<#
  Care Diagnostics — Scan Bridge one-file web installer (Windows)
  ---------------------------------------------------------------
  This file is downloaded from Form F ("Set up scanner" → Download installer)
  and is fully self-contained — it writes the bridge into your user profile,
  installs it, registers it to auto-start at logon, and verifies it responds.
  No folder to copy, no admin rights.

  Run:  right-click this file  →  "Run with PowerShell"

  (Generated by scan-bridge/build-web-installer.mjs from the real bridge source
  — do not edit by hand; edit the source and re-run the generator.)
#>
#Requires -Version 5.1
$ErrorActionPreference = "Stop"

function Pause-Exit($code) { Read-Host "Press Enter to close"; exit $code }
function Write-FileNoBom($path, $text) {
  $dir = Split-Path -Parent $path
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  [System.IO.File]::WriteAllText($path, $text, (New-Object System.Text.UTF8Encoding $false))
}

Write-Host ""
Write-Host "==  Care Diagnostics  -  Scan Bridge setup  ==" -ForegroundColor Cyan
Write-Host ""

# 1. Node.js present?
$nodeV = $null
try { $nodeV = (& node --version) 2>$null } catch { $nodeV = $null }
if (-not $nodeV) {
  Write-Host "Node.js is not installed." -ForegroundColor Red
  Write-Host "Install the LTS version from https://nodejs.org, then run this installer again."
  Start-Process "https://nodejs.org/en/download"
  Pause-Exit 1
}
Write-Host "Node.js $nodeV found." -ForegroundColor Green

# 2. Where the bridge lives (per-user profile — no admin needed)
$dest = Join-Path $env:LOCALAPPDATA "CareScanBridge"
Write-Host "Installing to: $dest"

# 3. Embedded bridge source (filled in by the generator)
$B = @{}
$B['package.json'] = @'
{
  "name": "care-diagnostics-scan-bridge",
  "version": "1.0.0",
  "private": true,
  "description": "Local document scanner bridge for Care Diagnostics ERP. Runs on each workstation, talks to WIA (Windows) or SANE (Linux) scanners and forwards scanned images to the ERP.",
  "type": "module",
  "main": "src/index.js",
  "scripts": {
    "start": "node src/index.js",
    "dev": "node --watch src/index.js"
  },
  "dependencies": {
    "express": "^5.0.0",
    "cors": "^2.8.5"
  }
}

'@

$B['src\index.js'] = @'
// Care Diagnostics Document Scan Bridge
// -------------------------------------------------------------
// Runs on each workstation that has a document scanner (flatbed or ADF).
// Browser pages call http://127.0.0.1:8766/* for scan/health.
// The bridge talks to:
//   • a vendor adapter (WIA / SANE / Folder-watch / Mock)
//   • returns base64 images to the ERP frontend
//
// Configuration via environment variables:
//   BRIDGE_SCAN_PORT        (default 8766)
//   BRIDGE_SCAN_VENDOR      mock | wia | sane | folder-watch
//   SCAN_WATCH_FOLDER       (folder-watch only) watched folder path
//   WIA_DEVICE_INDEX        1-based index for multiple WIA devices (default 1)
//   WIA_DPI                 Resolution for WIA scans (default 300)
//   SANE_DPI                Resolution for SANE scans (default 300)
//   ERP_BRIDGE_SECRET       shared secret; if set and BRIDGE_REQUIRE_AUTH=true,
//                           required on every request (except /health) via the
//                           X-Bridge-Secret header.
//   BRIDGE_REQUIRE_AUTH     "true" to enforce ERP_BRIDGE_SECRET (default false,
//                           so existing workstations upgrading the bridge are
//                           not locked out until every PC has the secret set —
//                           flip to true once rollout is complete).
//
// Endpoints:
//   GET  /health    → { ok: true, deviceConnected: true, vendor: "wia", ... }
//   GET  /devices   → { ok: true, devices: [{ index, name }] }
//   POST /scan      → { ok: true, imageBase64: "...", mimeType: "image/jpeg" }
//   POST /latest-scan → { ok: true, imageBase64: "...", filename: "..." }
//
// Security:
//   The bridge binds to 127.0.0.1 only. CORS allows the ERP origin derived
//   from ERP_BASE_URL or explicitly via BRIDGE_ALLOW_ORIGINS. Since the ERP is
//   typically served over HTTPS while this bridge is plain HTTP on loopback,
//   modern browsers additionally require a Private Network Access preflight
//   response (see the Access-Control-Allow-Private-Network header below) —
//   without it, an HTTPS-origin page's fetch to 127.0.0.1 is blocked even
//   though CORS itself would otherwise allow it.

import express from "express";
import cors from "cors";
import { loadAdapter } from "./adapters/index.js";
import { promises as fs, constants } from "node:fs";
import { join, basename, extname } from "node:path";
import { tmpdir } from "node:os";
import { execFile } from "node:child_process";

const PORT = Number(process.env.BRIDGE_SCAN_PORT ?? 8766);
const VENDOR = process.env.BRIDGE_SCAN_VENDOR ?? "mock";
const ERP_BASE = (process.env.ERP_BASE_URL ?? "").replace(/\/$/, "");

// BRIDGE_ALLOW_ORIGINS must be explicitly configured. Defaults to the ERP
// origin when ERP_BASE_URL is set, or denies all cross-origin requests.
const _rawAllow = process.env.BRIDGE_ALLOW_ORIGINS ?? "";
if (_rawAllow.trim() === "*") {
  console.error("[scan-bridge] FATAL: BRIDGE_ALLOW_ORIGINS=\"*\" is not permitted. Set it to the specific ERP origin, e.g. https://erp.yourdomain.com");
  process.exit(1);
}

let ALLOW;
if (_rawAllow.trim()) {
  ALLOW = _rawAllow.split(",").map((s) => s.trim()).filter(Boolean);
} else if (ERP_BASE) {
  try {
    ALLOW = [new URL(ERP_BASE).origin];
  } catch {
    ALLOW = [];
  }
} else {
  ALLOW = [];
}

const REQUIRE_AUTH = (process.env.BRIDGE_REQUIRE_AUTH ?? "false").trim().toLowerCase() === "true";
const ERP_SECRET = process.env.ERP_BRIDGE_SECRET ?? "";
if (REQUIRE_AUTH && !ERP_SECRET) {
  console.error("[scan-bridge] FATAL: BRIDGE_REQUIRE_AUTH=true but ERP_BRIDGE_SECRET is not set. Set ERP_BRIDGE_SECRET or disable BRIDGE_REQUIRE_AUTH.");
  process.exit(1);
}

let adapter;

const app = express();
app.use(express.json({ limit: "10mb" }));
app.use(cors({ origin: ALLOW.length > 0 ? ALLOW : false, credentials: false }));

// Private Network Access preflight: without this header, a browser page
// served over HTTPS (or any non-private origin) that fetches a loopback/
// private-network address like 127.0.0.1 gets its preflight silently
// rejected in Chromium-based browsers, independent of the CORS allow-list
// above. This is the fix for "Local Workstation Scanner: Offline" reports
// where the bridge is actually running and CORS-allowed but PNA still blocks
// the request.
app.use((req, res, next) => {
  if (req.method === "OPTIONS") {
    res.setHeader("Access-Control-Allow-Private-Network", "true");
  }
  next();
});

// Shared-secret auth (opt-in via BRIDGE_REQUIRE_AUTH). /health stays
// unauthenticated always, so the "is the bridge even running" poller in the
// ERP frontend keeps working before a secret has been provisioned on a new
// install.
app.use((req, res, next) => {
  if (!REQUIRE_AUTH || req.path === "/health") {
    next();
    return;
  }
  const provided = req.get("X-Bridge-Secret") ?? "";
  if (provided !== ERP_SECRET) {
    res.status(401).json({ ok: false, error: "Missing or invalid X-Bridge-Secret header" });
    return;
  }
  next();
});

// ── Health / device status ───────────────────────────────────────────────────────
app.get("/health", async (_req, res) => {
  try {
    const status = await adapter.status();
    res.json({
      ok: true,
      vendor: VENDOR,
      adapter: adapter.name,
      version: "1.0.0",
      authRequired: REQUIRE_AUTH,
      corsConfigured: ALLOW.length > 0,
      allowedOrigins: ALLOW,
      ...status,
    });
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message, vendor: VENDOR, adapter: adapter.name });
  }
});

// ── List all detected scanners ─────────────────────────────────────────────────
app.get("/devices", async (_req, res) => {
  try {
    if (typeof adapter.devices === "function") {
      const result = await adapter.devices();
      res.json({ ok: true, devices: result.devices || [] });
    } else {
      res.json({ ok: true, devices: [] });
    }
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message });
  }
});

// ── Scan a document and return base64 image ────────────────────────────────────
app.post("/scan", async (_req, res) => {
  try {
    const result = await adapter.scan();
    res.json({ ok: true, imageBase64: result.imageBase64, mimeType: result.mimeType ?? "image/jpeg", filename: result.filename || null });
  } catch (e) {
    const isWiaUnsupported = e.code === "WIA_UNSUPPORTED_DRIVER" || e.code === "WIA_NO_DEVICE";
    res.status(500).json({ ok: false, error: e.message, code: e.code || null, fallback: isWiaUnsupported ? "folder-watch" : null });
  }
});

// ── Latest-scan pickup: grab the newest image from a watched folder ───────────
// Must match adapters/folder-watch.js's default exactly — otherwise POST /scan
// (via the folder-watch adapter) and POST /latest-scan (this handler) silently
// look in two different folders, and "Import Latest Scan" never finds what a
// prior "Scan" call just picked up. Neither handler special-cases win32; if
// you configure a Windows-specific path, set SCAN_WATCH_FOLDER explicitly.
const SCAN_WATCH_FOLDER = process.env.SCAN_WATCH_FOLDER ?? join(tmpdir(), "care-scans");
const SCAN_PROCESSED_FOLDER = process.env.SCAN_PROCESSED_FOLDER ?? join(SCAN_WATCH_FOLDER, "processed");

const SCAN_EXTS = new Set(["jpg", "jpeg", "png", "pdf", "tiff", "tif", "bmp"]);
const MIME_MAP = {
  jpg: "image/jpeg", jpeg: "image/jpeg", png: "image/png",
  pdf: "application/pdf", tiff: "image/tiff", tif: "image/tiff", bmp: "image/bmp",
};

function extMatches(filename) {
  const ext = basename(filename).split(".").pop()?.toLowerCase() ?? "";
  return SCAN_EXTS.has(ext);
}
function mimeFromExt(filename) {
  const ext = basename(filename).split(".").pop()?.toLowerCase() ?? "";
  return MIME_MAP[ext] || "application/octet-stream";
}

app.post("/latest-scan", async (_req, res) => {
  try {
    let entries;
    try {
      entries = await fs.readdir(SCAN_WATCH_FOLDER, { withFileTypes: true });
    } catch (e) {
      res.status(500).json({ ok: false, error: `Cannot read watch folder "${SCAN_WATCH_FOLDER}": ${e.message}` });
      return;
    }

    const files = entries
      .filter((e) => e.isFile() && extMatches(e.name))
      .map((e) => ({ name: e.name, path: join(SCAN_WATCH_FOLDER, e.name) }));

    if (files.length === 0) {
      res.status(404).json({ ok: false, error: `No scan files found in "${SCAN_WATCH_FOLDER}". Please scan a document first.`, fallback: "folder-watch" });
      return;
    }

    // Find newest by mtime
    const withStats = await Promise.all(
      files.map(async (f) => {
        const stat = await fs.stat(f.path);
        return { ...f, mtime: stat.mtimeMs };
      })
    );
    withStats.sort((a, b) => b.mtime - a.mtime);
    const newest = withStats[0];

    const buffer = await fs.readFile(newest.path);
    const result = {
      ok: true,
      imageBase64: buffer.toString("base64"),
      mimeType: mimeFromExt(newest.name),
      filename: newest.name,
      pickedFrom: SCAN_WATCH_FOLDER,
    };

    // Move to processed folder after successful read
    try {
      await fs.mkdir(SCAN_PROCESSED_FOLDER, { recursive: true });
      const dest = join(SCAN_PROCESSED_FOLDER, newest.name);
      await fs.rename(newest.path, dest);
    } catch {
      // Non-fatal: keep the file in place if move fails
    }

    res.json(result);
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message });
  }
});

// ── Open scanner application on the workstation ───────────────────────────────
app.post("/open-scanner-app", async (_req, res) => {
  try {
    if (process.platform !== "win32") {
      res.status(400).json({ ok: false, error: "Opening scanner app is only supported on Windows" });
      return;
    }

    // Try Windows Fax and Scan first (built-in)
    try {
      await new Promise((resolve, reject) => {
        execFile("powershell", [
          "-Command",
          `Start-Process "wiaacmgr" -ErrorAction Stop`,
        ], { timeout: 5000, windowsHide: true }, (err) => {
          if (err) reject(err);
          else resolve();
        });
      });
      res.json({ ok: true, message: "Windows Fax and Scan opened. After scanning completes, click Import Latest Scan.", app: "wiaacmgr" });
      return;
    } catch {
      // Fallback: try to open any installed scanner utility
    }

    // Try any vendor scanner utility found in well-known locations
    const commonPaths = [
      "C:\\Program Files (x86)\\Canon\\IJ Scan Utility\\CNMNUTIL.exe",
      "C:\\Program Files\\Canon\\IJ Scan Utility\\CNMNUTIL.exe",
      "C:\\Program Files (x86)\\HP\\HP Scan\\Scan.exe",
      "C:\\Program Files\\HP\\HP Scan\\Scan.exe",
      "C:\\Program Files (x86)\\Epson\\Epson Scan 2\\Scan.exe",
      "C:\\Program Files\\Epson\\Epson Scan 2\\Scan.exe",
      "C:\\Program Files (x86)\\Brother\\BrScan.exe",
      "C:\\Program Files\\Brother\\BrScan.exe",
    ];
    for (const p of commonPaths) {
      try {
        await fs.access(p, constants.F_OK);
        await new Promise((resolve, reject) => {
          execFile("powershell", [
            "-Command",
            `Start-Process "${p}" -ErrorAction Stop`,
          ], { timeout: 5000, windowsHide: true }, (err) => {
            if (err) reject(err);
            else resolve();
          });
        });
        res.json({ ok: true, message: "Scanner software opened. After scanning completes, click Import Latest Scan.", app: "vendor-scan" });
        return;
      } catch {
        // Try next path
      }
    }

    res.status(404).json({
      ok: false,
      error: "No scanner application found on this workstation. If you're using a TVS PDS 8M or another USB document camera, use the \"Scan with TVS PDS 8M\" or \"Webcam\" option instead — those devices are camera-class hardware and don't have a Windows scanner app to open. Otherwise, scan using your scanner software and save to the watch folder, then click Import Latest Scan.",
    });
  } catch (e) {
    res.status(500).json({ ok: false, error: e.message });
  }
});

(async () => {
  try {
    adapter = await loadAdapter(VENDOR);
    console.log(`[scan-bridge] Loaded adapter: ${VENDOR} (${adapter.name})`);
    if (ALLOW.length === 0) {
      console.warn("[scan-bridge] WARNING: No BRIDGE_ALLOW_ORIGINS configured and ERP_BASE_URL is not set. Cross-origin browser requests will be blocked.");
    }

    app.listen(PORT, "127.0.0.1", () => {
      console.log(`[scan-bridge] Listening on http://127.0.0.1:${PORT}`);
      console.log(`[scan-bridge] ERP: ${ERP_BASE || "(not configured)"}`);
      console.log(`[scan-bridge] Allowed origins: ${ALLOW.join(", ") || "(none — CORS blocked)"}`);
    });
  } catch (e) {
    console.error("[scan-bridge] FATAL: Failed to load adapter:", e);
    process.exit(1);
  }
})();

'@

$B['src\adapters\index.js'] = @'
import wia from "./wia.js";
import sane from "./sane.js";
import folderWatch from "./folder-watch.js";
import mock from "./mock.js";

// Scanner adapter loader — picks the right driver.
// Each adapter must export: { status(), scan(), name }
export async function loadAdapter(vendor) {
  switch ((vendor || "mock").toLowerCase()) {
    case "wia":
      return wia;
    case "sane":
      return sane;
    case "folder-watch":
    case "folder":
      return folderWatch;
    case "mock":
    default:
      return mock;
  }
}

'@

$B['src\adapters\wia.js'] = @'
// Windows Image Acquisition (WIA) adapter — GENERIC for any scanner brand.
// Uses an embedded PowerShell script to trigger scanning via the WIA COM API.
// Works with any WIA-compatible flatbed or document-feeder (Canon, HP, Epson, Brother, Fujitsu, etc.).
//
// REAL DEPLOYMENT:
// 1. Ensure the scanner driver is installed and visible in Windows Fax and Scan.
// 2. Run the bridge with BRIDGE_SCAN_VENDOR=wia
// 3. If you have multiple scanners, set WIA_DEVICE_INDEX (1-based) to pick one.
// 4. If direct WIA fails, fall back to folder-watch mode:
//    BRIDGE_SCAN_VENDOR=folder-watch SCAN_WATCH_FOLDER="C:\\Scans"
//
// TROUBLESHOOTING:
// - "No WIA devices found": Install the scanner driver or check USB connection.
// - "Scanner is busy": Another app is using the scanner. Close it and retry.
// - "Driver does not support direct WIA scan": The scanner vendor blocked programmatic access.
//   Switch to folder-watch mode (see README).
// - Wrong scanner selected: Set WIA_DEVICE_INDEX env var, or call /devices to see the list.

import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const DEVICE_INDEX = Number(process.env.WIA_DEVICE_INDEX ?? "1");
const DPI = Number(process.env.WIA_DPI ?? "300");
const COLOR_MODE = Number(process.env.WIA_COLOR_MODE ?? "1"); // 1 = Color, 2 = Grayscale, 4 = B&W

// ── PowerShell: enumerate all WIA devices ───────────────────────────────────
const PS_DEVICES = `
try {
  $dm = New-Object -ComObject WIA.DeviceManager
  $devices = @()
  for ($i = 1; $i -le $dm.DeviceInfos.Count; $i++) {
    $name = $dm.DeviceInfos.Item($i).Properties("Name").Value
    $devices += "{ \"index\": $i, \"name\": \"$name\" }"
  }
  if ($devices.Count -eq 0) {
    Write-Output "[]"
  } else {
    Write-Output ("[" + ($devices -join ",") + "]")
  }
} catch {
  Write-Output "[]"
}`;

function execAsync(command, args, timeout = 60000, windowsHide = true) {
  return new Promise((resolve, reject) => {
    execFile(command, args, { timeout, windowsHide }, (err, stdout, stderr) => {
      if (err) reject(new Error(stderr || stdout || err.message));
      else resolve({ stdout, stderr });
    });
  });
}

function classifyError(msg) {
  const m = msg.toLowerCase();
  if (m.includes("no wia devices found") || m.includes("device infos.count") || m.includes("count -eq 0")) {
    const err = new Error("No WIA scanner found. Check USB connection and that the driver is installed.");
    err.code = "WIA_NO_DEVICE";
    return err;
  }
  if (m.includes("scanner is busy") || m.includes("busy") || m.includes("in use") || m.includes("0x80210006") || m.includes("0x8021000a") || m.includes("already in use") || m.includes("another app")) {
    const err = new Error("Scanner is busy. Close any other scanning software and retry.");
    err.code = "WIA_DEVICE_BUSY";
    return err;
  }
  if (m.includes("driver does not support") || m.includes("not supported") || m.includes("unsupported") || m.includes("0x80210015") || m.includes("0x8021000d") || m.includes("specified cast is not valid")) {
    const err = new Error("Scanner driver does not support direct WIA scan. Use folder-watch mode instead: set BRIDGE_SCAN_VENDOR=folder-watch and SCAN_WATCH_FOLDER to your scanner software's output folder.");
    err.code = "WIA_UNSUPPORTED_DRIVER";
    return err;
  }
  const err = new Error(`WIA scan failed: ${msg}`);
  err.code = "WIA_SCAN_FAILED";
  return err;
}

function buildPsScanScript(outputPath, deviceIndex, dpi, colorMode) {
  // Values are embedded directly — no param() block, so no parameter passing issues.
  // NOTE: PowerShell comments are '#', not '//'. Using '//' here previously made
  // the script a parse/cast failure ("Specified cast is not valid").
  const safePath = outputPath.replace(/'/g, "''");
  return `
$OutputPath = '${safePath}'
$DeviceIndex = ${deviceIndex}
$DPI = ${dpi}
$ColorMode = ${colorMode}
$ErrorActionPreference = "Stop"

# wiaFormatJPEG / wiaFormatBMP GUIDs
$wiaFormatJPEG = "{B96B3CAE-0728-11D3-9D7B-0000F81EF32E}"

try {
  $deviceManager = New-Object -ComObject WIA.DeviceManager
  if ($deviceManager.DeviceInfos.Count -eq 0) {
    Write-Error "No WIA devices found"
    exit 1
  }
  if ($DeviceIndex -gt $deviceManager.DeviceInfos.Count -or $DeviceIndex -lt 1) { $DeviceIndex = 1 }
  $deviceInfo = $deviceManager.DeviceInfos.Item($DeviceIndex)
  $device = $deviceInfo.Connect()
  $item = $device.Items.Item(1)

  # Best-effort DPI via WIA property IDs (6147 = Horizontal, 6148 = Vertical
  # Resolution; 6146 = Current Intent). Numeric IDs are far more reliable than
  # string names across drivers. Each set is wrapped so a rejection never aborts
  # the scan.
  foreach ($propId in 6147, 6148) {
    try { $item.Properties.Item($propId).Value = $DPI } catch { }
  }
  try { $item.Properties.Item(6146).Value = $ColorMode } catch { }

  # Transfer as JPEG. Passing the format GUID stops the driver returning a raw
  # type (BMP/TIFF) that then fails to cast/save. If the driver rejects an
  # explicit format, retry with its default and convert to JPEG below.
  $image = $null
  try {
    $image = $item.Transfer($wiaFormatJPEG)
  } catch {
    try { $image = $item.Transfer() } catch { }
  }

  if ($null -eq $image) {
    Write-Error "Transfer failed: the scanner driver does not support direct WIA scan. Use folder-watch mode instead."
    exit 1
  }

  # If it came back as something other than JPEG, convert it so SaveFile writes a
  # real JPEG (not BMP bytes in a .jpg).
  try {
    if ($image.FormatID -ne $wiaFormatJPEG) {
      $conv = New-Object -ComObject WIA.ImageProcess
      $conv.Filters.Add($conv.FilterInfos.Item("Convert").FilterID)
      $conv.Filters.Item($conv.Filters.Count).Properties.Item("FormatID").Value = $wiaFormatJPEG
      $image = $conv.Apply($image)
    }
  } catch { }

  if (Test-Path $OutputPath) { Remove-Item -LiteralPath $OutputPath -Force -ErrorAction SilentlyContinue }
  $image.SaveFile($OutputPath)
  Write-Output "OK"
} catch {
  $msg = $_.Exception.Message
  if ($msg -match "busy|in use|0x80210006|0x8021000A|already in use|another app") {
    Write-Error "Scanner is busy"
  } elseif ($msg -match "0x80210015|0x8021000D|not supported|unsupported") {
    Write-Error "Driver does not support direct WIA scan"
  } else {
    Write-Error $msg
  }
  exit 1
}`;
}

export default {
  name: "wia",

  async devices() {
    try {
      const { stdout } = await execAsync("powershell", [
        "-ExecutionPolicy", "Bypass",
        "-Command",
        PS_DEVICES,
      ], 15000);
      const devices = JSON.parse(stdout.trim() || "[]");
      return { devices };
    } catch (e) {
      return { devices: [], error: e.message };
    }
  },

  async status() {
    try {
      const { devices } = await this.devices();
      const selected = devices.find((d) => d.index === DEVICE_INDEX);
      return {
        deviceConnected: devices.length > 0,
        deviceCount: devices.length,
        deviceIndex: DEVICE_INDEX,
        selectedDevice: selected?.name || null,
        devices: devices.map((d) => ({ index: d.index, name: d.name })),
        type: "wia",
        dpi: DPI,
      };
    } catch (e) {
      return { deviceConnected: false, error: e.message, type: "wia" };
    }
  },

  async scan() {
    const outPath = join(tmpdir(), `scan-${Date.now()}.jpg`);
    const psScript = buildPsScanScript(outPath, DEVICE_INDEX, DPI, COLOR_MODE);
    const psPath = join(tmpdir(), `scan-${Date.now()}.ps1`);
    try {
      await fs.writeFile(psPath, psScript, "utf8");
      // windowsHide=false so the WIA CommonDialog.ShowTransfer() scanner dialog can appear.
      await execAsync("powershell", [
        "-ExecutionPolicy", "Bypass",
        "-File", psPath,
      ], 60000, false);
      const buffer = await fs.readFile(outPath);
      await fs.unlink(outPath).catch(() => {});
      const filename = outPath.split("\\").pop()?.split("/").pop() ?? "scan.jpg";
      return {
        ok: true,
        imageBase64: buffer.toString("base64"),
        mimeType: "image/jpeg",
        filename,
      };
    } catch (e) {
      throw classifyError(e.message || "");
    } finally {
      await fs.unlink(psPath).catch(() => {});
    }
  },
};

'@

$B['src\adapters\sane.js'] = @'
// SANE (Scanner Access Now Easy) adapter for Linux / macOS.
// Uses the system `scanimage` command (from sane-backends package).
//
// REAL DEPLOYMENT:
// 1. Install sane-backends:  sudo apt-get install sane-backends  (Debian/Ubuntu)
//                            sudo dnf install sane-backends     (Fedora)
//                            brew install sane-backends         (macOS)
// 2. Verify scanner is detected:  scanimage -L
// 3. Run the bridge with BRIDGE_SCAN_VENDOR=sane
//
// TROUBLESHOOTING:
// - "scanimage: no SANE devices found": Check USB connection / driver.
// - Permission denied on /dev/bus/usb: Add user to scanner group: sudo usermod -aG scanner $USER
// - macOS: You may need to install sane-backends via Homebrew and add the binary to PATH.

import { execFile } from "node:child_process";
import { promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";

const DPI = Number(process.env.SANE_DPI ?? "300");
const MODE = process.env.SANE_MODE ?? "Color"; // Color | Gray | Lineart

function execAsync(command, args) {
  return new Promise((resolve, reject) => {
    execFile(command, args, { timeout: 120000 }, (err, stdout, stderr) => {
      if (err) reject(new Error(stderr || stdout || err.message));
      else resolve({ stdout, stderr });
    });
  });
}

export default {
  name: "sane",
  async status() {
    try {
      const { stdout } = await execAsync("scanimage", ["-L"]);
      const lines = stdout.split("\n").filter((l) => l.includes("device "));
      return {
        deviceConnected: lines.length > 0,
        deviceCount: lines.length,
        devices: lines,
        type: "sane",
      };
    } catch (e) {
      return { deviceConnected: false, error: e.message, type: "sane" };
    }
  },

  async scan() {
    const outPath = join(tmpdir(), `scan-${Date.now()}.png`);
    try {
      await execAsync("scanimage", [
        "--format=png",
        `--resolution=${DPI}`,
        `--mode=${MODE}`,
        `--output-file=${outPath}`,
      ]);
      const buffer = await fs.readFile(outPath);
      await fs.unlink(outPath).catch(() => {});
      return {
        imageBase64: buffer.toString("base64"),
        mimeType: "image/png",
      };
    } catch (e) {
      throw new Error(`SANE scan failed: ${e.message}`);
    }
  },
};

'@

$B['src\adapters\folder-watch.js'] = @'
// Folder-watch adapter — for scanners that save images via their own software.
// The scanner's bundled application (or Windows Fax and Scan, VueScan, etc.)
// saves to a watched folder; this adapter returns the newest image file.
//
// CONFIGURATION (env vars):
//   SCAN_WATCH_FOLDER   Absolute path to the folder to watch (default: OS temp dir + /scans)
//   SCAN_FILE_PATTERN   Glob pattern to match scan files (default: *.jpg,*.jpeg,*.png,*.pdf,*.tiff,*.bmp)
//
// REAL DEPLOYMENT:
// 1. Configure your scanner software to save scans to SCAN_WATCH_FOLDER.
// 2. Run the bridge with BRIDGE_SCAN_VENDOR=folder-watch.
// 3. Staff clicks "Scanner" in the ERP → bridge returns the newest file.

import { promises as fs } from "node:fs";
import { join, basename } from "node:path";
import { tmpdir } from "node:os";

const WATCH_FOLDER = process.env.SCAN_WATCH_FOLDER ?? join(tmpdir(), "care-scans");
const FILE_PATTERNS = (process.env.SCAN_FILE_PATTERN ?? "*.jpg,*.jpeg,*.png,*.pdf,*.tiff,*.bmp")
  .split(",")
  .map((s) => s.trim().toLowerCase().replace(/^\*\./, ""));

function extMatches(filename) {
  const ext = basename(filename).split(".").pop()?.toLowerCase() ?? "";
  return FILE_PATTERNS.includes(ext);
}

function mimeFromExt(filename) {
  const ext = basename(filename).split(".").pop()?.toLowerCase() ?? "";
  const map = {
    jpg: "image/jpeg",
    jpeg: "image/jpeg",
    png: "image/png",
    pdf: "application/pdf",
    tiff: "image/tiff",
    tif: "image/tiff",
    bmp: "image/bmp",
  };
  return map[ext] || "application/octet-stream";
}

export default {
  name: "folder-watch",
  async status() {
    try {
      const entries = await fs.readdir(WATCH_FOLDER, { withFileTypes: true });
      const files = entries.filter((e) => e.isFile() && extMatches(e.name));
      return {
        deviceConnected: files.length > 0,
        watchFolder: WATCH_FOLDER,
        fileCount: files.length,
        type: "folder-watch",
      };
    } catch (e) {
      return {
        deviceConnected: false,
        watchFolder: WATCH_FOLDER,
        error: e.message,
        type: "folder-watch",
      };
    }
  },

  async scan() {
    let entries;
    try {
      entries = await fs.readdir(WATCH_FOLDER, { withFileTypes: true });
    } catch (e) {
      throw new Error(`Cannot read watch folder "${WATCH_FOLDER}": ${e.message}`);
    }

    const files = entries
      .filter((e) => e.isFile() && extMatches(e.name))
      .map((e) => ({ name: e.name, path: join(WATCH_FOLDER, e.name) }));

    if (files.length === 0) {
      throw new Error(
        `No scan files found in "${WATCH_FOLDER}". Please scan a document using your scanner software and save it to this folder, or configure SCAN_WATCH_FOLDER.`
      );
    }

    // Get file stats to find the newest
    const withStats = await Promise.all(
      files.map(async (f) => {
        const stat = await fs.stat(f.path);
        return { ...f, mtime: stat.mtimeMs };
      })
    );
    withStats.sort((a, b) => b.mtime - a.mtime);
    const newest = withStats[0];

    const buffer = await fs.readFile(newest.path);
    return {
      imageBase64: buffer.toString("base64"),
      mimeType: mimeFromExt(newest.name),
      // index.js's POST /scan handler reads `result.filename` (lowercase n) on
      // whatever adapter it calls; this was `fileName`, so the response always
      // carried filename: null for folder-watch scans (the image itself still
      // came through — a cosmetic miss, not a failure, but worth matching the
      // shared contract every other adapter (wia.js, mock.js) already uses).
      filename: newest.name,
    };
  },
};

'@

$B['src\adapters\mock.js'] = @'
// Mock adapter — for development and demos.
// Generates a test card image using canvas-like logic (a simple colored rectangle
// with text) encoded as base64 JPEG.
import crypto from "node:crypto";

function createTestImage() {
  // Simple 300x200 test pattern as raw RGB, then we’d need JPEG encoding.
  // For mock mode, we return a tiny 1x1 red pixel JPEG (base64).
  // This is a valid minimal JPEG.
  const tinyJpeg = Buffer.from(
    "/9j/4AAQSkZJRgABAQEASABIAAD/2wBDAP//////////////////////////////////////////////////////////////////////////////////////wAALCAABAAEBAREA/8QAFAABAAAAAAAAAAAAAAAAAAAAA//EABQQAQAAAAAAAAAAAAAAAAAAAAD/2gAIAQEAAD8Af//Z",
    "base64"
  );
  return {
    imageBase64: tinyJpeg.toString("base64"),
    mimeType: "image/jpeg",
    width: 1,
    height: 1,
  };
}

export default {
  name: "mock",
  async status() {
    return { deviceConnected: true, deviceModel: "mock-scanner", type: "mock" };
  },
  async scan() {
    // Simulate scan taking ~800ms
    await new Promise((r) => setTimeout(r, 800));
    return createTestImage();
  },
};

'@

foreach ($rel in $B.Keys) {
  Write-FileNoBom (Join-Path $dest $rel) $B[$rel]
}
Write-Host "Wrote bridge files."

# 4. Configuration
$defaultErp = "https://caredeoghar.com"
$erp = Read-Host "ERP web address (must match the browser URL) [$defaultErp]"
if ([string]::IsNullOrWhiteSpace($erp)) { $erp = $defaultErp }
$erp = $erp.TrimEnd('/')

Write-Host ""
Write-Host "Scanner type:"
Write-Host "  1) WIA          - any scanner listed in Windows 'Fax and Scan' (recommended)"
Write-Host "  2) folder-watch - your scanner's own software saves images to a folder"
$choice = Read-Host "Choose 1 or 2 [1]"
if ($choice -eq "2") {
  $vendor = "folder-watch"
  $watch = Read-Host "Folder your scanner software saves scans to (e.g. C:\Scans)"
} else {
  $vendor = "wia"
  $watch = ""
}

# 5. Dependencies
Write-Host ""
Write-Host "Installing dependencies (npm install)..." -ForegroundColor Cyan
Push-Location $dest
& npm install --omit=dev
$npmCode = $LASTEXITCODE
Pop-Location
if ($npmCode -ne 0) {
  Write-Host "npm install failed. Check your internet connection and try again." -ForegroundColor Red
  Pause-Exit 1
}

# 6. Start script with the chosen config baked in
$startCmd = Join-Path $dest "start-scan-bridge.cmd"
$cmdLines = @(
  "@echo off",
  "cd /d ""%~dp0""",
  "set ERP_BASE_URL=$erp",
  "set BRIDGE_SCAN_VENDOR=$vendor"
)
if ($vendor -eq "folder-watch") { $cmdLines += "set SCAN_WATCH_FOLDER=$watch" }
$cmdLines += "node src\index.js"
Write-FileNoBom $startCmd (($cmdLines -join "`r`n") + "`r`n")

# 7. Auto-start at logon (per-user task; no admin)
$taskName = "CareScanBridge"
$arg = '/c "' + $startCmd + '"'
try {
  Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
  $action   = New-ScheduledTaskAction -Execute "cmd.exe" -Argument $arg
  $trigger  = New-ScheduledTaskTrigger -AtLogOn
  $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -Hidden
  Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Description "Care Diagnostics document scan bridge" | Out-Null
  Write-Host "Registered auto-start task '$taskName' (starts at each logon)." -ForegroundColor Green
  Start-ScheduledTask -TaskName $taskName
} catch {
  Write-Host "Could not register the auto-start task: $($_.Exception.Message)" -ForegroundColor Yellow
  Write-Host "Starting the bridge directly instead (it won't auto-start after reboot)."
  Start-Process -FilePath "cmd.exe" -ArgumentList $arg -WindowStyle Hidden
}

# 8. Verify
Write-Host ""
Write-Host "Verifying the bridge is responding..." -ForegroundColor Cyan
$ok = $false; $vendorReported = ""
for ($i = 0; $i -lt 6 -and -not $ok; $i++) {
  Start-Sleep -Seconds 2
  try {
    $health = Invoke-RestMethod -Uri "http://127.0.0.1:8766/health" -TimeoutSec 4
    if ($health.ok) { $ok = $true; $vendorReported = $health.vendor }
  } catch { }
}
Write-Host ""
if ($ok) {
  Write-Host "SUCCESS - scan bridge is running (vendor: $vendorReported)." -ForegroundColor Green
  Write-Host "Go back to Form F and the 'Existing Scanner' tab will show Online." -ForegroundColor Green
} else {
  Write-Host "The bridge did not answer on http://127.0.0.1:8766 yet." -ForegroundColor Yellow
  Write-Host "Give it a few seconds and refresh Form F. If it stays offline, confirm Node.js is on PATH."
}
Pause-Exit 0
