-- Structured-json cache + render-context columns (Radiology Implementation
-- Roadmap, Ticket A2; Strand A of the approved consolidation architecture).
--
-- radiology_report_drafts and patient_reports are existing, populated, hot
-- tables — every column added here is NULLABLE with NO DEFAULT, so each
-- statement is a metadata-only operation (no table rewrite, no full-table
-- scan, no lock beyond a brief ACCESS EXCLUSIVE for the catalog update).
-- Nothing reads or writes these columns yet: structured_json is a
-- denormalized cache regenerated by a later ticket (A4), never a source of
-- truth; the three version columns on patient_reports exist so a later
-- ticket can freeze which renderEngine/template/catalog version produced
-- the signed `body` at signature, without altering `body` itself, which
-- remains the authoritative append-only record.

ALTER TABLE radiology_report_drafts ADD COLUMN IF NOT EXISTS structured_json jsonb;

ALTER TABLE patient_reports ADD COLUMN IF NOT EXISTS structured_json       jsonb;
ALTER TABLE patient_reports ADD COLUMN IF NOT EXISTS render_engine_version text;
ALTER TABLE patient_reports ADD COLUMN IF NOT EXISTS template_version      text;
ALTER TABLE patient_reports ADD COLUMN IF NOT EXISTS catalog_version       text;
