-- CARE X-Ray Gold Standard — Knowledge Pack REGISTRY (40 X-Ray / DR studies).
--
-- Each row is a MANIFEST naming an X-Ray study and declaring its pack-level
-- clinical rules (companion follow-ups, copilot modules, comparison targets,
-- critical findings, recommendations, quality rules, references). Live content
-- (protocols / findings / history / measurements / impression rules / knowledge)
-- is authored into the existing tables in the sibling
-- zzzz_xr_gold_standard_content.sql / zzzz_xr_impression_rules_knowledge.sql and
-- assembled live by the loader — no reporting code is copied.
--
-- X-Ray reporting philosophy: most plain radiographs are DESCRIPTIVE. Packs that
-- carry no clinically-standard measurement declare "measurements" in
-- notApplicableSections so the readiness score is not penalized for an absence
-- that is correct (see knowledgePackManifest.ts). Measurements are seeded only
-- where they are standard practice (CTR, Cobb, vertebral height, joint space,
-- stone size, prevertebral soft-tissue thickness).
--
-- Companion follow-ups are DATA (companionRules) — never hardcoded React.
-- Copilot reuses the existing generic modules (comparison + measurement
-- completeness); extremity trauma studies SHARE the xr_extremity builder_type so
-- one deterministic rule set covers them all. No X-Ray Copilot/Companion V2.
--
-- Idempotent: replaces the coarse XR placeholders from the Knowledge Pack Engine
-- seed, then inserts the full 40 as system packs (ON CONFLICT DO NOTHING on
-- re-run; system packs are guarded from the delete). Named zzzz_ so it sorts
-- AFTER every base + z* schema migration (feature migrations run alphabetically).

DELETE FROM knowledge_packs WHERE modality = 'XR' AND is_system = FALSE;

INSERT INTO knowledge_packs
  (pack_id, modality, name, description, category, study_type, builder_type, body_part, knowledge_category, version, author, status, is_system, manifest_json)
VALUES
  -- ── Chest ────────────────────────────────────────────────────────────────
  ('xr.chest_pa', 'XR', 'Chest X-Ray PA Pack', 'PA chest radiograph — the flagship general radiograph.', 'Chest', 'X-Ray Chest PA', 'xr_chest', 'CHEST', 'Chest', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Opacity -> lobar or diffuse? air bronchogram? volume loss/collapse? associated effusion?","Pleural effusion -> side? size (blunting vs opacification)? meniscus? mediastinal shift?","Pneumothorax -> side? size? tension (mediastinal shift, deep sulcus)?","Cardiomegaly -> CTR? upper-lobe diversion / pulmonary edema?","Lung nodule -> size? margins? calcification? single or multiple?"],"comparisonMeasurements":["Cardiothoracic ratio","Lung opacity","Pleural effusion","Nodule size"],"criticalFindings":["Tension pneumothorax","Large pleural effusion","Free subdiaphragmatic air","Widened mediastinum"],"recommendations":["Clinical correlation","Chest CT for a suspicious or persistent opacity/nodule","Follow-up chest radiograph after treatment","Emergency referral for tension pneumothorax"],"qualityRules":["State CTR when the cardiac silhouette looks enlarged","Assess for rotation and adequate inspiration before calling volumes","Comment on both costophrenic angles"],"references":["Fleischner Society nodule guidelines","Cardiothoracic ratio (normal < 0.5 on PA)"],"reportingNotes":"Erect PA at full inspiration; the reference chest projection."}'),
  ('xr.chest_ap', 'XR', 'Chest X-Ray AP Pack', 'AP chest radiograph (supine / paediatric / ICU).', 'Chest', 'X-Ray Chest AP', 'xr_chest', 'CHEST', 'Chest', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Opacity -> lobar or diffuse? effusion? collapse?","Cardiomegaly -> note AP magnification (CTR overestimated on AP)?"],"comparisonMeasurements":["Lung opacity","Pleural effusion"],"criticalFindings":["Tension pneumothorax","Large pleural effusion","Free subdiaphragmatic air"],"recommendations":["Clinical correlation","Erect PA for accurate cardiac size","Chest CT for suspicious opacity"],"qualityRules":["State that AP/supine technique magnifies the heart and alters effusion appearance"],"references":["AP vs PA projection pitfalls"]}'),
  ('xr.portable_chest', 'XR', 'Portable Chest X-Ray Pack', 'Bedside / ICU chest — tube and line position.', 'Chest', 'X-Ray Portable Chest', 'xr_chest', 'CHEST', 'Chest', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["ET tube -> tip position relative to carina (5 +/- 2 cm)? too low/endobronchial? too high?","NG tube -> below the diaphragm and crossing the midline? tip in stomach? coiled/in bronchus?","Central line -> tip at cavoatrial junction? kink? pneumothorax post-insertion?","New opacity -> consolidation vs collapse vs effusion vs edema?"],"comparisonMeasurements":["ET tube tip position","NG tube position","Central line tip","Lung opacity"],"criticalFindings":["Misplaced ET tube (endobronchial or oesophageal)","Misplaced NG tube (bronchial/coiled)","Tension pneumothorax","Post-line pneumothorax"],"recommendations":["Immediate correlation for any misplaced tube/line before use","Reposition and repeat film as indicated"],"qualityRules":["Always state ET tube tip-to-carina distance","Confirm NG tube crosses the diaphragm in the midline and the tip is sub-diaphragmatic"],"references":["Safe NG tube placement (tip below diaphragm, bisects carina)"],"notApplicableSections":["measurements"]}'),
  ('xr.chest_lateral', 'XR', 'Chest X-Ray Lateral Pack', 'Lateral chest — retrocardiac/retrosternal, localization.', 'Chest', 'X-Ray Chest Lateral', 'xr_chest', 'CHEST', 'Chest', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Lateral -> retrocardiac opacity? posterior costophrenic blunting? vertebral density?"],"comparisonMeasurements":["Lung opacity","Pleural effusion"],"criticalFindings":["Large pleural effusion"],"recommendations":["Correlate with the frontal projection","Chest CT for a localized opacity"],"notApplicableSections":["measurements"]}'),
  ('xr.ribs', 'XR', 'Rib X-Ray Pack', 'Rib radiograph — trauma, lesion.', 'Chest', 'X-Ray Ribs', 'xr_ribs', 'RIBS', 'Chest', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Rib fracture -> which ribs? single or multiple? flail segment? underlying pneumothorax/haemothorax?"],"comparisonMeasurements":["Fracture healing"],"criticalFindings":["Flail segment","Pneumothorax","Haemothorax"],"recommendations":["Clinical correlation","CT chest for suspected haemo/pneumothorax or multiple fractures"],"qualityRules":["Always look for associated pneumothorax/effusion with rib fractures"],"notApplicableSections":["measurements"]}'),
  ('xr.sternum', 'XR', 'Sternum X-Ray Pack', 'Sternum radiograph — trauma.', 'Chest', 'X-Ray Sternum', 'xr_sternum', 'STERNUM', 'Chest', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Sternal fracture -> site? displacement? retrosternal haematoma?"],"comparisonMeasurements":["Fracture healing"],"criticalFindings":["Displaced sternal fracture"],"recommendations":["Clinical correlation","CT for suspected mediastinal injury"],"notApplicableSections":["measurements"]}'),

  -- ── Abdomen ──────────────────────────────────────────────────────────────
  ('xr.abdomen_ap', 'XR', 'Abdomen X-Ray AP Pack', 'Supine AP abdomen radiograph.', 'Abdomen', 'X-Ray Abdomen AP', 'xr_abdomen', 'ABDOMEN', 'Abdomen', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Bowel gas -> dilated loops? small vs large bowel? valvulae vs haustra? air-fluid on erect?","Calcification -> renal/ureteric calculus? phlebolith? gallstone?","Abnormal gas -> pneumoperitoneum? gas in bowel wall? Rigler sign?"],"comparisonMeasurements":["Bowel calibre"],"criticalFindings":["Bowel obstruction","Pneumoperitoneum","Toxic megacolon"],"recommendations":["Erect abdomen / erect chest for free air","Clinical correlation","CT abdomen for suspected obstruction or perforation"],"qualityRules":["Correlate supine dilatation with an erect film for air-fluid levels"],"references":["Small-bowel dilatation > 3 cm; large bowel > 6 cm; caecum > 9 cm"],"notApplicableSections":["measurements"]}'),
  ('xr.erect_abdomen', 'XR', 'Erect Abdomen X-Ray Pack', 'Erect abdomen — obstruction / perforation.', 'Abdomen', 'X-Ray Erect Abdomen', 'xr_abdomen', 'ABDOMEN', 'Abdomen', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Air-fluid levels -> multiple? step-ladder? >2.5 cm?","Free air -> subdiaphragmatic gas? which side?"],"comparisonMeasurements":["Bowel calibre"],"criticalFindings":["Bowel obstruction","Pneumoperitoneum","Sigmoid/caecal volvulus"],"recommendations":["Erect chest to confirm subdiaphragmatic free air","Surgical correlation for obstruction or perforation","CT abdomen for confirmation and cause"],"qualityRules":["State whether free subdiaphragmatic gas is present","Describe air-fluid levels (number, step-ladder pattern)"],"notApplicableSections":["measurements"]}'),
  ('xr.kub', 'XR', 'X-Ray KUB Pack', 'KUB radiograph — radio-opaque calculi.', 'Abdomen', 'X-Ray KUB', 'xr_kub', 'ABDOMEN', 'Abdomen', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Calcification -> renal/ureteric line? size? distinguish from phlebolith (rounded, lucent centre)?"],"comparisonMeasurements":["Stone size","Stone position"],"criticalFindings":["Large staghorn calculus"],"recommendations":["Ultrasound KUB for hydronephrosis","CT KUB (stone protocol) for radiolucent calculi and accurate sizing","Urology correlation"],"qualityRules":["State that KUB detects only radio-opaque calculi; radiolucent stones need CT/US"],"references":["~90% of urinary calculi are radio-opaque"]}'),

  -- ── Pelvis / Hip ───────────────────────────────────────────────────────────
  ('xr.pelvis_ap', 'XR', 'Pelvis X-Ray AP Pack', 'AP pelvis — trauma, hip, arthritis.', 'Pelvis', 'X-Ray Pelvis AP', 'xr_pelvis', 'PELVIS', 'MSK', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Pelvic fracture -> which ring elements? single or double break (unstable)? acetabulum?","Hip -> neck-of-femur fracture? Shenton line broken? joint space? avascular necrosis?"],"comparisonMeasurements":["Fracture healing","Hip joint space","Alignment"],"criticalFindings":["Unstable pelvic ring fracture","Hip/neck-of-femur fracture","Acetabular fracture"],"recommendations":["Orthopaedic opinion for any fracture","CT pelvis for acetabular/complex ring injury","MRI hip for occult neck-of-femur fracture if radiograph normal but clinically suspected"],"qualityRules":["Assess both Shenton lines and the pelvic ring at all break points"],"references":["Shenton line","Pelvic ring double-break = unstable"],"notApplicableSections":["measurements"]}'),
  ('xr.hip', 'XR', 'Hip X-Ray Pack', 'Hip radiograph — fracture, arthritis, AVN.', 'Pelvis', 'X-Ray Hip', 'xr_pelvis', 'HIP', 'MSK', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Neck-of-femur fracture -> displaced? Garden grade? intra- vs extracapsular?","Arthritis -> joint-space loss? osteophytes? AVN (crescent sign, collapse)?"],"comparisonMeasurements":["Fracture healing","Hip joint space","Alignment"],"criticalFindings":["Neck-of-femur fracture","Hip dislocation","Avascular necrosis with collapse"],"recommendations":["Urgent orthopaedic referral for fracture or dislocation","MRI hip for occult fracture or early AVN"],"qualityRules":["State intra- vs extracapsular and displacement for NOF fractures"],"references":["Garden classification","Shenton line"],"notApplicableSections":["measurements"]}'),
  ('xr.sacrum', 'XR', 'Sacrum X-Ray Pack', 'Sacral radiograph — trauma.', 'Pelvis', 'X-Ray Sacrum', 'xr_pelvis', 'SACRUM', 'MSK', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Sacral fracture -> zone (Denis)? foraminal involvement?"],"comparisonMeasurements":["Fracture healing","Alignment"],"criticalFindings":["Sacral fracture with neural involvement"],"recommendations":["CT/MRI for suspected sacral fracture","Orthopaedic/spine correlation"],"notApplicableSections":["measurements"]}'),
  ('xr.coccyx', 'XR', 'Coccyx X-Ray Pack', 'Coccyx radiograph — trauma.', 'Pelvis', 'X-Ray Coccyx', 'xr_pelvis', 'COCCYX', 'MSK', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Coccyx -> fracture? dislocation? angulation?"],"comparisonMeasurements":["Alignment"],"criticalFindings":[],"recommendations":["Clinical correlation; usually managed conservatively"],"notApplicableSections":["measurements"]}'),

  -- ── Lower limb (shared xr_extremity trauma builder) ──────────────────────────
  ('xr.femur', 'XR', 'Femur X-Ray Pack', 'Femur radiograph — fracture, lesion.', 'MSK', 'X-Ray Femur', 'xr_extremity', 'FEMUR', 'MSK', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Femoral fracture -> site (neck/shaft/supracondylar)? displacement? angulation? comminution?","Bone lesion -> lytic/sclerotic? margin? periosteal reaction?"],"comparisonMeasurements":["Fracture healing","Alignment","Bone lesion size"],"criticalFindings":["Displaced femoral fracture","Pathological fracture"],"recommendations":["Orthopaedic referral","MRI/CT for a bone lesion or pathological fracture"],"notApplicableSections":["measurements"]}'),
  ('xr.knee', 'XR', 'Knee X-Ray Pack', 'Knee radiograph — trauma, OA, effusion.', 'MSK', 'X-Ray Knee', 'xr_extremity', 'KNEE', 'MSK', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Fracture -> tibial plateau? patella? Segond (ACL)? lipohaemarthrosis?","Osteoarthritis -> compartment? joint-space narrowing? osteophytes? subchondral sclerosis?","Effusion -> suprapatellar distension? fat-fluid level?"],"comparisonMeasurements":["Joint space","Fracture healing","Alignment"],"criticalFindings":["Tibial plateau fracture","Lipohaemarthrosis (occult fracture)","Knee dislocation"],"recommendations":["Orthopaedic opinion for fracture","CT for tibial plateau assessment","MRI for internal derangement (ligament/meniscus)"],"qualityRules":["A lipohaemarthrosis implies an intra-articular fracture even if not directly seen","Grade OA by compartment and joint-space loss"],"references":["Kellgren-Lawrence OA grading"]}'),
  ('xr.leg', 'XR', 'Leg (Tibia-Fibula) X-Ray Pack', 'Tibia/fibula radiograph — fracture.', 'MSK', 'X-Ray Leg', 'xr_extremity', 'LEG', 'MSK', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Tibia/fibula fracture -> site? displacement? angulation? joint extension (plafond)?"],"comparisonMeasurements":["Fracture healing","Alignment"],"criticalFindings":["Displaced/open fracture","Compartment concern"],"recommendations":["Orthopaedic referral","Include ankle and knee joints"],"notApplicableSections":["measurements"]}'),
  ('xr.ankle', 'XR', 'Ankle X-Ray Pack', 'Ankle radiograph — fracture, mortise.', 'MSK', 'X-Ray Ankle', 'xr_extremity', 'ANKLE', 'MSK', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Ankle fracture -> malleolus (medial/lateral/posterior)? Weber level? mortise symmetry? talar shift?","Soft tissue -> swelling? effusion?"],"comparisonMeasurements":["Fracture healing","Mortise alignment"],"criticalFindings":["Unstable bimalleolar/trimalleolar fracture","Talar shift / mortise disruption"],"recommendations":["Orthopaedic opinion for unstable/displaced fracture","CT for complex or intra-articular fracture"],"qualityRules":["Assess mortise symmetry and the medial clear space"],"references":["Weber (Danis-Weber) classification","Ottawa ankle rules"],"notApplicableSections":["measurements"]}'),
  ('xr.foot', 'XR', 'Foot X-Ray Pack', 'Foot radiograph — fracture.', 'MSK', 'X-Ray Foot', 'xr_extremity', 'FOOT', 'MSK', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Foot fracture -> which bone? 5th metatarsal base? Lisfranc alignment? calcaneus (Bohler angle)?"],"comparisonMeasurements":["Fracture healing","Alignment"],"criticalFindings":["Lisfranc injury","Calcaneal fracture"],"recommendations":["Orthopaedic opinion","CT for Lisfranc/calcaneal assessment"],"notApplicableSections":["measurements"]}'),

  -- ── Upper limb (shared xr_extremity) ─────────────────────────────────────────
  ('xr.shoulder', 'XR', 'Shoulder X-Ray Pack', 'Shoulder radiograph — dislocation, fracture.', 'MSK', 'X-Ray Shoulder', 'xr_extremity', 'SHOULDER', 'MSK', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Dislocation -> anterior (sub-coracoid) or posterior (light-bulb sign)? Hill-Sachs / Bankart? glenohumeral alignment?","Fracture -> proximal humerus? greater tuberosity? clavicle? ACJ?"],"comparisonMeasurements":["Fracture healing","Alignment"],"criticalFindings":["Shoulder dislocation","Displaced proximal humeral fracture"],"recommendations":["Orthopaedic opinion / reduction for dislocation","Post-reduction film","CT for complex proximal humeral fracture"],"qualityRules":["Assess glenohumeral alignment on an axial/Y view; posterior dislocation is easily missed on AP"],"references":["Light-bulb sign (posterior dislocation)"],"notApplicableSections":["measurements"]}'),
  ('xr.clavicle', 'XR', 'Clavicle X-Ray Pack', 'Clavicle radiograph — fracture.', 'MSK', 'X-Ray Clavicle', 'xr_extremity', 'CLAVICLE', 'MSK', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Clavicle fracture -> third (middle/lateral/medial)? displacement? shortening? ACJ involvement?"],"comparisonMeasurements":["Fracture healing"],"criticalFindings":["Displaced clavicle fracture with skin tenting"],"recommendations":["Orthopaedic opinion for displaced/lateral-third fracture"],"notApplicableSections":["measurements"]}'),
  ('xr.scapula', 'XR', 'Scapula X-Ray Pack', 'Scapula radiograph — fracture.', 'MSK', 'X-Ray Scapula', 'xr_extremity', 'SCAPULA', 'MSK', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Scapular fracture -> body/neck/glenoid/acromion? associated rib or lung injury?"],"comparisonMeasurements":["Fracture healing"],"criticalFindings":["Scapular fracture with associated thoracic injury"],"recommendations":["CT for glenoid involvement","Assess for associated chest injury"],"notApplicableSections":["measurements"]}'),
  ('xr.humerus', 'XR', 'Humerus X-Ray Pack', 'Humerus radiograph — fracture, lesion.', 'MSK', 'X-Ray Humerus', 'xr_extremity', 'HUMERUS', 'MSK', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Humeral fracture -> site? displacement? spiral (radial nerve risk)? pathological?","Bone lesion -> lytic/sclerotic? margin?"],"comparisonMeasurements":["Fracture healing","Alignment","Bone lesion size"],"criticalFindings":["Displaced fracture","Pathological fracture"],"recommendations":["Orthopaedic referral","MRI/CT for bone lesion"],"notApplicableSections":["measurements"]}'),
  ('xr.elbow', 'XR', 'Elbow X-Ray Pack', 'Elbow radiograph — fracture, effusion.', 'MSK', 'X-Ray Elbow', 'xr_extremity', 'ELBOW', 'MSK', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Effusion -> raised anterior/posterior fat pad (occult fracture)?","Fracture -> radial head? supracondylar? anterior humeral line? paediatric ossification order?"],"comparisonMeasurements":["Fracture healing","Alignment"],"criticalFindings":["Supracondylar fracture with displacement","Posterior fat-pad sign (occult fracture)"],"recommendations":["Orthopaedic opinion","A posterior fat pad implies fracture even if none is seen"],"qualityRules":["Assess the anterior humeral line and radiocapitellar line"],"notApplicableSections":["measurements"]}'),
  ('xr.forearm', 'XR', 'Forearm X-Ray Pack', 'Radius/ulna radiograph — fracture.', 'MSK', 'X-Ray Forearm', 'xr_extremity', 'FOREARM', 'MSK', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Forearm fracture -> radius/ulna? Monteggia/Galeazzi? both joints imaged? angulation?"],"comparisonMeasurements":["Fracture healing","Alignment"],"criticalFindings":["Monteggia / Galeazzi fracture-dislocation"],"recommendations":["Include elbow and wrist joints","Orthopaedic opinion for fracture-dislocation"],"notApplicableSections":["measurements"]}'),
  ('xr.wrist', 'XR', 'Wrist X-Ray Pack', 'Wrist radiograph — distal radius, scaphoid.', 'MSK', 'X-Ray Wrist', 'xr_extremity', 'WRIST', 'MSK', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Distal radius fracture -> Colles/Smith? intra-articular? dorsal/volar tilt? ulnar styloid?","Scaphoid -> tenderness? fracture (may be occult)? scapholunate widening?"],"comparisonMeasurements":["Fracture healing","Alignment"],"criticalFindings":["Displaced/intra-articular distal radius fracture","Scapholunate dissociation"],"recommendations":["Orthopaedic opinion for displaced/intra-articular fracture","Scaphoid views; MRI/repeat film for suspected occult scaphoid fracture"],"qualityRules":["State dorsal/volar tilt and intra-articular extension for distal radius fractures"],"references":["Colles / Smith fracture patterns"],"notApplicableSections":["measurements"]}'),
  ('xr.hand', 'XR', 'Hand X-Ray Pack', 'Hand radiograph — fracture, arthritis.', 'MSK', 'X-Ray Hand', 'xr_extremity', 'HAND', 'MSK', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Fracture -> which metacarpal/phalanx? intra-articular? rotation/angulation?","Arthritis -> distribution (MCP/PIP/DIP)? erosions? joint-space loss? soft-tissue swelling? chondrocalcinosis?"],"comparisonMeasurements":["Fracture healing","Joint erosion"],"criticalFindings":["Open/displaced fracture","Aggressive bone lesion"],"recommendations":["Orthopaedic/hand opinion for displaced or rotated fracture","Rheumatology correlation for an inflammatory arthropathy"],"qualityRules":["Describe arthritis by distribution and erosion pattern"],"notApplicableSections":["measurements"]}'),
  ('xr.finger', 'XR', 'Finger X-Ray Pack', 'Finger radiograph — fracture, dislocation.', 'MSK', 'X-Ray Finger', 'xr_extremity', 'FINGER', 'MSK', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Finger injury -> phalanx? intra-articular? volar plate avulsion? dislocation?"],"comparisonMeasurements":["Fracture healing","Alignment"],"criticalFindings":["Open/displaced fracture-dislocation"],"recommendations":["Orthopaedic/hand opinion for intra-articular or displaced injury"],"notApplicableSections":["measurements"]}'),
  ('xr.thumb', 'XR', 'Thumb X-Ray Pack', 'Thumb radiograph — Bennett/Rolando.', 'MSK', 'X-Ray Thumb', 'xr_extremity', 'THUMB', 'MSK', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Thumb base -> Bennett (intra-articular 2-part) or Rolando (comminuted)? UCL avulsion (gamekeeper)?"],"comparisonMeasurements":["Fracture healing","Alignment"],"criticalFindings":["Bennett / Rolando fracture-dislocation"],"recommendations":["Orthopaedic/hand opinion for base-of-thumb fracture"],"notApplicableSections":["measurements"]}'),

  -- ── Spine ────────────────────────────────────────────────────────────────
  ('xr.cervical_spine', 'XR', 'Cervical Spine X-Ray Pack', 'C-spine AP/lateral/odontoid — trauma, degeneration.', 'Spine', 'X-Ray Cervical Spine', 'xr_cervical_spine', 'CERVICAL_SPINE', 'Spine', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Alignment -> anterior/posterior vertebral and spinolaminar lines intact? listhesis?","Fracture -> level? odontoid (type II)? C7-T1 junction visualized?","Degeneration -> disc-space narrowing? osteophytes? prevertebral soft-tissue widening?"],"comparisonMeasurements":["Vertebral body height","Listhesis","Prevertebral soft tissue"],"criticalFindings":["Unstable cervical fracture","Cervical spine instability / listhesis","Prevertebral soft-tissue swelling (occult injury)"],"recommendations":["Maintain spinal precautions until cleared","CT cervical spine for suspected/inadequately-imaged fracture","MRI for cord or ligamentous injury"],"qualityRules":["Adequacy requires C7-T1 visualization","Trace all three lordotic lines; assess prevertebral soft tissue"],"references":["Canadian C-spine rule","Prevertebral soft tissue: <7 mm at C2, <22 mm at C6"]}'),
  ('xr.dorsal_spine', 'XR', 'Dorsal Spine X-Ray Pack', 'Thoracic spine AP/lateral — compression, degeneration.', 'Spine', 'X-Ray Dorsal Spine', 'xr_dorsal_spine', 'DORSAL_SPINE', 'Spine', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Compression fracture -> level? wedge? % height loss? acute vs old?","Kyphosis -> increased? Scheuermann?","Degeneration -> disc-space narrowing? osteophytes?"],"comparisonMeasurements":["Vertebral body height","Kyphosis angle"],"criticalFindings":["Unstable/burst thoracic fracture","Multiple compression fractures"],"recommendations":["MRI to age a compression fracture and assess the cord","Spine/orthopaedic correlation","DEXA if osteoporotic fracture suspected"],"qualityRules":["State % vertebral height loss for compression fractures"],"references":["Genant semiquantitative grading"]}'),
  ('xr.lumbar_spine', 'XR', 'Lumbar Spine X-Ray Pack', 'L-spine AP/lateral (± flexion-extension) — degeneration, listhesis.', 'Spine', 'X-Ray Lumbar Spine', 'xr_lumbar_spine', 'LS_SPINE', 'Spine', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Spondylolisthesis -> level? Meyerding grade? pars defect? mobile on flexion-extension?","Compression fracture -> level? % height loss?","Degeneration -> disc-space narrowing? osteophytes? facet arthropathy? transitional vertebra?"],"comparisonMeasurements":["Vertebral body height","Listhesis","Disc-space height"],"criticalFindings":["Unstable spondylolisthesis / instability on flexion-extension","Burst fracture"],"recommendations":["MRI for radiculopathy, canal/cord and marrow assessment","Flexion-extension views for suspected instability","Spine correlation"],"qualityRules":["Grade spondylolisthesis (Meyerding)","Assess mobility on flexion-extension for instability"],"references":["Meyerding grading"]}'),
  ('xr.whole_spine', 'XR', 'Whole Spine X-Ray Pack', 'Scoliosis / full-length spine — Cobb angle.', 'Spine', 'X-Ray Whole Spine', 'xr_whole_spine', 'WHOLE_SPINE', 'Spine', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Scoliosis -> Cobb angle? apex level? direction (convexity)? Risser grade (skeletal maturity)?","Balance -> coronal/sagittal balance? kyphosis/lordosis?"],"comparisonMeasurements":["Cobb angle","Coronal balance","Curve progression"],"criticalFindings":["Rapidly progressive curve","Congenital vertebral anomaly with instability"],"recommendations":["Cobb > 25 deg / progressing: orthopaedic (scoliosis) referral","Serial standing whole-spine films to monitor progression","Same technique/landmarks on follow-up"],"qualityRules":["Standing full-length film; measure Cobb from the same end-vertebrae as prior","State Risser grade for skeletal maturity"],"references":["Cobb angle","Risser grading","Curve >10 deg = scoliosis; surgery generally considered > 45-50 deg"]}'),

  -- ── Skull / Head & Neck ─────────────────────────────────────────────────────
  ('xr.skull', 'XR', 'Skull X-Ray Pack', 'Skull AP/lateral — fracture, lesion.', 'Head & Neck', 'X-Ray Skull', 'xr_skull', 'SKULL', 'Head & Neck', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Fracture -> linear vs depressed? crosses a vascular groove/suture? distinguish from suture/vascular marking?","Lesion -> lytic/sclerotic? margin?"],"comparisonMeasurements":["Bone lesion size"],"criticalFindings":["Depressed skull fracture","Fracture crossing the middle meningeal groove"],"recommendations":["CT head is the investigation of choice for significant head injury","Neurosurgical correlation for a depressed fracture"],"qualityRules":["CT — not plain films — is standard for head trauma; state this where relevant"],"notApplicableSections":["measurements"]}'),
  ('xr.facial_bones', 'XR', 'Facial Bones X-Ray Pack', 'Facial radiograph — trauma.', 'Head & Neck', 'X-Ray Facial Bones', 'xr_face', 'FACE', 'Head & Neck', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Facial fracture -> orbital floor (teardrop, antral fluid)? zygoma? maxilla?"],"comparisonMeasurements":["Fracture healing"],"criticalFindings":["Orbital blow-out fracture","Displaced facial fracture"],"recommendations":["CT facial bones for suspected fracture","Maxillofacial correlation"],"notApplicableSections":["measurements"]}'),
  ('xr.nasal_bones', 'XR', 'Nasal Bones X-Ray Pack', 'Nasal bone radiograph — trauma.', 'Head & Neck', 'X-Ray Nasal Bones', 'xr_face', 'NASAL', 'Head & Neck', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Nasal fracture -> displacement? distinguish from nasomaxillary suture/groove?"],"comparisonMeasurements":["Fracture healing"],"criticalFindings":[],"recommendations":["Clinical correlation; ENT if displaced or septal haematoma suspected"],"notApplicableSections":["measurements"]}'),
  ('xr.mandible', 'XR', 'Mandible X-Ray Pack', 'Mandible / OPG — fracture.', 'Head & Neck', 'X-Ray Mandible', 'xr_face', 'MANDIBLE', 'Head & Neck', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Mandibular fracture -> site? condyle? often TWO fractures (ring bone)? displacement?"],"comparisonMeasurements":["Fracture healing"],"criticalFindings":["Displaced/condylar mandibular fracture"],"recommendations":["Look for a second fracture (ring bone)","CT / maxillofacial correlation"],"notApplicableSections":["measurements"]}'),
  ('xr.tm_joint', 'XR', 'TM Joint X-Ray Pack', 'Temporomandibular joint radiograph.', 'Head & Neck', 'X-Ray TM Joint', 'xr_face', 'TMJ', 'Head & Neck', '0.4.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["TMJ -> condylar excursion open vs closed? dislocation? degenerative change?"],"comparisonMeasurements":["Alignment"],"criticalFindings":["TMJ dislocation"],"recommendations":["MRI for internal derangement (disc)","Dental/maxillofacial correlation"],"notApplicableSections":["measurements"]}'),
  ('xr.paranasal_sinuses', 'XR', 'Paranasal Sinuses X-Ray Pack', 'PNS radiograph (OM/Waters view) — sinusitis.', 'Head & Neck', 'X-Ray Paranasal Sinuses', 'xr_pns', 'PNS', 'Head & Neck', '0.6.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Sinus -> mucosal thickening? air-fluid level? complete opacification? which sinuses?"],"comparisonMeasurements":["Mucosal thickening"],"criticalFindings":["Sinus air-fluid level (acute sinusitis)"],"recommendations":["CT PNS for chronic/complicated sinus disease and pre-FESS planning","ENT correlation"],"qualityRules":["Plain films underestimate ethmoid/sphenoid disease; CT is definitive"],"notApplicableSections":["measurements"]}'),
  ('xr.mastoid', 'XR', 'Mastoid X-Ray Pack', 'Mastoid radiograph — aeration.', 'Head & Neck', 'X-Ray Mastoid', 'xr_mastoid', 'MASTOID', 'Head & Neck', '0.4.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Mastoid -> air-cell clouding? loss of trabeculation (coalescent)?"],"comparisonMeasurements":[],"criticalFindings":["Coalescent mastoiditis"],"recommendations":["CT temporal bone for suspected mastoiditis/cholesteatoma","ENT correlation"],"notApplicableSections":["measurements"]}'),
  ('xr.soft_tissue_neck', 'XR', 'Soft Tissue Neck X-Ray Pack', 'Lateral neck — airway, adenoids, foreign body.', 'Head & Neck', 'X-Ray Soft Tissue Neck', 'xr_neck', 'NECK', 'Head & Neck', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Airway -> narrowing? epiglottis (thumb sign)? subglottic (steeple sign)?","Prevertebral -> soft-tissue widening (retropharyngeal abscess)?","Foreign body -> radio-opaque? level? airway vs oesophagus?"],"comparisonMeasurements":["Prevertebral soft tissue","Airway calibre"],"criticalFindings":["Airway foreign body","Acute epiglottitis (thumb sign)","Retropharyngeal abscess","Airway compromise"],"recommendations":["Urgent ENT / airway correlation for stridor or suspected epiglottitis","CT neck for abscess or radiolucent foreign body"],"qualityRules":["Assess prevertebral soft-tissue thickness and the airway on a true lateral in inspiration"],"references":["Thumb sign (epiglottitis)","Steeple sign (croup)"]}')
ON CONFLICT (pack_id) DO NOTHING;
