-- CARE CT Gold Standard — Knowledge Pack REGISTRY (28 CT studies).
--
-- Each row is a MANIFEST that names a CT study and declares its pack-level
-- clinical rules (companion follow-ups, copilot modules, previous-comparison
-- measurements, critical findings, recommendations, quality rules, references).
-- Live content (protocols / findings / history / measurements / impression
-- rules / knowledge) is authored into the existing tables in the sibling
-- seed_ct_gold_standard_content.sql / seed_ct_impression_rules_knowledge.sql
-- and assembled live by the loader — this file copies no reporting code.
--
-- Companion follow-ups are DATA (companionRules), not hardcoded React. Copilot
-- reuses the existing generic modules (comparison + measurement completeness) —
-- no CT Copilot V2; CT-specific advice comes from the deterministic impression
-- rules + structured questionsJson.
--
-- Idempotent: replaces the coarse CT placeholders from the Knowledge Pack
-- Engine seed, then inserts the full 28 as system packs (ON CONFLICT DO NOTHING
-- on re-run; system packs are guarded from the delete).

DELETE FROM knowledge_packs WHERE modality = 'CT' AND is_system = FALSE;

INSERT INTO knowledge_packs
  (pack_id, modality, name, description, category, study_type, builder_type, body_part, knowledge_category, version, author, status, is_system, manifest_json)
VALUES
  -- ── Neuro ──────────────────────────────────────────────────────────────────
  ('ct.brain_plain', 'CT', 'CT Brain Plain Pack', 'Non-contrast CT brain — trauma, stroke, headache, altered sensorium.', 'Neuro', 'CT Brain Plain', 'ct_brain', 'BRAIN', 'Brain', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Intracranial hemorrhage -> volume (ABC/2)? midline shift? intraventricular extension? hydrocephalus?","Infarct -> vascular territory? ASPECTS? hemorrhagic transformation?","Mass effect -> midline shift (mm)? effaced sulci/cisterns? herniation?"],"comparisonMeasurements":["Hemorrhage volume","Midline shift","Ventricle size","Mass size"],"criticalFindings":["Acute intracranial hemorrhage","Large territorial infarct","Mass effect","Midline shift","Herniation","Hydrocephalus","Diffuse axonal injury"],"recommendations":["Immediate neurosurgical referral if mass effect or herniation","Follow-up CT in 24-48h for evolving hemorrhage","MRI brain correlation for infarct extent / posterior fossa"],"qualityRules":["State bleed volume by ABC/2 for any parenchymal hemorrhage","Always state midline shift in mm","Comment on grey-white differentiation in suspected infarct"],"references":["ASPECTS scoring","Marshall/Rotterdam CT classification (TBI)"],"reportingNotes":"Non-contrast; window for blood, brain, and bone."}'),
  ('ct.brain_contrast', 'CT', 'CT Brain Contrast Pack', 'Contrast CT brain — mass, infection, metastasis.', 'Neuro', 'CT Brain Contrast', 'ct_brain', 'BRAIN', 'Brain', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Enhancing lesion -> number? size? pattern (ring/homogeneous)? edema? mass effect?"],"comparisonMeasurements":["Lesion size","Number of lesions","Midline shift"],"criticalFindings":["Mass effect","Midline shift","Herniation","Hydrocephalus"],"recommendations":["MRI with contrast for lesion characterization","Follow-up per oncology protocol"],"qualityRules":["State enhancement pattern and perilesional edema"],"references":["Contrast-enhanced CT brain protocol"]}'),
  ('ct.stroke', 'CT', 'CT Stroke Pack', 'Acute stroke CT (non-contrast + ASPECTS).', 'Neuro', 'CT Stroke', 'ct_stroke', 'BRAIN', 'Brain', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Infarct -> ASPECTS score? dense vessel sign? early ischemic change? hemorrhage excluded?"],"comparisonMeasurements":["Infarct size","ASPECTS"],"criticalFindings":["Acute infarct","Dense MCA sign","Hemorrhagic transformation","Large-vessel occlusion"],"recommendations":["Urgent stroke-team activation if within thrombolysis/thrombectomy window","CT angiography + perfusion if LVO suspected","MRI DWI correlation"],"qualityRules":["Report ASPECTS for anterior-circulation stroke","Explicitly exclude hemorrhage before thrombolysis"],"references":["ASPECTS","AHA/ASA acute stroke guidelines"]}'),
  ('ct.perfusion', 'CT', 'CT Perfusion Pack', 'CT perfusion — core/penumbra mismatch.', 'Neuro', 'CT Perfusion', 'ct_perfusion', 'BRAIN', 'Brain', '0.5.0', 'CARE Radiology', 'enabled', TRUE,
    '{"companionRules":["Perfusion -> core volume? penumbra? mismatch ratio?"],"comparisonMeasurements":["Core volume","Penumbra volume"],"criticalFindings":["Large ischemic core","Large penumbra (salvageable tissue)"],"recommendations":["Thrombectomy referral if favourable mismatch"],"references":["DEFUSE-3 / DAWN mismatch criteria"]}'),
  ('ct.angiography_brain', 'CT', 'CT Angiography Brain Pack', 'CTA circle of Willis — aneurysm, stenosis, occlusion.', 'Vascular', 'CT Angiography Brain', 'ct_angiography_brain', 'BRAIN', 'Brain', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Aneurysm -> location? neck? dome size? daughter sac?","Stenosis -> vessel? degree? occlusion?"],"comparisonMeasurements":["Aneurysm diameter","Stenosis degree"],"criticalFindings":["Intracranial aneurysm","Large-vessel occlusion","High-grade stenosis","Vascular dissection"],"recommendations":["Neurosurgical / neuro-interventional referral for aneurysm","DSA correlation as indicated"],"qualityRules":["State aneurysm neck and dome dimensions"],"references":["CTA circle of Willis protocol"]}'),
  ('ct.orbit', 'CT', 'CT Orbit Pack', 'CT orbit — trauma, proptosis, mass.', 'Head & Neck', 'CT Orbit', 'ct_orbit', 'ORBIT', 'Head & Neck', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"companionRules":["Orbital trauma -> wall fracture? entrapment? retrobulbar hematoma?"],"comparisonMeasurements":["Proptosis","Lesion size"],"criticalFindings":["Retrobulbar hemorrhage","Globe rupture","Orbital fracture with entrapment"],"recommendations":["Ophthalmology referral","MRI orbit for soft-tissue characterization"]}'),

  -- ── Head & Neck / ENT ──────────────────────────────────────────────────────
  ('ct.pns', 'CT', 'CT PNS Pack', 'CT paranasal sinuses — sinusitis, polyps, pre-FESS.', 'Head & Neck', 'CT PNS', 'ct_pns', 'PNS', 'Head & Neck', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"companionRules":["Sinus opacification -> which sinuses? mucosal thickening vs complete opacification? OMC patency? bony erosion?"],"comparisonMeasurements":["Mucosal thickening"],"criticalFindings":["Bony erosion / intracranial or orbital extension","Fungal sinusitis features","Mucocele with expansion"],"recommendations":["ENT referral for FESS planning","MRI if fungal or neoplastic disease suspected"],"qualityRules":["Comment on OMC patency and anatomical variants (concha bullosa, Haller cell, Onodi cell) before FESS"],"references":["Lund-Mackay staging"]}'),
  ('ct.temporal_bone', 'CT', 'CT Temporal Bone Pack', 'HRCT temporal bone — cholesteatoma, otosclerosis, trauma.', 'Head & Neck', 'CT Temporal Bone', 'ct_temporal_bone', 'TEMPORAL_BONE', 'Head & Neck', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"companionRules":["Middle-ear opacification -> ossicular erosion? scutum blunting? Prussak space? tegmen/labyrinthine fistula?"],"comparisonMeasurements":["Lesion size"],"criticalFindings":["Ossicular erosion","Labyrinthine / tegmen dehiscence","Facial-canal involvement"],"recommendations":["ENT / otology referral","MRI (non-echo-planar DWI) for cholesteatoma"],"references":["HRCT temporal bone protocol"]}'),
  ('ct.neck', 'CT', 'CT Neck Pack', 'Contrast CT neck — abscess, mass, nodes.', 'Head & Neck', 'CT Neck', 'ct_neck', 'NECK', 'Head & Neck', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"companionRules":["Neck collection -> space? rim enhancement? airway compromise?","Lymph node -> level? size (short axis)? necrosis?"],"comparisonMeasurements":["Lymph node size","Mass size"],"criticalFindings":["Deep-neck abscess with airway compromise","Descending mediastinitis"],"recommendations":["ENT / surgical referral","Correlate with histopathology for nodal disease"]}'),
  ('ct.facial_bones', 'CT', 'CT Facial Bones Pack', 'CT facial bones — maxillofacial trauma.', 'Head & Neck', 'CT Facial Bones', 'ct_facial_bones', 'FACE', 'Head & Neck', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"companionRules":["Facial fracture -> Le Fort level? ZMC? orbital floor? displacement?"],"comparisonMeasurements":["Fracture displacement"],"criticalFindings":["Le Fort fracture","Orbital blow-out with entrapment","Skull-base fracture"],"recommendations":["Maxillofacial / plastic surgery referral"]}'),
  ('ct.mandible', 'CT', 'CT Mandible Pack', 'CT mandible — fracture, lesion.', 'Head & Neck', 'CT Mandible', 'ct_mandible', 'MANDIBLE', 'Head & Neck', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"companionRules":["Mandible fracture -> site? displacement? condylar involvement?"],"comparisonMeasurements":["Fracture displacement"],"criticalFindings":["Displaced mandibular fracture","Condylar fracture-dislocation"],"recommendations":["Maxillofacial referral"]}'),
  ('ct.mastoid', 'CT', 'CT Mastoid Pack', 'CT mastoid — mastoiditis, cholesteatoma.', 'Head & Neck', 'CT Temporal Bone', 'ct_temporal_bone', 'TEMPORAL_BONE', 'Head & Neck', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"companionRules":["Mastoid opacification -> coalescent? bony erosion? sigmoid-sinus/dural involvement?"],"criticalFindings":["Coalescent mastoiditis","Sigmoid-sinus thrombosis","Intracranial extension"],"recommendations":["Urgent ENT referral","MRV if venous-sinus thrombosis suspected"]}'),
  ('ct.paranasal_sinuses', 'CT', 'CT Paranasal Sinuses Pack', 'Alias of CT PNS — shares CT PNS content.', 'Head & Neck', 'CT PNS', 'ct_pns', 'PNS', 'Head & Neck', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"companionRules":["Sinus opacification -> which sinuses? OMC patency? bony erosion?"],"criticalFindings":["Intracranial or orbital extension","Fungal sinusitis"],"recommendations":["ENT referral for FESS planning"],"references":["Lund-Mackay staging"]}'),

  -- ── Chest ──────────────────────────────────────────────────────────────────
  ('ct.chest_plain', 'CT', 'CT Chest Plain Pack', 'CT chest — nodule, mass, effusion, mediastinum.', 'Chest', 'CT Chest Plain', 'ct_chest', 'CHEST', 'Chest', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Pulmonary nodule -> size (mm)? solid/subsolid? margins? location? Fleischner category?","Pleural effusion -> side? volume? loculated? enhancement?","Mediastinal node -> station? short-axis size?"],"comparisonMeasurements":["Nodule size","Mass size","Pleural effusion","Lymph node size"],"criticalFindings":["Tension pneumothorax","Large pleural effusion","Central airway obstruction","Aortic aneurysm/dissection"],"recommendations":["Fleischner Society follow-up for incidental nodule","MDT / oncology referral for suspicious mass","Contrast CT for mediastinal characterization"],"qualityRules":["Report largest nodule size and Fleischner category","State effusion side and approximate volume"],"references":["Fleischner Society 2017 nodule guidelines","Lung-RADS"]}'),
  ('ct.hrct_chest', 'CT', 'HRCT Chest Pack', 'HRCT chest — interstitial lung disease.', 'Chest', 'HRCT Chest', 'ct_hrct', 'CHEST', 'Chest', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule"],"companionRules":["Interstitial pattern -> fibrosis? honeycombing? traction bronchiectasis? ground-glass? distribution (basal/peripheral)? UIP vs non-UIP?"],"comparisonMeasurements":["Extent of fibrosis","Ground-glass extent"],"criticalFindings":["Acute exacerbation of ILD","Extensive honeycombing","Superimposed infection"],"recommendations":["Pulmonology / ILD-MDT referral","Correlate with PFTs and serology","Follow-up HRCT to assess progression"],"qualityRules":["State whether the pattern is UIP, probable UIP, indeterminate, or alternative (per Fleischner/ATS)","Comment on honeycombing and traction bronchiectasis explicitly"],"references":["ATS/ERS/JRS/ALAT IPF guidelines","Fleischner Society ILD"]}'),
  ('ct.pulmonary_angiography', 'CT', 'CT Pulmonary Angiography Pack', 'CTPA — pulmonary embolism.', 'Vascular', 'CT Pulmonary Angiography', 'ct_pulmonary_angiography', 'CHEST', 'Chest', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["PE -> central/lobar/segmental? saddle? RV strain (RV:LV ratio)? clot burden?"],"comparisonMeasurements":["RV:LV ratio","Pulmonary artery diameter"],"criticalFindings":["Saddle / central pulmonary embolism","Right-heart strain (RV:LV > 1)","Pulmonary infarct"],"recommendations":["Urgent clinical correlation and anticoagulation per protocol","Echocardiography if RV strain","Consider thrombolysis for massive PE"],"qualityRules":["State most proximal level of embolus and RV:LV ratio","Report main pulmonary artery diameter (dilated if > 29 mm)"],"references":["PIOPED II","ESC pulmonary embolism guidelines"]}'),

  -- ── Abdomen & Pelvis ───────────────────────────────────────────────────────
  ('ct.abdomen_plain', 'CT', 'CT Abdomen Plain Pack', 'Non-contrast CT abdomen.', 'Body', 'CT Abdomen Plain', 'ct_abdomen', 'ABDOMEN', 'Abdomen', '0.7.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Calculus -> location? size? hydronephrosis?","Free air -> location? source?"],"comparisonMeasurements":["Stone size","Lesion size"],"criticalFindings":["Free intraperitoneal air","Bowel obstruction","Aortic aneurysm","Active hemorrhage"],"recommendations":["Contrast CT for further characterization","Surgical referral for acute abdomen"]}'),
  ('ct.cect_abdomen', 'CT', 'CECT Abdomen Pack', 'Contrast-enhanced CT abdomen — full triphasic where indicated.', 'Body', 'CECT Abdomen', 'ct_abdomen', 'ABDOMEN', 'Abdomen', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Liver lesion -> segment? size? enhancement pattern (arterial/portal/delayed)? washout? LI-RADS?","Appendicitis -> diameter (mm)? appendicolith? wall enhancement? periappendiceal collection?","Bowel obstruction -> transition point? closed loop? ischemia?","Pancreatitis -> necrosis? collection? CTSI?"],"comparisonMeasurements":["Liver lesion size","Lymph node size","Pancreatic lesion size","Renal lesion size"],"criticalFindings":["Bowel ischemia / closed-loop obstruction","Active contrast extravasation","Abscess / collection","Aortic dissection or aneurysm","Necrotizing pancreatitis","Portal / mesenteric venous thrombosis"],"recommendations":["Surgical referral for acute abdomen","MRI / MRCP for biliary or hepatic characterization","Follow-up per oncology protocol","Ultrasound correlation for gallbladder"],"qualityRules":["State enhancement phases available","Report LI-RADS category for at-risk liver lesions","State appendix diameter and appendicolith status when appendicitis is queried"],"references":["LI-RADS","CT severity index (pancreatitis)","Bosniak classification (renal cysts)"]}'),
  ('ct.kub', 'CT', 'CT KUB Pack', 'Non-contrast CT KUB — urolithiasis.', 'Body', 'CT KUB', 'ct_kub', 'ABDOMEN', 'Abdomen', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Calculus -> side? location (calyx/pelvis/ureter PUJ/mid/VUJ)? size (mm)? density (HU)?","Hydronephrosis -> side? grade (mild/moderate/gross)? hydroureter to level?","Obstruction -> perinephric/periureteric stranding? level?"],"comparisonMeasurements":["Stone size","Hydronephrosis grade"],"criticalFindings":["Obstructing calculus with hydronephrosis","Pyonephrosis / infected obstruction","Forniceal rupture"],"recommendations":["Urology referral for obstructing or large (> 6 mm) calculus","Emergency referral if infected obstruction (sepsis)","Follow-up KUB to confirm passage"],"qualityRules":["Report each calculus by side, level, size (mm) and density (HU)","Grade hydronephrosis and state hydroureter level","State perinephric stranding"],"references":["ACR appropriateness — acute flank pain"]}'),
  ('ct.urography', 'CT', 'CT Urography Pack', 'CT urography — hematuria, urothelial evaluation.', 'Body', 'CT Urography', 'ct_urography', 'ABDOMEN', 'Abdomen', '0.7.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Urothelial lesion -> site? size? enhancement? filling defect on excretory phase?"],"comparisonMeasurements":["Lesion size"],"criticalFindings":["Urothelial malignancy","Obstructing lesion"],"recommendations":["Urology referral / cystoscopy for filling defect","Follow-up per protocol"],"references":["CT urography split-bolus protocol"]}'),
  ('ct.pelvis', 'CT', 'CT Pelvis Pack', 'CT pelvis — pelvic pathology, trauma.', 'Body', 'CT Pelvis', 'ct_pelvis', 'PELVIS', 'Pelvis', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"companionRules":["Pelvic collection -> size? drainable?","Pelvic fracture -> stability? active bleed?"],"comparisonMeasurements":["Mass size","Lymph node size"],"criticalFindings":["Active pelvic hemorrhage","Unstable pelvic fracture"],"recommendations":["Surgical / gynae referral as indicated"]}'),
  ('ct.whole_abdomen', 'CT', 'CT Whole Abdomen Pack', 'CT whole abdomen — staging, sepsis source.', 'Body', 'CT Whole Abdomen', 'ct_abdomen', 'ABDOMEN', 'Abdomen', '0.7.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Collection -> site? size? drainable?","Mass -> organ? size? nodal/metastatic spread?"],"comparisonMeasurements":["Mass size","Lymph node size","Liver lesion size"],"criticalFindings":["Bowel perforation","Bowel ischemia","Aortic aneurysm/dissection","Active hemorrhage","Abscess"],"recommendations":["Surgical referral for acute abdomen","Oncology / MDT referral for staging"],"references":["RECIST 1.1 for oncologic follow-up"]}'),

  -- ── Spine ──────────────────────────────────────────────────────────────────
  ('ct.cervical_spine', 'CT', 'CT Cervical Spine Pack', 'CT cervical spine — trauma, degenerative.', 'Neuro', 'CT Cervical Spine', 'ct_cervical_spine', 'CERVICAL_SPINE', 'Spine', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Vertebral fracture -> level? type? body-height loss (%)? retropulsion? canal compromise? stability?","Listhesis -> level? grade?"],"comparisonMeasurements":["Vertebral body height","Canal diameter","Listhesis"],"criticalFindings":["Unstable cervical fracture","Spinal canal compromise","Cord compression","Facet dislocation","Atlanto-axial instability"],"recommendations":["Urgent spine-surgery / neurosurgery referral for unstable fracture","MRI for cord and ligamentous injury","Maintain spinal precautions until cleared"],"qualityRules":["State fracture stability (per AO/SLIC)","Report canal diameter and retropulsion"],"references":["AO Spine classification","SLIC score"]}'),
  ('ct.dorsal_spine', 'CT', 'CT Dorsal Spine Pack', 'CT dorsal (thoracic) spine — trauma, lesion.', 'Neuro', 'CT Dorsal Spine', 'ct_dorsal_spine', 'DORSAL_SPINE', 'Spine', '0.7.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Vertebral fracture -> level? body-height loss? retropulsion? stability?"],"comparisonMeasurements":["Vertebral body height","Canal diameter"],"criticalFindings":["Unstable thoracic fracture","Canal compromise","Cord compression"],"recommendations":["Spine-surgery referral for unstable fracture","MRI for cord injury"],"references":["AO Spine classification"]}'),
  ('ct.lumbar_spine', 'CT', 'CT Lumbar Spine Pack', 'CT lumbar spine — trauma, degenerative, post-op.', 'Neuro', 'CT Lumbar Spine', 'ct_lumbar_spine', 'LS_SPINE', 'Spine', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Vertebral fracture -> level? body-height loss? retropulsion? stability?","Canal stenosis -> level? AP canal diameter? grade?","Spondylolisthesis -> level? grade (Meyerding)? pars defect?"],"comparisonMeasurements":["Vertebral body height","Canal diameter","Listhesis"],"criticalFindings":["Unstable burst fracture","Cauda equina compression","Canal compromise"],"recommendations":["Spine-surgery referral for instability or cauda equina","MRI for disc, cord/cauda and marrow assessment"],"qualityRules":["Report AP canal diameter for stenosis","Grade spondylolisthesis (Meyerding)"],"references":["Meyerding grading","AO Spine classification"]}'),
  ('ct.whole_spine', 'CT', 'CT Whole Spine Pack', 'CT whole spine — polytrauma screening.', 'Neuro', 'CT Whole Spine', 'ct_whole_spine', 'WHOLE_SPINE', 'Spine', '0.5.0', 'CARE Radiology', 'placeholder', TRUE,
    '{"companionRules":["Multilevel injury -> each level? most unstable level?"],"comparisonMeasurements":["Vertebral body height"],"criticalFindings":["Unstable fracture at any level","Cord compression"],"recommendations":["Spine-surgery referral","MRI whole spine for cord/ligamentous injury"]}'),

  -- ── Trauma & Oncology ──────────────────────────────────────────────────────
  ('ct.trauma', 'CT', 'CT Trauma (Polytrauma) Pack', 'Whole-body / polytrauma CT.', 'Body', 'CT Trauma', 'ct_trauma', 'TRAUMA', 'Abdomen', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Solid-organ injury -> organ? AAST grade? active extravasation?","Hemoperitoneum -> volume? source?","Pneumothorax / hemothorax -> side? tension?"],"comparisonMeasurements":["Laceration size","Hematoma size"],"criticalFindings":["Active contrast extravasation","Tension pneumothorax","Aortic injury","High-grade solid-organ laceration","Unstable pelvic fracture","Bowel/mesenteric injury"],"recommendations":["Immediate trauma-surgery activation for active bleed / high-grade injury","Angioembolization referral where appropriate"],"qualityRules":["Grade solid-organ injuries by AAST","Explicitly state active extravasation"],"references":["AAST organ injury scale","ATLS"]}'),
  ('ct.oncology_followup', 'CT', 'CT Oncology Follow-up Pack', 'Oncologic response assessment (RECIST).', 'Body', 'CT Oncology Follow-up', 'ct_oncology_followup', 'ABDOMEN', 'Abdomen', '1.0.0', 'CARE Radiology', 'enabled', TRUE,
    '{"copilotModules":["copilotComparisonModule","copilotMeasurementModule"],"companionRules":["Target lesion -> which lesions? sum of longest diameters? change vs baseline/nadir?","New lesion -> site?"],"comparisonMeasurements":["Target lesion sum","Largest lesion size","Lymph node short axis"],"criticalFindings":["Cord compression from metastasis","Impending pathological fracture","Large-volume progression / visceral crisis"],"recommendations":["Report RECIST 1.1 category (CR/PR/SD/PD)","MDT / oncology correlation","Compare against baseline AND nadir"],"qualityRules":["Use the SAME target lesions and measurement technique as prior","State RECIST response category explicitly"],"references":["RECIST 1.1"]}')
ON CONFLICT (pack_id) DO NOTHING;
