// catalog.ts — the Universal Pathology Catalog: one canonical identity per
// laboratory analyte, with age/sex-aware reference intervals, critical (panic)
// values, LOINC codes and every legacy spelling registered as an alias, plus
// the common panels (CBC, LFT, KFT, Lipid, Thyroid…) that compose them.
//
// RULES OF THE FILE (mirrors lib/measurements/src/catalog.ts):
//   - `id` is immutable. Never rename; deprecate + `replacedBy` instead.
//   - Every spelling that exists in shipped templates/data MUST appear in
//     `aliases` (resolution is deterministic — no fuzzy matching).
//   - Reference intervals are conventional ADULT defaults unless an age band is
//     stated; a lab may override them per-instance in a future content pack.
//     Where an analyte is strongly age-dependent (Hb, Hct, WBC, ALP, bilirubin,
//     creatinine) explicit pediatric/neonatal bands are seeded so children are
//     never flagged against adult norms. Analytes without seeded pediatric
//     bands report "no reference interval" for out-of-band ages rather than a
//     wrong flag.
//   - Critical/panic values are widely-cited defaults; they escalate a result
//     regardless of which reference interval matched.
//
// Clinical values are conventional reference intervals as commonly reported by
// Indian diagnostic laboratories; they are decision-support defaults, not a
// substitute for a lab's validated, method-specific ranges.

import type { AnalyteDefinition, PanelDefinition } from "./contract";

export const PATHOLOGY_CATALOG_VERSION = "1.0.0";

const V1 = "1.0.0";

// 28 days / 1 year expressed in years, for neonatal/infant age bands.
const D28 = 28 / 365.25; // ≈ 0.0767

export const PATHOLOGY_ANALYTE_CATALOG: readonly AnalyteDefinition[] = [
  // ══ Hematology — Complete Blood Count ═════════════════════════════════════
  {
    id: "HEMOGLOBIN",
    canonicalKey: "analyte.hemoglobin",
    displayName: "Hemoglobin",
    shortName: "Hb",
    aliases: ["Haemoglobin", "Hb", "HGB", "Hgb", "Hemoglobin (Hb)", "Hb (Haemoglobin)", "Haemoglobin (Hb)"],
    loinc: "718-7",
    description: "Oxygen-carrying protein concentration in whole blood.",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL", "g/L"],
    precision: 1,
    referenceIntervals: [
      { sex: "any", ageMinYears: 0, ageMaxYears: D28, low: 14.0, high: 22.0, note: "Newborn (0–28 days)" },
      { sex: "any", ageMinYears: D28, ageMaxYears: 1, low: 10.0, high: 13.5, note: "Infant" },
      { sex: "any", ageMinYears: 1, ageMaxYears: 12, low: 11.0, high: 15.0, note: "Child" },
      { sex: "any", ageMinYears: 12, ageMaxYears: 15, low: 12.0, high: 16.0, note: "Adolescent" },
      { sex: "male", ageMinYears: 15, low: 13.0, high: 17.0, note: "Adult male" },
      { sex: "female", ageMinYears: 15, low: 12.0, high: 15.0, note: "Adult female (non-pregnant)" },
      { sex: "female", condition: "pregnancy", low: 11.0, high: 14.0, note: "Pregnancy (WHO anemia cutoff 11)" },
    ],
    criticalLow: 7.0,
    criticalHigh: 20.0,
    absurdLow: 2.0,
    absurdHigh: 30.0,
    higherIsWorse: false,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "HEMATOCRIT",
    canonicalKey: "analyte.hematocrit",
    displayName: "Hematocrit (PCV)",
    shortName: "PCV",
    aliases: ["Haematocrit", "PCV", "HCT", "Packed Cell Volume", "Hematocrit", "Hct", "PCV (Hematocrit)"],
    loinc: "4544-3",
    description: "Fraction of blood volume occupied by red cells.",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "%",
    allowedUnits: ["%"],
    precision: 1,
    referenceIntervals: [
      { sex: "any", ageMinYears: 1, ageMaxYears: 15, low: 33.0, high: 45.0, note: "Child" },
      { sex: "male", ageMinYears: 15, low: 40.0, high: 50.0, note: "Adult male" },
      { sex: "female", ageMinYears: 15, low: 36.0, high: 46.0, note: "Adult female" },
    ],
    criticalLow: 20.0,
    criticalHigh: 60.0,
    absurdLow: 10.0,
    absurdHigh: 75.0,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "RBC_COUNT",
    canonicalKey: "analyte.rbc_count",
    displayName: "RBC Count",
    shortName: "RBC",
    aliases: ["RBC", "Red Blood Cell Count", "Total RBC Count", "Erythrocyte Count", "RBC Count", "TRBC"],
    loinc: "789-8",
    description: "Number concentration of red blood cells.",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "10^6/µL",
    allowedUnits: ["10^6/µL", "10^12/L"],
    precision: 2,
    referenceIntervals: [
      { sex: "any", ageMinYears: 1, ageMaxYears: 15, low: 4.0, high: 5.2, note: "Child" },
      { sex: "male", ageMinYears: 15, low: 4.5, high: 5.9, note: "Adult male" },
      { sex: "female", ageMinYears: 15, low: 4.0, high: 5.2, note: "Adult female" },
    ],
    absurdLow: 0.5,
    absurdHigh: 12.0,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "WBC_COUNT",
    canonicalKey: "analyte.wbc_count",
    displayName: "WBC Count (TLC)",
    shortName: "WBC",
    aliases: ["WBC", "TLC", "Total Leukocyte Count", "Total WBC Count", "Leucocyte Count", "White Blood Cell Count", "TC", "WBC Count", "Total Leucocyte Count"],
    loinc: "6690-2",
    description: "Total white-blood-cell (leukocyte) concentration.",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "10^3/µL",
    allowedUnits: ["10^3/µL", "10^9/L", "/µL"],
    precision: 1,
    referenceIntervals: [
      { sex: "any", ageMinYears: 0, ageMaxYears: D28, low: 9.0, high: 30.0, note: "Newborn" },
      { sex: "any", ageMinYears: D28, ageMaxYears: 1, low: 6.0, high: 17.5, note: "Infant" },
      { sex: "any", ageMinYears: 1, ageMaxYears: 12, low: 5.0, high: 15.0, note: "Child" },
      { sex: "any", ageMinYears: 12, low: 4.0, high: 11.0, note: "Adult" },
    ],
    criticalLow: 2.0,
    criticalHigh: 50.0,
    absurdLow: 0.1,
    absurdHigh: 500.0,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "PLATELET_COUNT",
    canonicalKey: "analyte.platelet_count",
    displayName: "Platelet Count",
    shortName: "PLT",
    aliases: ["Platelets", "PLT", "Thrombocyte Count", "Platelet Count", "Platelet", "Total Platelet Count"],
    loinc: "777-3",
    description: "Platelet (thrombocyte) concentration.",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "10^3/µL",
    allowedUnits: ["10^3/µL", "10^9/L", "/µL"],
    precision: 0,
    referenceIntervals: [
      { sex: "any", low: 150, high: 410, note: "All ages" },
    ],
    criticalLow: 20,
    criticalHigh: 1000,
    absurdLow: 2,
    absurdHigh: 5000,
    higherIsWorse: false,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "MCV",
    canonicalKey: "analyte.mcv",
    displayName: "MCV",
    aliases: ["Mean Corpuscular Volume", "MCV", "Mean Cell Volume"],
    loinc: "787-2",
    description: "Mean corpuscular (red cell) volume.",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "fL",
    allowedUnits: ["fL"],
    precision: 1,
    referenceIntervals: [
      { sex: "any", ageMinYears: 1, ageMaxYears: 15, low: 75, high: 95, note: "Child" },
      { sex: "any", ageMinYears: 15, low: 80, high: 100, note: "Adult" },
    ],
    absurdLow: 40,
    absurdHigh: 160,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "MCH",
    canonicalKey: "analyte.mch",
    displayName: "MCH",
    aliases: ["Mean Corpuscular Hemoglobin", "MCH", "Mean Cell Hemoglobin"],
    loinc: "785-6",
    description: "Mean corpuscular hemoglobin (mass per red cell).",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "pg",
    allowedUnits: ["pg"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 27, high: 33, note: "All ages" }],
    absurdLow: 10,
    absurdHigh: 60,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "MCHC",
    canonicalKey: "analyte.mchc",
    displayName: "MCHC",
    aliases: ["Mean Corpuscular Hemoglobin Concentration", "MCHC", "Mean Cell Hemoglobin Concentration"],
    loinc: "786-4",
    description: "Mean corpuscular hemoglobin concentration.",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 32, high: 36, note: "All ages" }],
    absurdLow: 20,
    absurdHigh: 45,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "RDW",
    canonicalKey: "analyte.rdw",
    displayName: "RDW-CV",
    aliases: ["Red Cell Distribution Width", "RDW", "RDW-CV", "RDW CV"],
    loinc: "788-0",
    description: "Red-cell distribution width (anisocytosis index).",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "%",
    allowedUnits: ["%"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 11.5, high: 14.5, note: "All ages" }],
    absurdLow: 5,
    absurdHigh: 40,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "NEUTROPHILS_PCT",
    canonicalKey: "analyte.neutrophils_pct",
    displayName: "Neutrophils",
    shortName: "Neut",
    aliases: ["Neutrophils %", "Neutrophil", "Polymorphs", "Neutrophils (%)", "Segmented Neutrophils", "Neutrophil Percentage"],
    loinc: "770-8",
    description: "Neutrophils as a percentage of white cells (differential).",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "%",
    allowedUnits: ["%"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 40, high: 75, note: "Adult differential (pediatric differs)" }],
    absurdLow: 0,
    absurdHigh: 100,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "LYMPHOCYTES_PCT",
    canonicalKey: "analyte.lymphocytes_pct",
    displayName: "Lymphocytes",
    shortName: "Lymph",
    aliases: ["Lymphocytes %", "Lymphocyte", "Lymphocytes (%)", "Lymphocyte Percentage"],
    loinc: "736-9",
    description: "Lymphocytes as a percentage of white cells (differential).",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "%",
    allowedUnits: ["%"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 20, high: 45, note: "Adult differential (infants lymphocyte-predominant)" }],
    absurdLow: 0,
    absurdHigh: 100,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "MONOCYTES_PCT",
    canonicalKey: "analyte.monocytes_pct",
    displayName: "Monocytes",
    shortName: "Mono",
    aliases: ["Monocytes %", "Monocyte", "Monocytes (%)"],
    loinc: "5905-5",
    description: "Monocytes as a percentage of white cells (differential).",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "%",
    allowedUnits: ["%"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 2, high: 10 }],
    absurdLow: 0,
    absurdHigh: 100,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "EOSINOPHILS_PCT",
    canonicalKey: "analyte.eosinophils_pct",
    displayName: "Eosinophils",
    shortName: "Eos",
    aliases: ["Eosinophils %", "Eosinophil", "Eosinophils (%)"],
    loinc: "713-8",
    description: "Eosinophils as a percentage of white cells (differential).",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "%",
    allowedUnits: ["%"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 1, high: 6 }],
    absurdLow: 0,
    absurdHigh: 100,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "BASOPHILS_PCT",
    canonicalKey: "analyte.basophils_pct",
    displayName: "Basophils",
    shortName: "Baso",
    aliases: ["Basophils %", "Basophil", "Basophils (%)"],
    loinc: "706-2",
    description: "Basophils as a percentage of white cells (differential).",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "%",
    allowedUnits: ["%"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 0, high: 2 }],
    absurdLow: 0,
    absurdHigh: 100,
    refs: { panels: ["CBC"] },
    version: V1,
  },
  {
    id: "ESR",
    canonicalKey: "analyte.esr",
    displayName: "ESR",
    aliases: ["Erythrocyte Sedimentation Rate", "ESR", "Sed Rate", "ESR (Westergren)", "E.S.R."],
    loinc: "4537-7",
    description: "Erythrocyte sedimentation rate (Westergren).",
    department: "Hematology",
    resultType: "numeric",
    defaultUnit: "mm/hr",
    allowedUnits: ["mm/hr"],
    precision: 0,
    referenceIntervals: [
      { sex: "male", low: 0, high: 15, note: "Adult male (rises with age)" },
      { sex: "female", low: 0, high: 20, note: "Adult female (rises with age)" },
    ],
    absurdLow: 0,
    absurdHigh: 200,
    higherIsWorse: true,
    refs: {},
    version: V1,
  },

  // ══ Biochemistry — Diabetes ═══════════════════════════════════════════════
  {
    id: "GLUCOSE_FASTING",
    canonicalKey: "analyte.glucose_fasting",
    displayName: "Glucose, Fasting",
    shortName: "FBS",
    aliases: ["Fasting Blood Sugar", "FBS", "Fasting Glucose", "Blood Sugar Fasting", "Glucose Fasting", "Sugar Fasting", "FBG"],
    loinc: "1558-6",
    description: "Plasma glucose after an overnight fast.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "any", low: 70, high: 100, note: "Normal fasting; 100–125 pre-diabetes; ≥126 diabetes", source: "ADA" },
    ],
    criticalLow: 40,
    criticalHigh: 450,
    absurdLow: 5,
    absurdHigh: 1500,
    higherIsWorse: true,
    refs: { panels: ["DIABETIC_PROFILE"] },
    version: V1,
  },
  {
    id: "GLUCOSE_PP",
    canonicalKey: "analyte.glucose_pp",
    displayName: "Glucose, Post-Prandial",
    shortName: "PPBS",
    aliases: ["Post Prandial Blood Sugar", "PPBS", "PP Glucose", "Blood Sugar PP", "Glucose 2hr PP", "Post-Prandial Glucose", "2 Hour PP", "PLBS"],
    loinc: "1521-4",
    description: "Plasma glucose two hours after a meal.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "any", high: 140, text: "< 140 mg/dL (2-hr); 140–199 pre-diabetes; ≥ 200 diabetes", note: "2-hour post-prandial", source: "ADA" },
    ],
    criticalLow: 40,
    criticalHigh: 450,
    absurdLow: 5,
    absurdHigh: 1500,
    higherIsWorse: true,
    refs: { panels: ["DIABETIC_PROFILE"] },
    version: V1,
  },
  {
    id: "GLUCOSE_RANDOM",
    canonicalKey: "analyte.glucose_random",
    displayName: "Glucose, Random",
    shortName: "RBS",
    aliases: ["Random Blood Sugar", "RBS", "Random Glucose", "Blood Sugar Random", "Glucose Random", "RBG"],
    loinc: "2345-7",
    description: "Plasma glucose at a random time.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 70, high: 140 }],
    criticalLow: 40,
    criticalHigh: 450,
    absurdLow: 5,
    absurdHigh: 1500,
    higherIsWorse: true,
    refs: {},
    version: V1,
  },
  {
    id: "HBA1C",
    canonicalKey: "analyte.hba1c",
    displayName: "HbA1c",
    aliases: ["Glycated Hemoglobin", "Glycosylated Hemoglobin", "HbA1c", "A1c", "Hb A1c", "Glycohemoglobin", "HBA1C"],
    loinc: "4548-4",
    description: "Glycated hemoglobin — 3-month average glycemia.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "%",
    allowedUnits: ["%"],
    precision: 1,
    referenceIntervals: [
      { sex: "any", high: 5.7, text: "< 5.7% non-diabetic; 5.7–6.4% pre-diabetes; ≥ 6.5% diabetes", source: "ADA" },
    ],
    absurdLow: 2,
    absurdHigh: 20,
    higherIsWorse: true,
    refs: { panels: ["DIABETIC_PROFILE"] },
    version: V1,
  },

  // ══ Biochemistry — Renal / Electrolytes ═══════════════════════════════════
  {
    id: "UREA",
    canonicalKey: "analyte.urea",
    displayName: "Urea",
    aliases: ["Blood Urea", "Serum Urea", "Urea", "B. Urea"],
    loinc: "22664-7",
    description: "Serum urea concentration.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 15, high: 40 }],
    criticalHigh: 200,
    absurdLow: 2,
    absurdHigh: 500,
    higherIsWorse: true,
    refs: { panels: ["KFT"] },
    version: V1,
  },
  {
    id: "BUN",
    canonicalKey: "analyte.bun",
    displayName: "Blood Urea Nitrogen",
    shortName: "BUN",
    aliases: ["BUN", "Urea Nitrogen", "Blood Urea Nitrogen"],
    loinc: "3094-0",
    description: "Blood urea nitrogen (urea ÷ 2.14).",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 7, high: 20 }],
    criticalHigh: 100,
    absurdLow: 1,
    absurdHigh: 300,
    higherIsWorse: true,
    refs: { panels: ["KFT"] },
    version: V1,
  },
  {
    id: "CREATININE",
    canonicalKey: "analyte.creatinine",
    displayName: "Creatinine",
    shortName: "Creat",
    aliases: ["Serum Creatinine", "Creatinine", "S. Creatinine", "Creat", "Sr. Creatinine"],
    loinc: "2160-0",
    description: "Serum creatinine — renal filtration marker.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "µmol/L"],
    precision: 2,
    referenceIntervals: [
      { sex: "any", ageMinYears: 0, ageMaxYears: 15, low: 0.3, high: 0.7, note: "Child" },
      { sex: "male", ageMinYears: 15, low: 0.7, high: 1.3, note: "Adult male" },
      { sex: "female", ageMinYears: 15, low: 0.6, high: 1.1, note: "Adult female" },
    ],
    criticalHigh: 7.4,
    absurdLow: 0.1,
    absurdHigh: 25,
    higherIsWorse: true,
    refs: { panels: ["KFT"] },
    version: V1,
  },
  {
    id: "URIC_ACID",
    canonicalKey: "analyte.uric_acid",
    displayName: "Uric Acid",
    aliases: ["Serum Uric Acid", "Uric Acid", "S. Uric Acid", "Urate"],
    loinc: "3084-1",
    description: "Serum uric acid concentration.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL"],
    precision: 1,
    referenceIntervals: [
      { sex: "any", ageMinYears: 1, ageMaxYears: 15, low: 2.0, high: 5.5, note: "Child" },
      { sex: "male", ageMinYears: 15, low: 3.5, high: 7.2, note: "Adult male" },
      { sex: "female", ageMinYears: 15, low: 2.6, high: 6.0, note: "Adult female" },
    ],
    absurdLow: 0.5,
    absurdHigh: 25,
    higherIsWorse: true,
    refs: { panels: ["KFT"] },
    version: V1,
  },
  {
    id: "SODIUM",
    canonicalKey: "analyte.sodium",
    displayName: "Sodium",
    shortName: "Na",
    aliases: ["Serum Sodium", "Sodium", "Na", "Na+", "S. Sodium"],
    loinc: "2951-2",
    description: "Serum sodium concentration.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 135, high: 145 }],
    criticalLow: 120,
    criticalHigh: 160,
    absurdLow: 80,
    absurdHigh: 200,
    refs: { panels: ["KFT", "ELECTROLYTES"] },
    version: V1,
  },
  {
    id: "POTASSIUM",
    canonicalKey: "analyte.potassium",
    displayName: "Potassium",
    shortName: "K",
    aliases: ["Serum Potassium", "Potassium", "K", "K+", "S. Potassium"],
    loinc: "2823-3",
    description: "Serum potassium concentration.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 3.5, high: 5.1 }],
    criticalLow: 2.5,
    criticalHigh: 6.5,
    absurdLow: 1.0,
    absurdHigh: 12.0,
    refs: { panels: ["KFT", "ELECTROLYTES"] },
    version: V1,
  },
  {
    id: "CHLORIDE",
    canonicalKey: "analyte.chloride",
    displayName: "Chloride",
    shortName: "Cl",
    aliases: ["Serum Chloride", "Chloride", "Cl", "Cl-", "S. Chloride"],
    loinc: "2075-0",
    description: "Serum chloride concentration.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 98, high: 107 }],
    criticalLow: 80,
    criticalHigh: 120,
    absurdLow: 50,
    absurdHigh: 200,
    refs: { panels: ["KFT", "ELECTROLYTES"] },
    version: V1,
  },
  {
    id: "BICARBONATE",
    canonicalKey: "analyte.bicarbonate",
    displayName: "Bicarbonate",
    shortName: "HCO3",
    aliases: ["Serum Bicarbonate", "Bicarbonate", "HCO3", "CO2", "Total CO2"],
    loinc: "1963-8",
    description: "Serum bicarbonate (total CO2).",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mmol/L",
    allowedUnits: ["mmol/L", "mEq/L"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 22, high: 29 }],
    criticalLow: 10,
    criticalHigh: 40,
    absurdLow: 3,
    absurdHigh: 60,
    refs: { panels: ["ELECTROLYTES"] },
    version: V1,
  },
  {
    id: "CALCIUM",
    canonicalKey: "analyte.calcium",
    displayName: "Calcium, Total",
    shortName: "Ca",
    aliases: ["Serum Calcium", "Calcium", "Total Calcium", "Ca", "S. Calcium"],
    loinc: "17861-6",
    description: "Serum total calcium.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 8.6, high: 10.2 }],
    criticalLow: 6.0,
    criticalHigh: 13.0,
    absurdLow: 3.0,
    absurdHigh: 20.0,
    refs: { panels: ["KFT"] },
    version: V1,
  },
  {
    id: "PHOSPHORUS",
    canonicalKey: "analyte.phosphorus",
    displayName: "Phosphorus",
    shortName: "PO4",
    aliases: ["Serum Phosphorus", "Phosphorus", "Phosphate", "Inorganic Phosphorus", "PO4"],
    loinc: "2777-1",
    description: "Serum inorganic phosphorus.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL"],
    precision: 1,
    referenceIntervals: [
      { sex: "any", ageMinYears: 0, ageMaxYears: 15, low: 4.0, high: 7.0, note: "Child (higher, bone growth)" },
      { sex: "any", ageMinYears: 15, low: 2.5, high: 4.5, note: "Adult" },
    ],
    absurdLow: 0.5,
    absurdHigh: 20,
    refs: { panels: ["KFT"] },
    version: V1,
  },
  {
    id: "MAGNESIUM",
    canonicalKey: "analyte.magnesium",
    displayName: "Magnesium",
    shortName: "Mg",
    aliases: ["Serum Magnesium", "Magnesium", "Mg", "S. Magnesium"],
    loinc: "19123-9",
    description: "Serum magnesium.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 1.7, high: 2.2 }],
    criticalLow: 1.0,
    criticalHigh: 5.0,
    absurdLow: 0.2,
    absurdHigh: 15,
    refs: {},
    version: V1,
  },

  // ══ Biochemistry — Liver ══════════════════════════════════════════════════
  {
    id: "BILIRUBIN_TOTAL",
    canonicalKey: "analyte.bilirubin_total",
    displayName: "Bilirubin, Total",
    shortName: "T.Bil",
    aliases: ["Total Bilirubin", "Bilirubin Total", "Serum Bilirubin Total", "T. Bilirubin", "Bilirubin (Total)"],
    loinc: "1975-2",
    description: "Total serum bilirubin.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "µmol/L"],
    precision: 1,
    referenceIntervals: [
      { sex: "any", ageMinYears: 0, ageMaxYears: D28, low: 0.2, high: 12.0, note: "Neonate — interpret against an hour-specific nomogram" },
      { sex: "any", ageMinYears: D28, low: 0.2, high: 1.2, note: "Beyond neonatal period" },
    ],
    criticalHigh: 15.0,
    absurdLow: 0.0,
    absurdHigh: 60.0,
    higherIsWorse: true,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "BILIRUBIN_DIRECT",
    canonicalKey: "analyte.bilirubin_direct",
    displayName: "Bilirubin, Direct",
    shortName: "D.Bil",
    aliases: ["Direct Bilirubin", "Conjugated Bilirubin", "Bilirubin Direct", "D. Bilirubin", "Bilirubin (Direct)"],
    loinc: "1968-7",
    description: "Direct (conjugated) serum bilirubin.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "µmol/L"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 0.0, high: 0.3 }],
    absurdLow: 0.0,
    absurdHigh: 40.0,
    higherIsWorse: true,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "BILIRUBIN_INDIRECT",
    canonicalKey: "analyte.bilirubin_indirect",
    displayName: "Bilirubin, Indirect",
    shortName: "I.Bil",
    aliases: ["Indirect Bilirubin", "Unconjugated Bilirubin", "Bilirubin Indirect", "I. Bilirubin", "Bilirubin (Indirect)"],
    loinc: "1971-1",
    description: "Indirect (unconjugated) serum bilirubin.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "µmol/L"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 0.0, high: 1.0 }],
    absurdLow: 0.0,
    absurdHigh: 50.0,
    higherIsWorse: true,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "SGPT_ALT",
    canonicalKey: "analyte.sgpt_alt",
    displayName: "SGPT (ALT)",
    shortName: "ALT",
    aliases: ["SGPT", "ALT", "Alanine Aminotransferase", "SGPT (ALT)", "ALT (SGPT)", "Alanine Transaminase", "S.G.P.T."],
    loinc: "1742-6",
    description: "Alanine aminotransferase — hepatocellular enzyme.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "U/L",
    allowedUnits: ["U/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "male", low: 0, high: 41, note: "Adult male" },
      { sex: "female", low: 0, high: 33, note: "Adult female" },
    ],
    criticalHigh: 1000,
    absurdLow: 0,
    absurdHigh: 20000,
    higherIsWorse: true,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "SGOT_AST",
    canonicalKey: "analyte.sgot_ast",
    displayName: "SGOT (AST)",
    shortName: "AST",
    aliases: ["SGOT", "AST", "Aspartate Aminotransferase", "SGOT (AST)", "AST (SGOT)", "Aspartate Transaminase", "S.G.O.T."],
    loinc: "1920-8",
    description: "Aspartate aminotransferase — hepatocellular/cardiac enzyme.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "U/L",
    allowedUnits: ["U/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "male", low: 0, high: 40, note: "Adult male" },
      { sex: "female", low: 0, high: 32, note: "Adult female" },
    ],
    criticalHigh: 1000,
    absurdLow: 0,
    absurdHigh: 20000,
    higherIsWorse: true,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "ALP",
    canonicalKey: "analyte.alp",
    displayName: "Alkaline Phosphatase",
    shortName: "ALP",
    aliases: ["ALP", "Alkaline Phosphatase", "SAP", "Serum Alkaline Phosphatase", "Alk Phos", "ALKP"],
    loinc: "6768-6",
    description: "Alkaline phosphatase — hepatobiliary/bone enzyme.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "U/L",
    allowedUnits: ["U/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "any", ageMinYears: 0, ageMaxYears: 1, low: 80, high: 470, note: "Infant (bone growth)" },
      { sex: "any", ageMinYears: 1, ageMaxYears: 15, low: 100, high: 390, note: "Child/adolescent (bone growth)" },
      { sex: "any", ageMinYears: 15, low: 40, high: 129, note: "Adult" },
    ],
    absurdLow: 5,
    absurdHigh: 5000,
    higherIsWorse: true,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "GGT",
    canonicalKey: "analyte.ggt",
    displayName: "Gamma GT (GGT)",
    shortName: "GGT",
    aliases: ["GGT", "Gamma GT", "Gamma Glutamyl Transferase", "GGTP", "γ-GT", "Gamma-Glutamyl Transpeptidase"],
    loinc: "2324-2",
    description: "Gamma-glutamyl transferase — cholestatic/alcohol marker.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "U/L",
    allowedUnits: ["U/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "male", low: 8, high: 61, note: "Adult male" },
      { sex: "female", low: 5, high: 36, note: "Adult female" },
    ],
    absurdLow: 0,
    absurdHigh: 5000,
    higherIsWorse: true,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "PROTEIN_TOTAL",
    canonicalKey: "analyte.protein_total",
    displayName: "Protein, Total",
    shortName: "T.Prot",
    aliases: ["Total Protein", "Serum Total Protein", "Protein Total", "T. Protein", "Total Proteins"],
    loinc: "2885-2",
    description: "Total serum protein.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL", "g/L"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 6.4, high: 8.3 }],
    absurdLow: 1.0,
    absurdHigh: 15.0,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "ALBUMIN",
    canonicalKey: "analyte.albumin",
    displayName: "Albumin",
    shortName: "Alb",
    aliases: ["Serum Albumin", "Albumin", "S. Albumin", "Alb"],
    loinc: "1751-7",
    description: "Serum albumin.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL", "g/L"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 3.5, high: 5.2 }],
    criticalLow: 1.5,
    absurdLow: 0.5,
    absurdHigh: 8.0,
    higherIsWorse: false,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "GLOBULIN",
    canonicalKey: "analyte.globulin",
    displayName: "Globulin",
    shortName: "Glob",
    aliases: ["Serum Globulin", "Globulin", "Total Globulin", "Glob"],
    loinc: "10834-0",
    description: "Serum globulin (total protein − albumin).",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "g/dL",
    allowedUnits: ["g/dL", "g/L"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 2.0, high: 3.5 }],
    absurdLow: 0.5,
    absurdHigh: 10.0,
    refs: { panels: ["LFT"] },
    version: V1,
  },
  {
    id: "AG_RATIO",
    canonicalKey: "analyte.ag_ratio",
    displayName: "A:G Ratio",
    aliases: ["Albumin Globulin Ratio", "A/G Ratio", "AG Ratio", "A:G Ratio", "Albumin/Globulin Ratio"],
    description: "Albumin-to-globulin ratio.",
    department: "Biochemistry",
    resultType: "ratio",
    defaultUnit: "ratio",
    allowedUnits: ["ratio"],
    precision: 2,
    referenceIntervals: [{ sex: "any", low: 1.0, high: 2.5 }],
    absurdLow: 0.1,
    absurdHigh: 10,
    refs: { panels: ["LFT"] },
    version: V1,
  },

  // ══ Biochemistry — Lipid Profile ══════════════════════════════════════════
  {
    id: "CHOLESTEROL_TOTAL",
    canonicalKey: "analyte.cholesterol_total",
    displayName: "Cholesterol, Total",
    shortName: "T.Chol",
    aliases: ["Total Cholesterol", "Cholesterol", "Serum Cholesterol", "Cholesterol Total", "T. Cholesterol"],
    loinc: "2093-3",
    description: "Total serum cholesterol.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "any", high: 200, text: "Desirable < 200; Borderline 200–239; High ≥ 240", source: "NCEP ATP III" },
    ],
    absurdLow: 20,
    absurdHigh: 1000,
    higherIsWorse: true,
    refs: { panels: ["LIPID_PROFILE"] },
    version: V1,
  },
  {
    id: "TRIGLYCERIDES",
    canonicalKey: "analyte.triglycerides",
    displayName: "Triglycerides",
    shortName: "TG",
    aliases: ["Triglyceride", "TG", "Serum Triglycerides", "TGL", "Trigly"],
    loinc: "2571-8",
    description: "Serum triglycerides.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "any", high: 150, text: "Normal < 150; Borderline 150–199; High 200–499; Very high ≥ 500", source: "NCEP ATP III" },
    ],
    absurdLow: 10,
    absurdHigh: 10000,
    higherIsWorse: true,
    refs: { panels: ["LIPID_PROFILE"] },
    version: V1,
  },
  {
    id: "HDL_CHOLESTEROL",
    canonicalKey: "analyte.hdl_cholesterol",
    displayName: "HDL Cholesterol",
    shortName: "HDL",
    aliases: ["HDL", "HDL-C", "HDL Cholesterol", "High Density Lipoprotein", "Good Cholesterol"],
    loinc: "2085-9",
    description: "High-density lipoprotein cholesterol (protective).",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "male", low: 40, text: "Low < 40; protective ≥ 60", note: "Adult male", source: "NCEP ATP III" },
      { sex: "female", low: 50, text: "Low < 50; protective ≥ 60", note: "Adult female", source: "NCEP ATP III" },
    ],
    absurdLow: 5,
    absurdHigh: 200,
    higherIsWorse: false,
    refs: { panels: ["LIPID_PROFILE"] },
    version: V1,
  },
  {
    id: "LDL_CHOLESTEROL",
    canonicalKey: "analyte.ldl_cholesterol",
    displayName: "LDL Cholesterol",
    shortName: "LDL",
    aliases: ["LDL", "LDL-C", "LDL Cholesterol", "Low Density Lipoprotein", "Bad Cholesterol"],
    loinc: "13457-7",
    description: "Low-density lipoprotein cholesterol.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL", "mmol/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "any", high: 100, text: "Optimal < 100; Near-optimal 100–129; Borderline 130–159; High 160–189; Very high ≥ 190", source: "NCEP ATP III" },
    ],
    absurdLow: 5,
    absurdHigh: 700,
    higherIsWorse: true,
    refs: { panels: ["LIPID_PROFILE"] },
    version: V1,
  },
  {
    id: "VLDL_CHOLESTEROL",
    canonicalKey: "analyte.vldl_cholesterol",
    displayName: "VLDL Cholesterol",
    shortName: "VLDL",
    aliases: ["VLDL", "VLDL-C", "VLDL Cholesterol", "Very Low Density Lipoprotein"],
    loinc: "13458-5",
    description: "Very-low-density lipoprotein cholesterol.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "mg/dL",
    allowedUnits: ["mg/dL"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 5, high: 40 }],
    absurdLow: 0,
    absurdHigh: 500,
    higherIsWorse: true,
    refs: { panels: ["LIPID_PROFILE"] },
    version: V1,
  },

  // ══ Endocrinology — Thyroid ═══════════════════════════════════════════════
  {
    id: "TSH",
    canonicalKey: "analyte.tsh",
    displayName: "TSH",
    aliases: ["Thyroid Stimulating Hormone", "TSH", "S. TSH", "Thyrotropin", "TSH (Ultrasensitive)", "TSH 3rd Generation"],
    loinc: "3016-3",
    description: "Thyroid-stimulating hormone.",
    department: "Endocrinology",
    resultType: "numeric",
    defaultUnit: "µIU/mL",
    allowedUnits: ["µIU/mL", "mIU/L"],
    precision: 2,
    referenceIntervals: [
      { sex: "any", low: 0.4, high: 4.0, note: "Non-pregnant adult" },
      { sex: "female", condition: "pregnancy-t1", low: 0.1, high: 2.5, note: "Pregnancy 1st trimester" },
      { sex: "female", condition: "pregnancy-t2", low: 0.2, high: 3.0, note: "Pregnancy 2nd trimester" },
      { sex: "female", condition: "pregnancy-t3", low: 0.3, high: 3.0, note: "Pregnancy 3rd trimester" },
    ],
    absurdLow: 0.001,
    absurdHigh: 200,
    refs: { panels: ["THYROID_PROFILE", "FREE_THYROID_PROFILE"] },
    version: V1,
  },
  {
    id: "T3_TOTAL",
    canonicalKey: "analyte.t3_total",
    displayName: "T3, Total",
    shortName: "T3",
    aliases: ["Total T3", "T3", "Triiodothyronine", "T3 Total", "Total Triiodothyronine"],
    loinc: "3053-6",
    description: "Total triiodothyronine.",
    department: "Endocrinology",
    resultType: "numeric",
    defaultUnit: "ng/dL",
    allowedUnits: ["ng/dL"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 80, high: 200 }],
    absurdLow: 5,
    absurdHigh: 1000,
    refs: { panels: ["THYROID_PROFILE"] },
    version: V1,
  },
  {
    id: "T4_TOTAL",
    canonicalKey: "analyte.t4_total",
    displayName: "T4, Total",
    shortName: "T4",
    aliases: ["Total T4", "T4", "Thyroxine", "T4 Total", "Total Thyroxine"],
    loinc: "3026-2",
    description: "Total thyroxine.",
    department: "Endocrinology",
    resultType: "numeric",
    defaultUnit: "µg/dL",
    allowedUnits: ["µg/dL"],
    precision: 1,
    referenceIntervals: [{ sex: "any", low: 5.0, high: 12.0 }],
    absurdLow: 0.5,
    absurdHigh: 40,
    refs: { panels: ["THYROID_PROFILE"] },
    version: V1,
  },
  {
    id: "FT3",
    canonicalKey: "analyte.ft3",
    displayName: "Free T3",
    shortName: "FT3",
    aliases: ["Free T3", "FT3", "Free Triiodothyronine", "T3 Free"],
    loinc: "3051-0",
    description: "Free triiodothyronine.",
    department: "Endocrinology",
    resultType: "numeric",
    defaultUnit: "pg/mL",
    allowedUnits: ["pg/mL"],
    precision: 2,
    referenceIntervals: [{ sex: "any", low: 2.3, high: 4.2 }],
    absurdLow: 0.1,
    absurdHigh: 50,
    refs: { panels: ["FREE_THYROID_PROFILE"] },
    version: V1,
  },
  {
    id: "FT4",
    canonicalKey: "analyte.ft4",
    displayName: "Free T4",
    shortName: "FT4",
    aliases: ["Free T4", "FT4", "Free Thyroxine", "T4 Free"],
    loinc: "3024-7",
    description: "Free thyroxine.",
    department: "Endocrinology",
    resultType: "numeric",
    defaultUnit: "ng/dL",
    allowedUnits: ["ng/dL"],
    precision: 2,
    referenceIntervals: [{ sex: "any", low: 0.8, high: 1.8 }],
    absurdLow: 0.05,
    absurdHigh: 12,
    refs: { panels: ["FREE_THYROID_PROFILE"] },
    version: V1,
  },

  // ══ Biochemistry — Cardiac / Pancreatic / Nutritional ═════════════════════
  {
    id: "CRP",
    canonicalKey: "analyte.crp",
    displayName: "C-Reactive Protein",
    shortName: "CRP",
    aliases: ["CRP", "C Reactive Protein", "C-Reactive Protein", "CRP Quantitative"],
    loinc: "1988-5",
    description: "C-reactive protein — acute-phase inflammation marker.",
    department: "Immunology",
    resultType: "numeric",
    defaultUnit: "mg/L",
    allowedUnits: ["mg/L", "mg/dL"],
    precision: 1,
    referenceIntervals: [{ sex: "any", high: 5, text: "< 5 mg/L" }],
    absurdLow: 0,
    absurdHigh: 1000,
    higherIsWorse: true,
    refs: {},
    version: V1,
  },
  {
    id: "AMYLASE",
    canonicalKey: "analyte.amylase",
    displayName: "Amylase",
    aliases: ["Serum Amylase", "Amylase", "S. Amylase"],
    loinc: "1798-8",
    description: "Serum amylase — pancreatic enzyme.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "U/L",
    allowedUnits: ["U/L"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 28, high: 100 }],
    absurdLow: 0,
    absurdHigh: 10000,
    higherIsWorse: true,
    refs: {},
    version: V1,
  },
  {
    id: "LIPASE",
    canonicalKey: "analyte.lipase",
    displayName: "Lipase",
    aliases: ["Serum Lipase", "Lipase", "S. Lipase"],
    loinc: "3040-3",
    description: "Serum lipase — pancreatic enzyme.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "U/L",
    allowedUnits: ["U/L"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 13, high: 60 }],
    absurdLow: 0,
    absurdHigh: 10000,
    higherIsWorse: true,
    refs: {},
    version: V1,
  },
  {
    id: "LDH",
    canonicalKey: "analyte.ldh",
    displayName: "LDH",
    aliases: ["Lactate Dehydrogenase", "LDH", "Serum LDH", "LD"],
    loinc: "2532-0",
    description: "Lactate dehydrogenase — tissue turnover marker.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "U/L",
    allowedUnits: ["U/L"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 140, high: 280 }],
    absurdLow: 20,
    absurdHigh: 20000,
    higherIsWorse: true,
    refs: {},
    version: V1,
  },
  {
    id: "CPK",
    canonicalKey: "analyte.cpk",
    displayName: "CPK (Total)",
    shortName: "CK",
    aliases: ["Creatine Phosphokinase", "CPK", "CK", "Creatine Kinase", "CPK Total", "CK Total"],
    loinc: "2157-6",
    description: "Creatine kinase — muscle/cardiac enzyme.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "U/L",
    allowedUnits: ["U/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "male", low: 39, high: 308, note: "Adult male" },
      { sex: "female", low: 26, high: 192, note: "Adult female" },
    ],
    absurdLow: 0,
    absurdHigh: 100000,
    higherIsWorse: true,
    refs: {},
    version: V1,
  },
  {
    id: "FERRITIN",
    canonicalKey: "analyte.ferritin",
    displayName: "Ferritin",
    aliases: ["Serum Ferritin", "Ferritin", "S. Ferritin"],
    loinc: "2276-4",
    description: "Serum ferritin — iron store marker (also acute-phase).",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL", "µg/L"],
    precision: 0,
    referenceIntervals: [
      { sex: "male", low: 22, high: 322, note: "Adult male" },
      { sex: "female", low: 10, high: 291, note: "Adult female" },
    ],
    absurdLow: 0,
    absurdHigh: 100000,
    refs: {},
    version: V1,
  },
  {
    id: "VITAMIN_D",
    canonicalKey: "analyte.vitamin_d",
    displayName: "Vitamin D (25-OH)",
    shortName: "Vit D",
    aliases: ["25-Hydroxy Vitamin D", "Vitamin D", "25-OH Vitamin D", "Vit D", "25(OH)D", "Vitamin D3", "25 Hydroxy Vitamin D"],
    loinc: "1989-3",
    description: "25-hydroxyvitamin D — vitamin D status.",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "ng/mL",
    allowedUnits: ["ng/mL"],
    precision: 1,
    referenceIntervals: [
      { sex: "any", low: 30, high: 100, text: "Deficient < 20; Insufficient 20–29; Sufficient 30–100", source: "Endocrine Society" },
    ],
    absurdLow: 1,
    absurdHigh: 500,
    higherIsWorse: false,
    refs: {},
    version: V1,
  },
  {
    id: "VITAMIN_B12",
    canonicalKey: "analyte.vitamin_b12",
    displayName: "Vitamin B12",
    shortName: "B12",
    aliases: ["Vitamin B12", "B12", "Cobalamin", "Cyanocobalamin", "Vit B12", "Serum B12"],
    loinc: "2132-9",
    description: "Serum vitamin B12 (cobalamin).",
    department: "Biochemistry",
    resultType: "numeric",
    defaultUnit: "pg/mL",
    allowedUnits: ["pg/mL"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 200, high: 900, note: "Borderline 200–300" }],
    absurdLow: 20,
    absurdHigh: 20000,
    higherIsWorse: false,
    refs: {},
    version: V1,
  },

  // ══ Serology / Immunology — categorical ═══════════════════════════════════
  {
    id: "HBSAG",
    canonicalKey: "analyte.hbsag",
    displayName: "HBsAg",
    aliases: ["Hepatitis B Surface Antigen", "HBsAg", "HBS Ag", "Australia Antigen", "HBsAg (Rapid)", "HBsAg (ELISA)"],
    loinc: "5196-1",
    description: "Hepatitis B surface antigen (qualitative screen).",
    department: "Serology",
    resultType: "categorical",
    defaultUnit: "",
    allowedUnits: [],
    precision: 0,
    referenceIntervals: [],
    categories: [
      { value: "Non-Reactive", flag: "N", aliases: ["Negative", "Nil", "Absent", "Non Reactive"] },
      { value: "Reactive", flag: "A", aliases: ["Positive", "Present"] },
    ],
    refs: {},
    version: V1,
    notes: "Qualitative screen; reactive results require confirmatory testing.",
  },
  {
    id: "HIV_AB",
    canonicalKey: "analyte.hiv_ab",
    displayName: "HIV I & II Antibody",
    aliases: ["HIV", "HIV 1 & 2", "HIV I/II", "HIV Antibody", "Anti-HIV", "HIV I & II Ab", "HIV 1 and 2 Antibody"],
    loinc: "75622-1",
    description: "HIV-1/HIV-2 antibody (qualitative screen).",
    department: "Serology",
    resultType: "categorical",
    defaultUnit: "",
    allowedUnits: [],
    precision: 0,
    referenceIntervals: [],
    categories: [
      { value: "Non-Reactive", flag: "N", aliases: ["Negative", "Nil", "Non Reactive"] },
      { value: "Reactive", flag: "A", aliases: ["Positive"] },
    ],
    refs: {},
    version: V1,
    notes: "Screening assay; reactive results require confirmatory/Western-blot testing and ICTC referral.",
  },
  {
    id: "HCV_AB",
    canonicalKey: "analyte.hcv_ab",
    displayName: "HCV Antibody",
    aliases: ["Anti-HCV", "HCV", "Hepatitis C Antibody", "HCV Ab", "Anti HCV"],
    loinc: "16128-1",
    description: "Hepatitis C virus antibody (qualitative screen).",
    department: "Serology",
    resultType: "categorical",
    defaultUnit: "",
    allowedUnits: [],
    precision: 0,
    referenceIntervals: [],
    categories: [
      { value: "Non-Reactive", flag: "N", aliases: ["Negative", "Nil", "Non Reactive"] },
      { value: "Reactive", flag: "A", aliases: ["Positive"] },
    ],
    refs: {},
    version: V1,
  },
  {
    id: "VDRL",
    canonicalKey: "analyte.vdrl",
    displayName: "VDRL / RPR",
    aliases: ["VDRL", "RPR", "Syphilis", "VDRL/RPR", "Rapid Plasma Reagin"],
    description: "Non-treponemal syphilis screen.",
    department: "Serology",
    resultType: "categorical",
    defaultUnit: "",
    allowedUnits: [],
    precision: 0,
    referenceIntervals: [],
    categories: [
      { value: "Non-Reactive", flag: "N", aliases: ["Negative", "Nil", "Non Reactive"] },
      { value: "Reactive", flag: "A", aliases: ["Positive"] },
    ],
    refs: {},
    version: V1,
  },
  {
    id: "DENGUE_NS1",
    canonicalKey: "analyte.dengue_ns1",
    displayName: "Dengue NS1 Antigen",
    aliases: ["Dengue NS1", "NS1 Antigen", "Dengue NS1 Ag", "Dengue Antigen"],
    description: "Dengue NS1 antigen (early dengue infection).",
    department: "Serology",
    resultType: "categorical",
    defaultUnit: "",
    allowedUnits: [],
    precision: 0,
    referenceIntervals: [],
    categories: [
      { value: "Negative", flag: "N", aliases: ["Non-Reactive", "Nil", "Absent"] },
      { value: "Positive", flag: "A", aliases: ["Reactive", "Present"] },
    ],
    refs: {},
    version: V1,
  },
  {
    id: "WIDAL",
    canonicalKey: "analyte.widal",
    displayName: "Widal Test",
    aliases: ["Widal", "Widal Test", "Enteric Fever Serology", "Typhoid Test"],
    description: "Widal agglutination titre for enteric fever (O/H antigens).",
    department: "Serology",
    resultType: "titre",
    defaultUnit: "",
    allowedUnits: [],
    precision: 0,
    referenceIntervals: [],
    refs: {},
    version: V1,
    notes: "Reported as a titre (e.g. 1:80). Significance depends on local baseline and paired sera; not auto-flagged.",
  },
  {
    id: "BLOOD_GROUP",
    canonicalKey: "analyte.blood_group",
    displayName: "Blood Group (ABO/Rh)",
    aliases: ["Blood Group", "ABO Rh", "ABO Grouping", "Blood Group & Rh", "ABO and Rh", "Blood Grouping"],
    loinc: "882-1",
    description: "ABO blood group and Rh(D) type.",
    department: "Immunology",
    resultType: "categorical",
    defaultUnit: "",
    allowedUnits: [],
    precision: 0,
    referenceIntervals: [],
    categories: [
      { value: "A Positive", flag: "N", aliases: ["A+", "A Rh+", "A Pos"] },
      { value: "A Negative", flag: "N", aliases: ["A-", "A Rh-", "A Neg"] },
      { value: "B Positive", flag: "N", aliases: ["B+", "B Rh+", "B Pos"] },
      { value: "B Negative", flag: "N", aliases: ["B-", "B Rh-", "B Neg"] },
      { value: "AB Positive", flag: "N", aliases: ["AB+", "AB Rh+", "AB Pos"] },
      { value: "AB Negative", flag: "N", aliases: ["AB-", "AB Rh-", "AB Neg"] },
      { value: "O Positive", flag: "N", aliases: ["O+", "O Rh+", "O Pos"] },
      { value: "O Negative", flag: "N", aliases: ["O-", "O Rh-", "O Neg"] },
    ],
    refs: {},
    version: V1,
    notes: "Informational (no abnormal state). O-negative flagged by transfusion services separately.",
  },

  // ══ Clinical Pathology — Urine routine ════════════════════════════════════
  {
    id: "URINE_PROTEIN",
    canonicalKey: "analyte.urine_protein",
    displayName: "Urine Protein",
    aliases: ["Urine Albumin", "Urine Protein", "Albumin (Urine)", "Protein (Urine)", "Urinary Protein"],
    description: "Semi-quantitative dipstick urinary protein.",
    department: "Clinical Pathology",
    resultType: "categorical",
    defaultUnit: "",
    allowedUnits: [],
    precision: 0,
    referenceIntervals: [],
    categories: [
      { value: "Nil", flag: "N", aliases: ["Absent", "Negative", "Nil/Absent"] },
      { value: "Trace", flag: "N", aliases: ["+/-"] },
      { value: "1+", flag: "A", aliases: ["Present", "+"] },
      { value: "2+", flag: "A", aliases: ["++"] },
      { value: "3+", flag: "A", aliases: ["+++"] },
      { value: "4+", flag: "A", aliases: ["++++"] },
    ],
    refs: {},
    version: V1,
  },
  {
    id: "URINE_SUGAR",
    canonicalKey: "analyte.urine_sugar",
    displayName: "Urine Sugar",
    aliases: ["Urine Glucose", "Urine Sugar", "Glucose (Urine)", "Sugar (Urine)", "Urinary Glucose"],
    description: "Semi-quantitative dipstick urinary glucose.",
    department: "Clinical Pathology",
    resultType: "categorical",
    defaultUnit: "",
    allowedUnits: [],
    precision: 0,
    referenceIntervals: [],
    categories: [
      { value: "Nil", flag: "N", aliases: ["Absent", "Negative", "Nil/Absent"] },
      { value: "Trace", flag: "N", aliases: ["+/-"] },
      { value: "1+", flag: "A", aliases: ["Present", "+"] },
      { value: "2+", flag: "A", aliases: ["++"] },
      { value: "3+", flag: "A", aliases: ["+++"] },
      { value: "4+", flag: "A", aliases: ["++++"] },
    ],
    refs: {},
    version: V1,
  },
  {
    id: "URINE_PUS_CELLS",
    canonicalKey: "analyte.urine_pus_cells",
    displayName: "Urine Pus Cells",
    aliases: ["Pus Cells", "Urine Pus Cells", "WBC (Urine)", "Leucocytes (Urine)", "Pus Cells (Urine)"],
    description: "Urinary leukocytes per high-power field (microscopy).",
    department: "Clinical Pathology",
    resultType: "numeric",
    defaultUnit: "/hpf",
    allowedUnits: ["/hpf"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 0, high: 5, text: "0–5 /hpf" }],
    absurdLow: 0,
    absurdHigh: 1000,
    higherIsWorse: true,
    refs: {},
    version: V1,
  },
  {
    id: "URINE_RBC",
    canonicalKey: "analyte.urine_rbc",
    displayName: "Urine RBCs",
    aliases: ["RBC (Urine)", "Urine RBC", "Red Cells (Urine)", "Urinary RBC", "Erythrocytes (Urine)"],
    description: "Urinary red cells per high-power field (microscopy).",
    department: "Clinical Pathology",
    resultType: "numeric",
    defaultUnit: "/hpf",
    allowedUnits: ["/hpf"],
    precision: 0,
    referenceIntervals: [{ sex: "any", low: 0, high: 2, text: "0–2 /hpf" }],
    absurdLow: 0,
    absurdHigh: 1000,
    higherIsWorse: true,
    refs: {},
    version: V1,
  },
];

export const PATHOLOGY_PANEL_CATALOG: readonly PanelDefinition[] = [
  {
    id: "CBC",
    canonicalKey: "panel.cbc",
    displayName: "Complete Blood Count",
    aliases: ["CBC", "Complete Blood Count", "Hemogram", "Haemogram", "CBC with Differential", "Complete Hemogram", "Blood Count", "CBP"],
    loinc: "58410-2",
    description: "Full hemogram: red-cell indices, white-cell count and differential, platelets.",
    department: "Hematology",
    analytes: [
      "HEMOGLOBIN", "HEMATOCRIT", "RBC_COUNT", "WBC_COUNT", "PLATELET_COUNT",
      "MCV", "MCH", "MCHC", "RDW",
      "NEUTROPHILS_PCT", "LYMPHOCYTES_PCT", "MONOCYTES_PCT", "EOSINOPHILS_PCT", "BASOPHILS_PCT",
    ],
    version: V1,
  },
  {
    id: "LFT",
    canonicalKey: "panel.lft",
    displayName: "Liver Function Test",
    aliases: ["LFT", "Liver Function Test", "Liver Profile", "LFT Panel", "Hepatic Function Panel", "Liver Function Tests"],
    loinc: "24325-3",
    description: "Bilirubin fractions, transaminases, ALP, GGT, total protein, albumin, globulin.",
    department: "Biochemistry",
    analytes: [
      "BILIRUBIN_TOTAL", "BILIRUBIN_DIRECT", "BILIRUBIN_INDIRECT",
      "SGPT_ALT", "SGOT_AST", "ALP", "GGT",
      "PROTEIN_TOTAL", "ALBUMIN", "GLOBULIN", "AG_RATIO",
    ],
    version: V1,
  },
  {
    id: "KFT",
    canonicalKey: "panel.kft",
    displayName: "Kidney Function Test",
    aliases: ["KFT", "RFT", "Renal Function Test", "Kidney Function Test", "Renal Profile", "KFT Panel", "Kidney Profile"],
    loinc: "24362-6",
    description: "Urea, BUN, creatinine, uric acid, electrolytes and calcium.",
    department: "Biochemistry",
    analytes: [
      "UREA", "BUN", "CREATININE", "URIC_ACID",
      "SODIUM", "POTASSIUM", "CHLORIDE", "CALCIUM", "PHOSPHORUS",
    ],
    version: V1,
  },
  {
    id: "LIPID_PROFILE",
    canonicalKey: "panel.lipid_profile",
    displayName: "Lipid Profile",
    aliases: ["Lipid Profile", "Lipid Panel", "Cholesterol Profile", "Lipid Profile Test", "Fasting Lipid Profile"],
    loinc: "57698-3",
    description: "Total cholesterol, triglycerides, HDL, LDL and VLDL.",
    department: "Biochemistry",
    analytes: ["CHOLESTEROL_TOTAL", "TRIGLYCERIDES", "HDL_CHOLESTEROL", "LDL_CHOLESTEROL", "VLDL_CHOLESTEROL"],
    version: V1,
  },
  {
    id: "THYROID_PROFILE",
    canonicalKey: "panel.thyroid_profile",
    displayName: "Thyroid Profile (Total)",
    aliases: ["Thyroid Profile", "TFT", "Thyroid Function Test", "T3 T4 TSH", "Thyroid Profile Total", "Thyroid Panel"],
    description: "Total T3, total T4 and TSH.",
    department: "Endocrinology",
    analytes: ["T3_TOTAL", "T4_TOTAL", "TSH"],
    version: V1,
  },
  {
    id: "FREE_THYROID_PROFILE",
    canonicalKey: "panel.free_thyroid_profile",
    displayName: "Thyroid Profile (Free)",
    aliases: ["Free Thyroid Profile", "Free TFT", "FT3 FT4 TSH", "Free Thyroid Panel"],
    description: "Free T3, free T4 and TSH.",
    department: "Endocrinology",
    analytes: ["FT3", "FT4", "TSH"],
    version: V1,
  },
  {
    id: "ELECTROLYTES",
    canonicalKey: "panel.electrolytes",
    displayName: "Serum Electrolytes",
    aliases: ["Electrolytes", "Serum Electrolytes", "Electrolyte Panel", "Na K Cl", "Electrolytes Panel"],
    loinc: "55231-5",
    description: "Sodium, potassium, chloride and bicarbonate.",
    department: "Biochemistry",
    analytes: ["SODIUM", "POTASSIUM", "CHLORIDE", "BICARBONATE"],
    version: V1,
  },
  {
    id: "DIABETIC_PROFILE",
    canonicalKey: "panel.diabetic_profile",
    displayName: "Diabetic Profile",
    aliases: ["Diabetic Profile", "Diabetes Panel", "Sugar Profile", "Glucose Profile", "Diabetic Panel"],
    description: "Fasting and post-prandial glucose with HbA1c.",
    department: "Biochemistry",
    analytes: ["GLUCOSE_FASTING", "GLUCOSE_PP", "HBA1C"],
    version: V1,
  },
];
