// catalog.ts — the Universal Measurement Catalog: one canonical identity per
// measurement, with every legacy spelling found in the platform as an alias.
//
// Sources unified here (the Step-1 audit's duplication map):
//   - artifacts/diagnostic-erp/src/lib/radiologyMeasurementLibrary.ts (kebab ids)
//   - artifacts/diagnostic-erp/src/components/MeasurementAssistantPanel.tsx (labels)
//   - artifacts/api-server/src/routes/radiologyLesions.ts MEASUREMENT_TEMPLATES (labels)
//   - lib/db usg_measurements / usg_doppler_measurements / fetal_usg_measurements (columns)
//   - artifacts/api-server/src/lib/usgCompanion.ts EXPECTED_MEASUREMENTS (column+label)
//   - radiology_quick_measurements + radiology_protocols seed rows (Title-Case + snake_case)
//   - seeds/radiology/content-packs/v1/_shared_libraries*.yaml (meas.* canonical keys)
//   - lib/report-quality structured rule params (labels + columns)
//
// RULES OF THE FILE:
//   - `id` is immutable. Never rename; deprecate + `replacedBy` instead.
//   - Every spelling that exists in shipped data/code MUST appear in `aliases`
//     (resolution is deterministic — no fuzzy matching).
//   - Where legacy sources disagree on units/ranges, the registry records the
//     clinically-standard value and the disagreement in `notes` — consumers
//     inherit ONE truth from here.

import type { MeasurementDefinition } from "./contract";

export const MEASUREMENT_CATALOG_VERSION = "1.0.0";

const V1 = "1.0.0";

export const MEASUREMENT_CATALOG: readonly MeasurementDefinition[] = [
  // ── Neuro (CT / MR) ───────────────────────────────────────────────────────
  {
    id: "MIDLINE_SHIFT",
    canonicalKey: "meas.midline_shift",
    displayName: "Midline Shift",
    aliases: ["Midline Shift", "Midline shift", "midline_shift", "midlineShift", "MLS"],
    description: "Displacement of midline brain structures from the midsagittal plane.",
    modalities: ["CT", "MR"],
    bodyRegion: "Brain",
    studyTypes: ["CT Brain Plain", "CT Brain Contrast", "MRI Brain"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "midline\\s*shift" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 2, note: "> 2 mm reportable (MeasurementAssistant/radiologyLesions convention)" },
    criticalRange: { high: 5, note: ">= 5 mm critical (content-pack crit.midline_shift)" },
    refs: {
      copilotKeys: ["midlineShift"],
      qualityRules: ["care.measurement.range.midline-shift"],
      knowledgePacks: ["CT Brain Plain"],
      reportTemplates: ["BRAIN"],
    },
    version: V1,
  },
  {
    id: "HEMORRHAGE_VOLUME",
    canonicalKey: "meas.hemorrhage_volume",
    displayName: "Hemorrhage Volume",
    aliases: ["Hemorrhage volume", "Haemorrhage volume", "hemorrhage_volume", "ICH volume"],
    description: "Estimated intracranial hemorrhage volume (ABC/2 or planimetric).",
    modalities: ["CT"],
    bodyRegion: "Brain",
    studyTypes: ["CT Brain Plain"],
    defaultUnit: "ml",
    allowedUnits: ["ml"],
    precision: 1,
    viewerMapping: { tool: "volume" },
    comparisonStrategy: "percent-change",
    criticalRange: { high: 30, note: ">= 30 ml adverse-outcome threshold (supratentorial ICH)" },
    refs: { knowledgePacks: ["CT Brain Plain"], qualityRules: ["care.measurement.range.hemorrhage-volume"] },
    version: V1,
  },
  {
    id: "EVANS_INDEX",
    canonicalKey: "meas.evans_index",
    displayName: "Evans Index",
    aliases: ["Evans Index", "Evans' Index", "evans_index", "brain-evans"],
    description: "Ratio of frontal horn width to maximal internal skull diameter.",
    modalities: ["CT", "MR"],
    bodyRegion: "Brain",
    studyTypes: ["CT Brain Plain", "MRI Brain"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio"],
    precision: 2,
    viewerMapping: { tool: "ratio" },
    comparisonStrategy: "ratio-trend",
    normalRange: { high: 0.33, note: "> 0.3 suggests ventriculomegaly" },
    refs: { reportTemplates: ["BRAIN"] },
    version: V1,
    notes: "Auto-calc: frontal horn width / max internal skull diameter (content-pack auto_calc).",
  },
  {
    id: "VENTRICULAR_INDEX",
    canonicalKey: "meas.ventricular_index",
    displayName: "Ventricular Index",
    aliases: ["Ventricular Index", "ventricular_index", "ventricleSize", "Ventricle size"],
    description: "Ventricular size index (cranial US / neuro follow-up trend metric).",
    modalities: ["US", "CT", "MR"],
    bodyRegion: "Brain",
    studyTypes: ["Neurosonogram", "CT Brain Plain", "MRI Brain"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio", "mm"],
    precision: 2,
    viewerMapping: { tool: "ratio" },
    comparisonStrategy: "ratio-trend",
    refs: { copilotKeys: ["ventricleSize"] },
    version: V1,
  },
  {
    id: "THIRD_VENTRICLE_WIDTH",
    canonicalKey: "meas.third_ventricle_width",
    displayName: "Third Ventricle Width",
    aliases: ["Third Ventricle Width", "Cerebral Ventricle Width (3rd)", "3rd ventricle width", "third_ventricle"],
    description: "Transverse width of the third ventricle.",
    modalities: ["CT", "MR", "US"],
    bodyRegion: "Brain",
    studyTypes: ["CT Brain Plain", "MRI Brain", "Neurosonogram"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 10, note: "adult upper limit; age-dependent" },
    refs: { reportTemplates: ["BRAIN"] },
    version: V1,
    notes: "MeasurementAssistantPanel and radiologyLesions templates use divergent labels — both aliased.",
  },

  // ── Spine (MR / XR) ───────────────────────────────────────────────────────
  {
    id: "CANAL_AP",
    canonicalKey: "meas.canal_ap",
    displayName: "Spinal Canal AP Diameter",
    aliases: ["AP Canal Diameter", "Spinal canal diameter", "AP canal diameter", "canal_ap", "mri-cerv-ap-canal", "Canal AP diameter"],
    description: "Anteroposterior diameter of the bony spinal canal at the measured level.",
    modalities: ["MR", "CT"],
    bodyRegion: "Spine",
    studyTypes: ["MRI Cervical Spine", "MRI LS Spine", "LS Spine"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "canal" },
    comparisonStrategy: "absolute-change",
    normalRange: { low: 13, note: ">= 13 mm cervical; < 10 mm = absolute stenosis" },
    refs: { qualityRules: ["care.measurement.range.canal-ap"], reportTemplates: ["MRI_CERVICAL", "MRI_LS"] },
    version: V1,
  },
  {
    id: "DISC_HEIGHT",
    canonicalKey: "meas.disc_height",
    displayName: "Disc Height",
    aliases: ["Disc Height", "disc_height", "discSize", "Disc height loss"],
    description: "Intervertebral disc height at the measured level.",
    modalities: ["MR", "XR", "CT"],
    bodyRegion: "Spine",
    studyTypes: ["MRI LS Spine", "LS Spine"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear" },
    comparisonStrategy: "absolute-change",
    refs: { copilotKeys: ["discSize"] },
    version: V1,
  },
  {
    id: "CORD_DIAMETER",
    canonicalKey: "meas.cord_diameter",
    displayName: "Spinal Cord Diameter",
    aliases: ["Cord Diameter", "Spinal cord diameter", "cord_diameter", "Cord AP diameter"],
    description: "AP diameter of the spinal cord at the measured level.",
    modalities: ["MR"],
    bodyRegion: "Spine",
    studyTypes: ["MRI Cervical Spine", "MRI Dorsal Spine"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear" },
    comparisonStrategy: "absolute-change",
    refs: {},
    version: V1,
  },
  {
    id: "VERTEBRAL_HEIGHT",
    canonicalKey: "meas.vertebral_height",
    displayName: "Vertebral Body Height",
    aliases: ["Vertebral Height", "Vertebral body height", "vertebral_height"],
    description: "Height of a vertebral body (anterior/middle/posterior as noted).",
    modalities: ["XR", "CT", "MR"],
    bodyRegion: "Spine",
    studyTypes: ["LS Spine", "Dorsal Spine"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear" },
    comparisonStrategy: "absolute-change",
    refs: {},
    version: V1,
  },
  {
    id: "VERTEBRAL_HEIGHT_LOSS",
    canonicalKey: "meas.vertebral_height_loss",
    displayName: "Vertebral Height Loss",
    aliases: ["Vertebral height loss", "vertebral_height_loss", "Height loss"],
    description: "Percentage compression of a vertebral body relative to adjacent normal bodies.",
    modalities: ["XR", "CT", "MR"],
    bodyRegion: "Spine",
    studyTypes: ["LS Spine", "Dorsal Spine"],
    defaultUnit: "%",
    allowedUnits: ["%"],
    precision: 0,
    viewerMapping: { tool: "ratio" },
    comparisonStrategy: "absolute-change",
    criticalRange: { high: 40, note: "> 40% loss suggests unstable compression" },
    refs: { qualityRules: ["care.measurement.range.vertebral-height-loss"] },
    version: V1,
  },
  {
    id: "COBB_ANGLE",
    canonicalKey: "meas.cobb_angle",
    displayName: "Cobb Angle",
    aliases: ["Cobb angle", "cobb_angle", "Cobb"],
    description: "Coronal curvature angle between the most tilted vertebrae (scoliosis grading).",
    modalities: ["XR"],
    bodyRegion: "Spine",
    studyTypes: ["Whole Spine", "Dorsal Spine", "LS Spine"],
    defaultUnit: "deg",
    allowedUnits: ["deg"],
    precision: 0,
    viewerMapping: { tool: "angle", dicomSrPattern: "cobb" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 10, note: ">= 10° defines scoliosis; > 40-50° surgical range" },
    refs: { qualityRules: ["care.measurement.range.cobb-angle"] },
    version: V1,
  },
  {
    id: "JOINT_SPACE",
    canonicalKey: "meas.joint_space",
    displayName: "Joint Space Width",
    aliases: ["Joint space", "Joint space width", "joint_space", "JSW"],
    description: "Radiographic joint space width at the measured compartment.",
    modalities: ["XR"],
    bodyRegion: "MSK",
    studyTypes: ["Knee", "Hip", "Joints"],
    defaultUnit: "mm",
    allowedUnits: ["mm"],
    precision: 1,
    viewerMapping: { tool: "linear" },
    comparisonStrategy: "absolute-change",
    refs: {},
    version: V1,
  },

  // ── Chest (XR / CT) ───────────────────────────────────────────────────────
  {
    id: "CTR",
    canonicalKey: "meas.ctr",
    displayName: "Cardiothoracic Ratio",
    aliases: ["Cardiothoracic ratio", "CT ratio", "ctr", "Cardio-thoracic ratio"],
    description: "Cardiac width divided by thoracic width on a PA chest radiograph.",
    modalities: ["XR"],
    bodyRegion: "Chest",
    studyTypes: ["Chest PA"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio", "%"],
    precision: 2,
    viewerMapping: { tool: "ratio" },
    comparisonStrategy: "ratio-trend",
    normalRange: { high: 0.5, note: "> 0.50 on PA = cardiomegaly (content-pack flag)" },
    refs: { qualityRules: ["care.measurement.range.ctr"], knowledgePacks: ["Chest PA"] },
    version: V1,
    notes: "Auto-calc: cardiac width / thoracic width.",
  },
  {
    id: "NODULE_SIZE",
    canonicalKey: "meas.nodule_size",
    displayName: "Nodule Size",
    aliases: ["Nodule size", "nodule_size", "Thyroid nodule size", "Lung nodule size", "Nodule diameter"],
    description: "Longest axial diameter of a nodule (lung, thyroid, or other as contexted).",
    modalities: ["CT", "US", "XR"],
    bodyRegion: "Chest",
    studyTypes: ["HRCT Chest", "Thyroid"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "nodule" },
    comparisonStrategy: "percent-change",
    refs: { knowledgePacks: ["HRCT Chest"] },
    version: V1,
    notes: "Follow-up growth is the clinically-relevant signal — percent-change comparison.",
  },
  {
    id: "RV_LV_RATIO",
    canonicalKey: "meas.rv_lv_ratio",
    displayName: "RV:LV Ratio",
    aliases: ["RV:LV ratio", "RV/LV ratio", "rv_lv_ratio"],
    description: "Right-to-left ventricular diameter ratio (CT pulmonary angiography strain marker).",
    modalities: ["CT"],
    bodyRegion: "Chest",
    studyTypes: ["CTPA"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio"],
    precision: 2,
    viewerMapping: { tool: "ratio" },
    comparisonStrategy: "ratio-trend",
    normalRange: { high: 1, note: "> 1.0 suggests right-heart strain" },
    refs: { qualityRules: ["care.measurement.range.rv-lv-ratio"] },
    version: V1,
  },

  // ── Abdomen / KUB (US / CT) ───────────────────────────────────────────────
  {
    id: "STONE_SIZE",
    canonicalKey: "meas.calculus_size",
    displayName: "Stone Size",
    aliases: ["Stone size", "Stone Size (if present)", "Renal Stone Size", "Calculus size", "calculus_size", "stone_size", "Calculus"],
    description: "Largest diameter of a calculus (renal, ureteric, biliary, or other as contexted).",
    modalities: ["US", "CT", "XR"],
    bodyRegion: "Abdomen",
    studyTypes: ["KUB", "CT KUB", "Whole Abdomen", "Abdomen"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "stone|calcul" },
    comparisonStrategy: "absolute-change",
    criticalRange: { high: 6, note: "> 6 mm ureteric stone unlikely to pass spontaneously" },
    refs: {
      qualityRules: ["care.measurement.range.stone-size"],
      knowledgePacks: ["CT KUB", "KUB"],
      reportTemplates: ["USG_ABD"],
    },
    version: V1,
    notes: "Label variants Stone/Renal Stone/Calculus unified here (audit cluster #7).",
  },
  {
    id: "STONE_HU",
    canonicalKey: "meas.stone_hu",
    displayName: "Stone Density",
    aliases: ["Stone density", "Stone HU", "stone_density", "stone_hu", "Calculus density"],
    description: "Attenuation of a calculus in Hounsfield units (composition/lithotripsy planning).",
    modalities: ["CT"],
    bodyRegion: "Abdomen",
    studyTypes: ["CT KUB"],
    defaultUnit: "HU",
    allowedUnits: ["HU"],
    precision: 0,
    viewerMapping: { tool: "density", dicomSrPattern: "density|hounsfield" },
    comparisonStrategy: "absolute-change",
    refs: { knowledgePacks: ["CT KUB"] },
    version: V1,
  },
  {
    id: "CBD",
    canonicalKey: "meas.cbd",
    displayName: "Common Bile Duct Diameter",
    aliases: [
      "CBD", "CBD Diameter", "CBD diameter", "cbd_diameter", "cbd", "cbdMm",
      "Common Bile Duct", "Common bile duct", "Common Bile Duct Diameter", "usg-cbd",
    ],
    description: "Internal diameter of the common bile duct at the porta hepatis.",
    modalities: ["US", "CT", "MR"],
    bodyRegion: "Abdomen",
    studyTypes: ["Whole Abdomen", "Abdomen", "Upper Abdomen"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "\\bcbd\\b|common bile" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 6, note: "> 6 mm dilated; post-cholecystectomy up to 8-10 mm accepted" },
    criticalRange: { high: 10, note: "> 10 mm obstructive range" },
    refs: {
      usgColumns: ["cbd", "cbdMm"],
      companionKeys: ["cbd"],
      qualityRules: ["care.measurement.range.cbd"],
      knowledgePacks: ["Whole Abdomen"],
      reportTemplates: ["USG_ABD"],
    },
    version: V1,
    notes: "Defined in 10 places pre-registry (audit cluster #1) — the canonical example of the problem.",
  },
  {
    id: "GB_WALL",
    canonicalKey: "meas.gb_wall",
    displayName: "Gallbladder Wall Thickness",
    aliases: ["GB Wall", "GB wall", "gbWall", "gb_wall", "Gallbladder wall", "Gall bladder wall thickness", "GB wall thickness"],
    description: "Gallbladder wall thickness (fasting).",
    modalities: ["US", "CT"],
    bodyRegion: "Abdomen",
    studyTypes: ["Whole Abdomen", "Abdomen", "Upper Abdomen"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "gall.?bladder wall|gb wall" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 3, note: "> 3 mm thickened (fasting)" },
    refs: { usgColumns: ["gbWall"], companionKeys: ["gbWall"], qualityRules: ["care.measurement.range.gb-wall"] },
    version: V1,
  },
  {
    id: "LIVER_LENGTH",
    canonicalKey: "meas.liver_span",
    displayName: "Liver Span",
    aliases: [
      "Liver Span", "Liver span", "liver_span", "liverSize", "liverSpanMm", "Liver Size", "Liver size",
      "Liver Longitudinal Span", "Liver Span (MCL)", "Liver", "Hepatic span",
    ],
    description: "Craniocaudal liver span in the midclavicular line.",
    modalities: ["US", "CT"],
    bodyRegion: "Abdomen",
    studyTypes: ["Whole Abdomen", "Abdomen", "Upper Abdomen"],
    defaultUnit: "cm",
    allowedUnits: ["cm", "mm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "liver" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 15.5, note: "> 15.5 cm = hepatomegaly (adult)" },
    refs: {
      usgColumns: ["liverSize", "liverSpanMm"],
      companionKeys: ["liverSize"],
      qualityRules: ["care.measurement.range.liver-length"],
      knowledgePacks: ["Whole Abdomen"],
      reportTemplates: ["USG_ABD"],
    },
    version: V1,
    notes: "Id kept as LIVER_LENGTH (platform spec); canonicalKey bridges legacy meas.liver_span.",
  },
  {
    id: "SPLEEN_LENGTH",
    canonicalKey: "meas.spleen_length",
    displayName: "Spleen Length",
    aliases: ["Spleen Length", "Spleen size", "Spleen span", "spleenSize", "spleen_length", "Splenic span"],
    description: "Craniocaudal splenic length.",
    modalities: ["US", "CT"],
    bodyRegion: "Abdomen",
    studyTypes: ["Whole Abdomen", "Abdomen", "Upper Abdomen"],
    defaultUnit: "cm",
    allowedUnits: ["cm", "mm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "spleen" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 12, note: "> 12-13 cm = splenomegaly (adult)" },
    refs: { usgColumns: ["spleenSize"], companionKeys: ["spleenSize"], reportTemplates: ["USG_ABD"] },
    version: V1,
  },
  {
    id: "RENAL_LENGTH_RIGHT",
    canonicalKey: "meas.renal_length_right",
    displayName: "Right Kidney Length",
    aliases: ["Right kidney length", "Right Kidney — Length", "Right Kidney", "rightKidney", "rightKidneyLengthMm", "right_kidney_length", "Right renal length"],
    description: "Bipolar length of the right kidney.",
    modalities: ["US", "CT"],
    bodyRegion: "Abdomen",
    studyTypes: ["Whole Abdomen", "KUB", "Abdomen"],
    defaultUnit: "cm",
    allowedUnits: ["cm", "mm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "right kidney|rt\\.? kidney" },
    comparisonStrategy: "absolute-change",
    normalRange: { low: 9, high: 12, note: "adult bipolar length 9-12 cm" },
    refs: {
      usgColumns: ["rightKidney", "rightKidneyLengthMm"],
      companionKeys: ["rightKidney"],
      qualityRules: ["care.measurement.range.renal-length-right"],
      knowledgePacks: ["Whole Abdomen"],
    },
    version: V1,
    notes: "Legacy stores mix mm and cm (audit cluster #4); registry default is cm with conversion.",
  },
  {
    id: "RENAL_LENGTH_LEFT",
    canonicalKey: "meas.renal_length_left",
    displayName: "Left Kidney Length",
    aliases: ["Left kidney length", "Left Kidney — Length", "Left Kidney", "leftKidney", "leftKidneyLengthMm", "left_kidney_length", "Left renal length"],
    description: "Bipolar length of the left kidney.",
    modalities: ["US", "CT"],
    bodyRegion: "Abdomen",
    studyTypes: ["Whole Abdomen", "KUB", "Abdomen"],
    defaultUnit: "cm",
    allowedUnits: ["cm", "mm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "left kidney|lt\\.? kidney" },
    comparisonStrategy: "absolute-change",
    normalRange: { low: 9, high: 12, note: "adult bipolar length 9-12 cm" },
    refs: {
      usgColumns: ["leftKidney", "leftKidneyLengthMm"],
      companionKeys: ["leftKidney"],
      qualityRules: ["care.measurement.range.renal-length-left"],
      knowledgePacks: ["Whole Abdomen"],
    },
    version: V1,
  },
  {
    id: "RENAL_LENGTH",
    canonicalKey: "meas.kidney_size",
    displayName: "Renal Length (unsided)",
    aliases: ["Kidney size", "Kidney length", "Renal length", "kidney_size", "renal_length"],
    description: "Unsided kidney length — legacy templates that do not specify side resolve here.",
    modalities: ["US", "CT"],
    bodyRegion: "Abdomen",
    studyTypes: ["Whole Abdomen", "KUB", "Abdomen"],
    defaultUnit: "cm",
    allowedUnits: ["cm", "mm"],
    precision: 1,
    viewerMapping: { tool: "linear" },
    comparisonStrategy: "absolute-change",
    normalRange: { low: 9, high: 12 },
    refs: {},
    version: V1,
    notes: "Prefer RENAL_LENGTH_RIGHT / RENAL_LENGTH_LEFT in new content; kept for unsided legacy labels.",
  },
  {
    id: "PROSTATE_VOLUME",
    canonicalKey: "meas.prostate_volume",
    displayName: "Prostate Volume",
    aliases: ["Prostate volume", "Prostate Volume", "prostateVolume", "prostate_volume", "usg-prostate", "Prostate size"],
    description: "Prostate volume by ellipsoid formula (L x W x H x 0.52).",
    modalities: ["US", "MR"],
    bodyRegion: "Pelvis",
    studyTypes: ["Pelvis", "Abdomen", "KUB"],
    defaultUnit: "ml",
    allowedUnits: ["ml", "g"],
    precision: 1,
    viewerMapping: { tool: "volume", dicomSrPattern: "prostate" },
    comparisonStrategy: "percent-change",
    normalRange: { high: 30, note: "> 30 ml enlarged" },
    refs: { usgColumns: ["prostateVolume"], companionKeys: ["prostateVolume"], qualityRules: ["care.measurement.range.prostate-volume"] },
    version: V1,
    notes: "Legacy sources disagree cc vs g (audit cluster #5); ml is canonical (cc≡ml, g≈ml for prostate tissue).",
  },
  {
    id: "PVR",
    canonicalKey: "meas.pvr",
    displayName: "Post-Void Residual",
    aliases: ["PVR", "Post-void residual", "Post void residual", "pvr", "Residual urine"],
    description: "Bladder volume immediately after voiding.",
    modalities: ["US"],
    bodyRegion: "Pelvis",
    studyTypes: ["KUB", "Pelvis", "Whole Abdomen"],
    defaultUnit: "ml",
    allowedUnits: ["ml"],
    precision: 0,
    viewerMapping: { tool: "volume", dicomSrPattern: "post.?void|residual" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 50, note: "> 50 ml significant in adults (context-dependent)" },
    refs: { qualityRules: ["care.measurement.range.pvr"] },
    version: V1,
  },
  {
    id: "APPENDIX_DIAMETER",
    canonicalKey: "meas.appendix_diameter",
    displayName: "Appendix Diameter",
    aliases: ["Appendix diameter", "Appendiceal diameter", "appendix_diameter", "Appendix"],
    description: "Outer wall-to-wall diameter of the appendix under compression.",
    modalities: ["US", "CT"],
    bodyRegion: "Abdomen",
    studyTypes: ["Whole Abdomen", "Abdomen", "CT Abdomen"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "appendix" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 6, note: "> 6 mm supports appendicitis" },
    refs: { qualityRules: ["care.measurement.range.appendix-diameter"] },
    version: V1,
  },
  {
    id: "AORTA_DIAMETER",
    canonicalKey: "meas.aorta_diameter",
    displayName: "Abdominal Aorta Diameter",
    aliases: ["Aorta diameter", "Aortic diameter", "aorta_diameter", "Abdominal aorta diameter", "AA diameter"],
    description: "Maximal outer-to-outer AP diameter of the abdominal aorta.",
    modalities: ["US", "CT"],
    bodyRegion: "Abdomen",
    studyTypes: ["Whole Abdomen", "CT Abdomen", "Doppler"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "aorta" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 30, note: ">= 30 mm = aneurysmal" },
    criticalRange: { high: 55, note: ">= 55 mm repair threshold" },
    refs: { qualityRules: ["care.measurement.range.aorta-diameter"] },
    version: V1,
  },
  {
    id: "ANEURYSM_SIZE",
    canonicalKey: "meas.aneurysm_size",
    displayName: "Aneurysm Size",
    aliases: ["Aneurysm size", "aneurysm_size", "Aneurysm diameter", "Sac size"],
    description: "Maximal diameter of an aneurysm sac (any territory; site in context).",
    modalities: ["US", "CT", "MR"],
    bodyRegion: "Vascular",
    studyTypes: ["CT Abdomen", "CT Brain Contrast", "Doppler"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "aneurysm" },
    comparisonStrategy: "percent-change",
    refs: {},
    version: V1,
  },
  {
    id: "ENDOMETRIAL_THICKNESS",
    canonicalKey: "meas.et",
    displayName: "Endometrial Thickness",
    aliases: ["Endometrial Thickness", "Endometrial thickness", "Endometrium", "endometrium", "ET", "et", "endometrial_thickness"],
    description: "Double-layer endometrial thickness on midline sagittal view.",
    modalities: ["US"],
    bodyRegion: "Pelvis",
    studyTypes: ["Pelvis", "TVS", "Follicular", "Infertility", "Endometrium"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "endometri" },
    comparisonStrategy: "absolute-change",
    normalRange: { low: 4, high: 14, note: "cycle-phase dependent; > 4-5 mm postmenopausal warrants evaluation" },
    refs: { usgColumns: ["endometrium"], qualityRules: ["care.measurement.range.endometrial-thickness"] },
    version: V1,
  },

  // ── Obstetric (US) ────────────────────────────────────────────────────────
  {
    id: "CRL",
    canonicalKey: "meas.crl",
    displayName: "Crown-Rump Length",
    aliases: ["CRL", "crl", "Crown-Rump Length", "Crown rump length"],
    description: "First-trimester embryonic/fetal crown-rump length (primary dating metric).",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Early Pregnancy", "NT", "Dating"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "\\bcrl\\b|crown.?rump" },
    comparisonStrategy: "absolute-change",
    refs: { usgColumns: ["crl"] },
    version: V1,
    notes: "CRL-vs-GA consistency is a future Phase-4 rule, keyed by this id when it ships.",
  },
  {
    id: "GS",
    canonicalKey: "meas.gs",
    displayName: "Gestational Sac Diameter",
    aliases: ["GS", "gs", "Gestational Sac", "Gestational sac diameter", "Mean Sac Diameter", "MSD", "msd"],
    description: "Mean gestational sac diameter (average of three orthogonal planes).",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Early Pregnancy", "Dating"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "gestational sac|\\bmsd\\b" },
    comparisonStrategy: "absolute-change",
    refs: { usgColumns: ["msd"] },
    version: V1,
  },
  {
    id: "YS",
    canonicalKey: "meas.ys",
    displayName: "Yolk Sac Diameter",
    aliases: ["YS", "ys", "Yolk Sac", "Yolk sac diameter"],
    description: "Yolk sac diameter in early pregnancy.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Early Pregnancy"],
    defaultUnit: "mm",
    allowedUnits: ["mm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "yolk" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 6, note: "> 6 mm associated with poor outcome" },
    refs: {},
    version: V1,
  },
  {
    id: "NT",
    canonicalKey: "meas.nt",
    displayName: "Nuchal Translucency",
    aliases: ["NT", "nt", "Nuchal Translucency", "Nuchal translucency"],
    description: "Nuchal translucency thickness at 11-13+6 weeks.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["NT"],
    defaultUnit: "mm",
    allowedUnits: ["mm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "nuchal" },
    comparisonStrategy: "absolute-change",
    normalRange: { high: 3, note: ">= 3.0 mm increased (structured rule threshold)" },
    refs: { qualityRules: ["care.measurement.range.nt"] },
    version: V1,
  },
  {
    id: "BPD",
    canonicalKey: "meas.bpd",
    displayName: "Biparietal Diameter",
    aliases: ["BPD", "bpd", "BPD (Biparietal Diameter)", "BPD (Biparietal Dia.)", "Biparietal Diameter", "biparietal diameter"],
    description: "Fetal biparietal diameter (outer-to-inner table).",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Anomaly", "Growth", "BPP"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "\\bbpd\\b|biparietal" },
    comparisonStrategy: "absolute-change",
    refs: { usgColumns: ["bpd"], companionKeys: ["bpd"], knowledgePacks: ["Growth", "Anomaly"], reportTemplates: ["OBSTETRIC"] },
    version: V1,
    notes: "Stored in BOTH usg_measurements.bpd and fetal_usg_measurements.bpd (audit cluster #2).",
  },
  {
    id: "HC",
    canonicalKey: "meas.hc",
    displayName: "Head Circumference",
    aliases: ["HC", "hc", "Head Circumference", "Head circumference"],
    description: "Fetal head circumference.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Anomaly", "Growth"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "ellipse", dicomSrPattern: "\\bhc\\b|head circumference" },
    comparisonStrategy: "absolute-change",
    refs: { usgColumns: ["hc"], companionKeys: ["hc"], knowledgePacks: ["Growth", "Anomaly"], reportTemplates: ["OBSTETRIC"] },
    version: V1,
  },
  {
    id: "AC",
    canonicalKey: "meas.ac",
    displayName: "Abdominal Circumference",
    aliases: ["AC", "ac", "Abdominal Circumference", "Abdominal circumference"],
    description: "Fetal abdominal circumference.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Anomaly", "Growth"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "ellipse", dicomSrPattern: "\\bac\\b|abdominal circumference" },
    comparisonStrategy: "absolute-change",
    refs: { usgColumns: ["ac"], companionKeys: ["ac"], knowledgePacks: ["Growth", "Anomaly"], reportTemplates: ["OBSTETRIC"] },
    version: V1,
  },
  {
    id: "FL",
    canonicalKey: "meas.fl",
    displayName: "Femur Length",
    aliases: ["FL", "fl", "Femur Length", "Femur length"],
    description: "Fetal femur diaphysis length.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Anomaly", "Growth"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "\\bfl\\b|femur" },
    comparisonStrategy: "absolute-change",
    refs: { usgColumns: ["fl"], companionKeys: ["fl"], knowledgePacks: ["Growth", "Anomaly"], reportTemplates: ["OBSTETRIC"] },
    version: V1,
  },
  {
    id: "HL",
    canonicalKey: "meas.hl",
    displayName: "Humerus Length",
    aliases: ["HL", "hl", "Humerus Length", "Humerus length"],
    description: "Fetal humerus diaphysis length.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Anomaly"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "\\bhl\\b|humerus" },
    comparisonStrategy: "absolute-change",
    refs: { usgColumns: ["hl"] },
    version: V1,
  },
  {
    id: "EFW",
    canonicalKey: "meas.efw",
    displayName: "Estimated Fetal Weight",
    aliases: ["EFW", "efw", "Estimated Fetal Weight", "Estimated fetal weight"],
    description: "Estimated fetal weight (Hadlock or as configured).",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Growth", "Anomaly", "BPP"],
    defaultUnit: "g",
    allowedUnits: ["g", "kg"],
    precision: 0,
    viewerMapping: { tool: "none", dicomSrPattern: "\\befw\\b|estimated fetal weight" },
    comparisonStrategy: "percent-change",
    refs: { usgColumns: ["efw"], companionKeys: ["efw"], copilotKeys: ["efw"], knowledgePacks: ["Growth"], reportTemplates: ["OBSTETRIC"] },
    version: V1,
  },
  {
    id: "AFI",
    canonicalKey: "meas.afi",
    displayName: "Amniotic Fluid Index",
    aliases: ["AFI", "afi", "AFI (Amniotic Fluid Index)", "Amniotic Fluid Index", "Liquor / AFI", "liquorAfi", "AFV", "Amniotic fluid"],
    description: "Sum of deepest vertical pockets in four quadrants.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Growth", "Anomaly", "BPP"],
    defaultUnit: "cm",
    allowedUnits: ["cm", "mm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "\\bafi\\b|amniotic|liquor" },
    comparisonStrategy: "absolute-change",
    normalRange: { low: 5, high: 24, note: "< 5 oligohydramnios, > 24 polyhydramnios (structured-rule thresholds; legacy sources also carried 8-18 and 5-25)" },
    refs: { usgColumns: ["liquorAfi", "afi"], companionKeys: ["liquorAfi"], copilotKeys: ["afi"], qualityRules: ["care.measurement.range.afi"] },
    version: V1,
    notes: "Three divergent legacy ranges unified (audit cluster #6).",
  },
  {
    id: "DVP",
    canonicalKey: "meas.dvp",
    displayName: "Deepest Vertical Pocket",
    aliases: ["DVP", "SDP", "sdp", "Deepest Vertical Pocket", "Single deepest pocket", "Max vertical pocket", "MVP"],
    description: "Single deepest vertical amniotic fluid pocket.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["BPP", "Growth"],
    defaultUnit: "cm",
    allowedUnits: ["cm", "mm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "deepest|\\bsdp\\b|\\bdvp\\b" },
    comparisonStrategy: "absolute-change",
    normalRange: { low: 2, high: 8 },
    refs: { usgColumns: ["sdp"] },
    version: V1,
  },
  {
    id: "FHR",
    canonicalKey: "meas.fhr",
    displayName: "Fetal Heart Rate",
    aliases: ["FHR", "fhr", "Fetal Heart Rate", "Fetal heart rate", "fetalHeartRate"],
    description: "Fetal heart rate.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Early Pregnancy", "Anomaly", "Growth", "BPP"],
    defaultUnit: "bpm",
    allowedUnits: ["bpm"],
    precision: 0,
    viewerMapping: { tool: "none", dicomSrPattern: "\\bfhr\\b|fetal heart" },
    comparisonStrategy: "absolute-change",
    normalRange: { low: 110, high: 160, note: "structured-rule fetal range" },
    refs: { usgColumns: ["fhr", "fetalHeartRate"], companionKeys: ["fhr"], qualityRules: ["care.measurement.range.fhr"] },
    version: V1,
  },
  {
    id: "CERVICAL_LENGTH",
    canonicalKey: "meas.cervical_length",
    displayName: "Cervical Length",
    aliases: ["Cervical Length", "Cervical length", "cervicalLength", "cervical_length", "ob-cervix", "CL"],
    description: "Transvaginal cervical length.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["TVS", "Anomaly", "Growth"],
    defaultUnit: "mm",
    allowedUnits: ["mm", "cm"],
    precision: 1,
    viewerMapping: { tool: "linear", dicomSrPattern: "cervi" },
    comparisonStrategy: "absolute-change",
    normalRange: { low: 25, note: "< 25 mm short cervix (structured-rule threshold)" },
    refs: { usgColumns: ["cervicalLength"], qualityRules: ["care.measurement.range.cervical-length"] },
    version: V1,
  },
  {
    id: "MCA_PI",
    canonicalKey: "meas.mca_pi",
    displayName: "MCA Pulsatility Index",
    aliases: ["MCA PI", "mcaPi", "mca_pi", "MCA-PI", "Middle cerebral artery PI"],
    description: "Fetal middle cerebral artery pulsatility index.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Doppler", "Growth"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio"],
    precision: 2,
    viewerMapping: { tool: "ratio", dicomSrPattern: "mca.*pi|middle cerebral" },
    comparisonStrategy: "ratio-trend",
    refs: { usgColumns: ["mcaPi"] },
    version: V1,
  },
  {
    id: "UA_PI",
    canonicalKey: "meas.ua_pi",
    displayName: "Umbilical Artery Pulsatility Index",
    aliases: ["UA PI", "umbilicalArteryPi", "ua_pi", "UA-PI", "Umbilical artery PI"],
    description: "Umbilical artery pulsatility index.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Doppler", "Growth"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio"],
    precision: 2,
    viewerMapping: { tool: "ratio", dicomSrPattern: "umbilical.*pi" },
    comparisonStrategy: "ratio-trend",
    refs: { usgColumns: ["umbilicalArteryPi"] },
    version: V1,
  },
  {
    id: "CPR",
    canonicalKey: "meas.cpr",
    displayName: "Cerebroplacental Ratio",
    aliases: ["CPR", "cpr", "Cerebroplacental Ratio", "Cerebro-placental ratio"],
    description: "MCA PI divided by UA PI.",
    modalities: ["US"],
    bodyRegion: "Obstetric",
    studyTypes: ["Doppler", "Growth"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio"],
    precision: 2,
    viewerMapping: { tool: "ratio" },
    comparisonStrategy: "ratio-trend",
    normalRange: { low: 1, note: "< 1.0 abnormal (redistribution)" },
    refs: { usgColumns: ["cpr"], qualityRules: ["care.measurement.range.cpr"] },
    version: V1,
    notes: "Auto-calc: MCA_PI / UA_PI.",
  },

  // ── Doppler (generic vascular) ────────────────────────────────────────────
  {
    id: "PSV",
    canonicalKey: "meas.psv",
    displayName: "Peak Systolic Velocity",
    aliases: ["PSV", "psv", "PSV (Peak Systolic Velocity)", "Peak Systolic Velocity", "Peak systolic velocity"],
    description: "Peak systolic velocity of the interrogated vessel.",
    modalities: ["US"],
    bodyRegion: "Vascular",
    studyTypes: ["Doppler"],
    defaultUnit: "cm/s",
    allowedUnits: ["cm/s", "mm/s"],
    precision: 1,
    viewerMapping: { tool: "none", dicomSrPattern: "\\bpsv\\b|peak systolic" },
    comparisonStrategy: "percent-change",
    refs: { usgColumns: ["psv"] },
    version: V1,
  },
  {
    id: "EDV",
    canonicalKey: "meas.edv",
    displayName: "End Diastolic Velocity",
    aliases: ["EDV", "edv", "End Diastolic Velocity", "End diastolic velocity"],
    description: "End-diastolic velocity of the interrogated vessel.",
    modalities: ["US"],
    bodyRegion: "Vascular",
    studyTypes: ["Doppler"],
    defaultUnit: "cm/s",
    allowedUnits: ["cm/s", "mm/s"],
    precision: 1,
    viewerMapping: { tool: "none", dicomSrPattern: "\\bedv\\b|end diastolic" },
    comparisonStrategy: "percent-change",
    refs: { usgColumns: ["edv"] },
    version: V1,
  },
  {
    id: "RI",
    canonicalKey: "meas.ri",
    displayName: "Resistive Index",
    aliases: ["RI", "ri", "Resistive Index", "Resistivity index", "Resistance index"],
    description: "(PSV - EDV) / PSV of the interrogated vessel.",
    modalities: ["US"],
    bodyRegion: "Vascular",
    studyTypes: ["Doppler"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio"],
    precision: 2,
    viewerMapping: { tool: "ratio", dicomSrPattern: "\\bri\\b|resistive" },
    comparisonStrategy: "ratio-trend",
    refs: { usgColumns: ["ri"] },
    version: V1,
  },
  {
    id: "PI",
    canonicalKey: "meas.pi",
    displayName: "Pulsatility Index",
    aliases: ["PI", "pi", "Pulsatility Index", "Pulsatility index"],
    description: "(PSV - EDV) / mean velocity of the interrogated vessel.",
    modalities: ["US"],
    bodyRegion: "Vascular",
    studyTypes: ["Doppler"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio"],
    precision: 2,
    viewerMapping: { tool: "ratio", dicomSrPattern: "pulsatility" },
    comparisonStrategy: "ratio-trend",
    refs: { usgColumns: ["pi"] },
    version: V1,
  },
  {
    id: "SD_RATIO",
    canonicalKey: "meas.sd_ratio",
    displayName: "S/D Ratio",
    aliases: ["S/D Ratio", "S/D ratio", "sdRatio", "sd_ratio", "SD ratio", "Systolic/diastolic ratio"],
    description: "Systolic-to-diastolic velocity ratio of the interrogated vessel.",
    modalities: ["US"],
    bodyRegion: "Vascular",
    studyTypes: ["Doppler"],
    defaultUnit: "ratio",
    allowedUnits: ["ratio"],
    precision: 2,
    viewerMapping: { tool: "ratio", dicomSrPattern: "s/d" },
    comparisonStrategy: "ratio-trend",
    refs: { usgColumns: ["sdRatio", "umbilicalArterySd"] },
    version: V1,
  },
] as const;
