/**
 * AI Clinical Workflow routes — Phase P3 / Gates G10/G11.
 * Mounted at /api/ai (staff-auth required upstream).
 *
 * EVERY endpoint is gated: the master flag (ff_radiology_ai) plus per-scope
 * policy resolution decide enablement, default OFF. Radiologist-facing reads
 * require `visibleToRadiologist` (pilot/production). Admin surfaces require a
 * full-access role. This router NEVER signs or writes a report.
 */
import { Router, type Request } from "express";
import { z } from "zod/v4";
import { FULL_ACCESS_ROLES, type StaffAuthRequest } from "../middleware/requireStaffAuth";
import {
  resolveAiEnablementForUser, getPreferences, savePreferences, getSchedulerConfig, saveSchedulerConfig,
  getModalityPolicies, setModalityPolicy, setOvernightModalities, saveDraftAutomation, listFeaturePolicies, setFeaturePolicy,
} from "../lib/ai/clinicalConfigService";
import { scheduleStudy, getAiQueueDashboard, cancelAiJob, runNightBatch, runScheduledReprocessing, runLearningAggregation, previewNightBatch, getOvernightDiagnostics, queueSelectedStudies, cancelQueuedOvernightJobs, retryOvernightJobs } from "../lib/ai/schedulerService";
import { getLatestDraftForStudy, recordDraftFeedback } from "../lib/ai/draftService";

export const aiClinicalRouter = Router();

function staff(req: Request) {
  return (req as StaffAuthRequest).staffSession ?? null;
}
function isAdmin(req: Request): boolean {
  const s = staff(req);
  return !!s && FULL_ACCESS_ROLES.has(s.role);
}

// ── Enablement + preferences (any authenticated staff) ──────────────────────
aiClinicalRouter.get("/policy", async (req, res) => {
  const s = staff(req);
  const modality = typeof req.query.modality === "string" ? req.query.modality : null;
  const studyType = typeof req.query.studyType === "string" ? req.query.studyType : null;
  const enablement = await resolveAiEnablementForUser({ staffId: s?.id ?? null, modality, studyType });
  res.json(enablement);
});

aiClinicalRouter.get("/preferences", async (req, res) => {
  const s = staff(req);
  if (!s) { res.status(401).json({ error: "auth required" }); return; }
  res.json(await getPreferences(s.id));
});

aiClinicalRouter.put("/preferences", async (req, res) => {
  const s = staff(req);
  if (!s) { res.status(401).json({ error: "auth required" }); return; }
  const parsed = z.object({
    autoGenerateDraft: z.boolean().optional(),
    autoOpenDraft: z.boolean().optional(),
    preferredReportStyle: z.string().optional(),
    showConfidenceBadges: z.boolean().optional(),
    showEvidenceThumbnails: z.boolean().optional(),
    autoCompareWithPrior: z.boolean().optional(),
    autoLoadMeasurements: z.boolean().optional(),
    preferredLanguage: z.string().optional(),
    structuredReportingPreference: z.boolean().optional(),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  await savePreferences(s.id, parsed.data);
  res.json({ ok: true });
});

// ── Draft read + on-demand generate + feedback (gated by visibility) ────────
aiClinicalRouter.get("/draft", async (req, res) => {
  const s = staff(req);
  const studyInstanceUid = typeof req.query.studyInstanceUid === "string" ? req.query.studyInstanceUid : "";
  const modality = typeof req.query.modality === "string" ? req.query.modality : null;
  if (!studyInstanceUid) { res.status(400).json({ error: "studyInstanceUid required" }); return; }
  const enablement = await resolveAiEnablementForUser({ staffId: s?.id ?? null, modality });
  if (!enablement.visibleToRadiologist) { res.status(204).end(); return; } // AI off for this user — show nothing
  const draft = await getLatestDraftForStudy(studyInstanceUid);
  if (!draft) { res.status(204).end(); return; }
  res.json(draft);
});

aiClinicalRouter.post("/generate", async (req, res) => {
  const s = staff(req);
  const parsed = z.object({ studyInstanceUid: z.string().min(1), modality: z.string().optional() }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  const enablement = await resolveAiEnablementForUser({ staffId: s?.id ?? null, modality: parsed.data.modality ?? null });
  if (!enablement.enabled) { res.status(403).json({ error: "AI is not enabled for this context" }); return; }
  // Server-side modality gate — CT/XR/etc. must not enter when only MRI is enabled,
  // even if the client crafts a manual generate request.
  const { getModalityMode } = await import("../lib/ai/clinicalConfigService");
  const mode = await getModalityMode(parsed.data.modality ?? null);
  if (mode === "disabled") {
    res.status(403).json({ error: "AI drafting is disabled for this modality", modality: parsed.data.modality ?? null, mode });
    return;
  }
  const result = await scheduleStudy({ studyInstanceUid: parsed.data.studyInstanceUid, modality: parsed.data.modality ?? null, manualRequest: true });
  res.json(result);
});

aiClinicalRouter.post("/draft/:id/feedback", async (req, res) => {
  const s = staff(req);
  const draftId = Number(req.params.id);
  const parsed = z.object({
    studyInstanceUid: z.string().min(1),
    findingKey: z.string().optional(),
    action: z.enum(["accept", "edit", "ignore", "reject"]),
    editedText: z.string().optional(),
    // P4 / G21 — optional structured feedback dataset fields (analytics only).
    reason: z.string().optional(),
    laterality: z.string().optional(),
    measurementRef: z.string().optional(),
    confidence: z.number().int().optional(),
    promptVersion: z.string().optional(),
    modelVersion: z.string().optional(),
  }).safeParse(req.body);
  if (!Number.isInteger(draftId) || !parsed.success) { res.status(400).json({ error: parsed.success ? "bad id" : parsed.error.issues }); return; }
  await recordDraftFeedback({ draftId, staffId: s?.id ?? null, ...parsed.data });
  res.json({ ok: true });
});

// ── Admin: scheduler config, modality policies, feature policies, queue ─────
function requireAdmin(req: Request, res: import("express").Response): boolean {
  if (!isAdmin(req)) { res.status(403).json({ error: "admin role required" }); return false; }
  return true;
}

aiClinicalRouter.get("/scheduler/config", async (req, res) => { if (!requireAdmin(req, res)) return; res.json(await getSchedulerConfig()); });
aiClinicalRouter.put("/scheduler/config", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const parsed = z.object({
    draftTiming: z.enum(["on_arrival", "scheduled"]).optional(),
    nightStart: z.string().optional(), nightEnd: z.string().optional(), quietStart: z.string().optional(), quietEnd: z.string().optional(),
    gpuLimitPercent: z.number().int().optional(), cpuLimitPercent: z.number().int().optional(), maxConcurrentJobs: z.number().int().optional(),
    maxRetries: z.number().int().optional(), includePriors: z.boolean().optional(), includeOcr: z.boolean().optional(),
    skipFinalizedReports: z.boolean().optional(), skipUnchangedStudies: z.boolean().optional(),
    studyAgeWindow: z.enum(["all", "today", "last_24h", "last_48h", "last_3d", "last_7d", "custom"]).optional(),
    studyAgeCustomFrom: z.string().nullable().optional(),
    studyAgeCustomTo: z.string().nullable().optional(),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  const { studyAgeCustomFrom, studyAgeCustomTo, ...rest } = parsed.data;
  await saveSchedulerConfig({
    ...rest,
    studyAgeCustomFrom: studyAgeCustomFrom === undefined ? undefined : studyAgeCustomFrom === null ? null : new Date(studyAgeCustomFrom),
    studyAgeCustomTo: studyAgeCustomTo === undefined ? undefined : studyAgeCustomTo === null ? null : new Date(studyAgeCustomTo),
  }, staff(req)?.role);
  res.json({ ok: true, config: await getSchedulerConfig() });
});

/** Overnight vision ops — pause / safe mode / image cap / vision ctx (no Docker redeploy). */
aiClinicalRouter.get("/overnight-ops", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const { getOvernightOpsControls } = await import("../lib/ai/clinicalConfigService");
  const { getOvernightVisionInferenceOptions } = await import("../lib/ai/overnightVisionConfig");
  const { countLegacyBacklogHold } = await import("../lib/ai/legacyBacklogHold");
  const ops = await getOvernightOpsControls();
  const vision = await getOvernightVisionInferenceOptions(true);
  const legacyBacklog = await countLegacyBacklogHold(ops);
  res.json({
    ops,
    effectivePolicy: {
      model: vision.policy.model,
      endpointUrl: vision.policy.endpointUrl,
      numCtx: vision.policy.numCtx,
      numCtxSource: vision.policy.numCtxSource,
      maxImages: vision.policy.maxImages,
      imageCapReason: vision.policy.imageCapReason,
      safeMode: vision.policy.safeMode,
      overnightPaused: vision.policy.overnightPaused,
      pauseReason: vision.policy.pauseReason,
      configuredNumCtx: vision.policy.configuredNumCtx,
      reason: vision.policy.reason,
    },
    legacyBacklog,
    backlogNote:
      "Deploy does NOT auto-retry abandoned ai_shadow_pipeline jobs. Abandoned stay abandoned. " +
      "Legacy backlog hold (auto-on at cutover) blocks pre-cutover pending/retrying from auto-claim; " +
      "post-cutover jobs may drain. Explicit canary/retry by jobId bypasses hold. " +
      "Release all legacy backlog requires explicit confirmation — never automatic.",
  });
});

aiClinicalRouter.put("/overnight-ops", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const parsed = z.object({
    paused: z.boolean().optional(),
    pauseReason: z.string().nullable().optional(),
    imageCap: z.enum(["auto", "1", "2", "3", "4", "6"]).optional(),
    visionCtx: z.enum(["current", "4096", "8192", "16384"]).optional(),
    safeMode: z.boolean().optional(),
    /** Clear resource-fail streak when resuming. */
    clearResourceStreak: z.boolean().optional(),
    /** Re-enable hold only (turning hold OFF requires POST .../legacy-backlog release_all + confirm). */
    legacyBacklogHold: z.literal(true).optional(),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  const { saveOvernightOpsControls } = await import("../lib/ai/clinicalConfigService");
  const patch: Record<string, unknown> = { ...parsed.data };
  if (parsed.data.paused === false) {
    patch.pauseReason = null;
    if (parsed.data.clearResourceStreak !== false) {
      patch.resourceFailStreak = 0;
      patch.lastResourceFailCode = null;
    }
  }
  if (parsed.data.paused === true && !parsed.data.pauseReason) {
    patch.pauseReason = "OVERNIGHT AI PAUSED — operator";
  }
  delete patch.clearResourceStreak;
  const ops = await saveOvernightOpsControls(patch as Parameters<typeof saveOvernightOpsControls>[0], staff(req)?.role);
  console.log("[ai] overnight ops updated", JSON.stringify({ by: staff(req)?.role, ops }));
  res.json({ ok: true, ops });
});

/**
 * Legacy backlog hold actions — never deletes rows.
 * release_all requires confirm:true.
 */
aiClinicalRouter.post("/overnight-ops/legacy-backlog", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const parsed = z.discriminatedUnion("action", [
    z.object({
      action: z.literal("retry_selected"),
      jobIds: z.array(z.number().int().positive()).min(1).max(50),
    }),
    z.object({
      action: z.literal("release_selected"),
      jobIds: z.array(z.number().int().positive()).min(1).max(50),
    }),
    z.object({
      action: z.literal("release_recent"),
      limit: z.number().int().min(1).max(50).optional(),
    }),
    z.object({
      action: z.literal("release_all"),
      confirm: z.literal(true),
    }),
  ]).safeParse(req.body ?? {});
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  const by = staff(req)?.role;
  const {
    releaseLegacyBacklogSelected,
    releaseLegacyBacklogRecent,
    releaseAllLegacyBacklogHold,
  } = await import("../lib/ai/clinicalConfigService");
  const { countLegacyBacklogHold } = await import("../lib/ai/legacyBacklogHold");
  const { retryOvernightJobs } = await import("../lib/ai/overnightDraftQueue");

  if (parsed.data.action === "release_all") {
    const ops = await releaseAllLegacyBacklogHold(by);
    const legacyBacklog = await countLegacyBacklogHold(ops);
    console.log("[ai] legacy backlog released ALL", JSON.stringify({ by, holdBefore: ops.legacyHoldBefore }));
    res.json({ ok: true, action: "release_all", ops, legacyBacklog, deleted: 0 });
    return;
  }
  if (parsed.data.action === "release_recent") {
    const { ops, releasedJobIds } = await releaseLegacyBacklogRecent(parsed.data.limit ?? 5, by);
    const legacyBacklog = await countLegacyBacklogHold(ops);
    res.json({ ok: true, action: "release_recent", ops, releasedJobIds, legacyBacklog, deleted: 0 });
    return;
  }
  if (parsed.data.action === "release_selected") {
    const ops = await releaseLegacyBacklogSelected(parsed.data.jobIds, by);
    const legacyBacklog = await countLegacyBacklogHold(ops);
    res.json({
      ok: true,
      action: "release_selected",
      ops,
      releasedJobIds: parsed.data.jobIds,
      legacyBacklog,
      deleted: 0,
    });
    return;
  }
  // retry_selected: allowlist + mark retryable (bypass hold for those ids; no deletes)
  const ops = await releaseLegacyBacklogSelected(parsed.data.jobIds, by);
  const retry = await retryOvernightJobs(parsed.data.jobIds);
  const legacyBacklog = await countLegacyBacklogHold(ops);
  res.json({
    ok: true,
    action: "retry_selected",
    ops,
    releasedJobIds: parsed.data.jobIds,
    retry,
    legacyBacklog,
    deleted: 0,
  });
});

/** One-shot save from Settings → Radiology → AI → Draft automation. */
aiClinicalRouter.put("/draft-automation", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const parsed = z.object({
    draftTiming: z.enum(["on_arrival", "scheduled"]),
    modalities: z.array(z.string().min(1)),
    nightStart: z.string().optional(),
    nightEnd: z.string().optional(),
    quietStart: z.string().optional(),
    quietEnd: z.string().optional(),
    studyAgeWindow: z.enum(["all", "today", "last_24h", "last_48h", "last_3d", "last_7d", "custom"]).optional(),
    studyAgeCustomFrom: z.string().nullable().optional(),
    studyAgeCustomTo: z.string().nullable().optional(),
    enableAi: z.boolean().optional(),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  const result = await saveDraftAutomation({ ...parsed.data, updatedBy: staff(req)?.role });
  res.json({ ok: true, ...result });
});

aiClinicalRouter.get("/modality-policies", async (req, res) => { if (!requireAdmin(req, res)) return; res.json(await getModalityPolicies()); });
aiClinicalRouter.put("/modality-policies", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  // Batch overnight selection: { overnightModalities: ["MR","CT"], mode?: "night_batch" }
  const batch = z.object({
    overnightModalities: z.array(z.string().min(1)).min(0),
    mode: z.enum(["immediate", "night_batch", "manual", "disabled"]).optional(),
  }).safeParse(req.body);
  if (batch.success) {
    const policies = await setOvernightModalities(batch.data.overnightModalities, {
      mode: batch.data.mode ?? "night_batch",
      updatedBy: staff(req)?.role,
    });
    res.json({ ok: true, policies });
    return;
  }
  const parsed = z.object({ modality: z.string().min(1), mode: z.enum(["immediate", "night_batch", "manual", "disabled"]) }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  await setModalityPolicy(parsed.data.modality, parsed.data.mode, staff(req)?.role);
  res.json({ ok: true });
});

aiClinicalRouter.get("/policies", async (req, res) => { if (!requireAdmin(req, res)) return; res.json(await listFeaturePolicies()); });
aiClinicalRouter.put("/policies", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const parsed = z.object({
    scope: z.enum(["global", "hospital", "modality", "study_type", "radiologist"]),
    scopeKey: z.string().min(1), enabled: z.boolean(), mode: z.enum(["shadow", "pilot", "production"]),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  await setFeaturePolicy(parsed.data.scope, parsed.data.scopeKey, parsed.data.enabled, parsed.data.mode, staff(req)?.role);
  res.json({ ok: true });
});

aiClinicalRouter.get("/queue", async (req, res) => { if (!requireAdmin(req, res)) return; res.json(await getAiQueueDashboard()); });
aiClinicalRouter.get("/overnight-diagnostics", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  res.json(await getOvernightDiagnostics());
});
aiClinicalRouter.post("/overnight/canary", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const parsed = z.object({ jobId: z.number().int().optional() }).safeParse(req.body ?? {});
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  const { runOvernightAiCanary } = await import("../lib/ai/overnightCanary");
  res.json(await runOvernightAiCanary(parsed.data));
});
aiClinicalRouter.get("/scheduler/night-batch-preview", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  res.json(await previewNightBatch());
});
aiClinicalRouter.post("/overnight/queue-selected", async (req, res) => {
  const parsed = z.object({
    studyInstanceUids: z.array(z.string().min(1)).min(1).max(50),
    modalities: z.record(z.string(), z.string().nullable()).optional(),
    retry: z.boolean().optional(),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  res.json(await queueSelectedStudies(parsed.data));
});
aiClinicalRouter.post("/overnight/retry-jobs", async (req, res) => {
  const parsed = z.object({ jobIds: z.array(z.number().int()).min(1).max(50) }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  res.json(await retryOvernightJobs(parsed.data.jobIds));
});
aiClinicalRouter.post("/overnight/cancel-queued", async (req, res) => {
  const parsed = z.object({ jobIds: z.array(z.number().int()).min(1).max(50) }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  res.json(await cancelQueuedOvernightJobs(parsed.data.jobIds));
});
aiClinicalRouter.post("/jobs/:id/cancel", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const ok = await cancelAiJob(Number(req.params.id));
  res.status(ok ? 200 : 404).json({ ok });
});

aiClinicalRouter.post("/scheduler/run/:mode", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  switch (req.params.mode) {
    case "night-batch": {
      const force = req.query.force === "1" || req.body?.force === true;
      const onlyNew = req.query.onlyNew === "1" || req.body?.onlyNew === true;
      res.json(await runNightBatch(50, { forceOutsideWindow: force, onlyNew }));
      return;
    }
    case "reprocess": res.json(await runScheduledReprocessing()); return;
    case "learning": res.json(await runLearningAggregation()); return;
    default: res.status(400).json({ error: "unknown mode" });
  }
});
