/**
 * AI Clinical Workflow routes — Phase P3 / Gates G10/G11.
 * Mounted at /api/ai (staff-auth required upstream).
 *
 * EVERY endpoint is gated: the master flag (ff_radiology_ai) plus per-scope
 * policy resolution decide enablement, default OFF. Radiologist-facing reads
 * require `visibleToRadiologist` (pilot/production). Admin surfaces require a
 * full-access role. This router NEVER signs or writes a report.
 */
import { Router, type Request } from "express";
import { z } from "zod/v4";
import { FULL_ACCESS_ROLES, type StaffAuthRequest } from "../middleware/requireStaffAuth";
import {
  resolveAiEnablementForUser, getPreferences, savePreferences, getSchedulerConfig, saveSchedulerConfig,
  getModalityPolicies, setModalityPolicy, setOvernightModalities, saveDraftAutomation, listFeaturePolicies, setFeaturePolicy,
} from "../lib/ai/clinicalConfigService";
import { scheduleStudy, getAiQueueDashboard, cancelAiJob, runNightBatch, runScheduledReprocessing, runLearningAggregation } from "../lib/ai/schedulerService";
import { getLatestDraftForStudy, recordDraftFeedback } from "../lib/ai/draftService";

export const aiClinicalRouter = Router();

function staff(req: Request) {
  return (req as StaffAuthRequest).staffSession ?? null;
}
function isAdmin(req: Request): boolean {
  const s = staff(req);
  return !!s && FULL_ACCESS_ROLES.has(s.role);
}

// ── Enablement + preferences (any authenticated staff) ──────────────────────
aiClinicalRouter.get("/policy", async (req, res) => {
  const s = staff(req);
  const modality = typeof req.query.modality === "string" ? req.query.modality : null;
  const studyType = typeof req.query.studyType === "string" ? req.query.studyType : null;
  const enablement = await resolveAiEnablementForUser({ staffId: s?.id ?? null, modality, studyType });
  res.json(enablement);
});

aiClinicalRouter.get("/preferences", async (req, res) => {
  const s = staff(req);
  if (!s) { res.status(401).json({ error: "auth required" }); return; }
  res.json(await getPreferences(s.id));
});

aiClinicalRouter.put("/preferences", async (req, res) => {
  const s = staff(req);
  if (!s) { res.status(401).json({ error: "auth required" }); return; }
  const parsed = z.object({
    autoGenerateDraft: z.boolean().optional(),
    autoOpenDraft: z.boolean().optional(),
    preferredReportStyle: z.string().optional(),
    showConfidenceBadges: z.boolean().optional(),
    showEvidenceThumbnails: z.boolean().optional(),
    autoCompareWithPrior: z.boolean().optional(),
    autoLoadMeasurements: z.boolean().optional(),
    preferredLanguage: z.string().optional(),
    structuredReportingPreference: z.boolean().optional(),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  await savePreferences(s.id, parsed.data);
  res.json({ ok: true });
});

// ── Draft read + on-demand generate + feedback (gated by visibility) ────────
aiClinicalRouter.get("/draft", async (req, res) => {
  const s = staff(req);
  const studyInstanceUid = typeof req.query.studyInstanceUid === "string" ? req.query.studyInstanceUid : "";
  const modality = typeof req.query.modality === "string" ? req.query.modality : null;
  if (!studyInstanceUid) { res.status(400).json({ error: "studyInstanceUid required" }); return; }
  const enablement = await resolveAiEnablementForUser({ staffId: s?.id ?? null, modality });
  if (!enablement.visibleToRadiologist) { res.status(204).end(); return; } // AI off for this user — show nothing
  const draft = await getLatestDraftForStudy(studyInstanceUid);
  if (!draft) { res.status(204).end(); return; }
  res.json(draft);
});

aiClinicalRouter.post("/generate", async (req, res) => {
  const s = staff(req);
  const parsed = z.object({ studyInstanceUid: z.string().min(1), modality: z.string().optional() }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  const enablement = await resolveAiEnablementForUser({ staffId: s?.id ?? null, modality: parsed.data.modality ?? null });
  if (!enablement.enabled) { res.status(403).json({ error: "AI is not enabled for this context" }); return; }
  // Server-side modality gate — CT/XR/etc. must not enter when only MRI is enabled,
  // even if the client crafts a manual generate request.
  const { getModalityMode } = await import("../lib/ai/clinicalConfigService");
  const mode = await getModalityMode(parsed.data.modality ?? null);
  if (mode === "disabled") {
    res.status(403).json({ error: "AI drafting is disabled for this modality", modality: parsed.data.modality ?? null, mode });
    return;
  }
  const result = await scheduleStudy({ studyInstanceUid: parsed.data.studyInstanceUid, modality: parsed.data.modality ?? null, manualRequest: true });
  res.json(result);
});

aiClinicalRouter.post("/draft/:id/feedback", async (req, res) => {
  const s = staff(req);
  const draftId = Number(req.params.id);
  const parsed = z.object({
    studyInstanceUid: z.string().min(1),
    findingKey: z.string().optional(),
    action: z.enum(["accept", "edit", "ignore", "reject"]),
    editedText: z.string().optional(),
    // P4 / G21 — optional structured feedback dataset fields (analytics only).
    reason: z.string().optional(),
    laterality: z.string().optional(),
    measurementRef: z.string().optional(),
    confidence: z.number().int().optional(),
    promptVersion: z.string().optional(),
    modelVersion: z.string().optional(),
  }).safeParse(req.body);
  if (!Number.isInteger(draftId) || !parsed.success) { res.status(400).json({ error: parsed.success ? "bad id" : parsed.error.issues }); return; }
  await recordDraftFeedback({ draftId, staffId: s?.id ?? null, ...parsed.data });
  res.json({ ok: true });
});

// ── Admin: scheduler config, modality policies, feature policies, queue ─────
function requireAdmin(req: Request, res: import("express").Response): boolean {
  if (!isAdmin(req)) { res.status(403).json({ error: "admin role required" }); return false; }
  return true;
}

aiClinicalRouter.get("/scheduler/config", async (req, res) => { if (!requireAdmin(req, res)) return; res.json(await getSchedulerConfig()); });
aiClinicalRouter.put("/scheduler/config", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const parsed = z.object({
    draftTiming: z.enum(["on_arrival", "scheduled"]).optional(),
    nightStart: z.string().optional(), nightEnd: z.string().optional(), quietStart: z.string().optional(), quietEnd: z.string().optional(),
    gpuLimitPercent: z.number().int().optional(), cpuLimitPercent: z.number().int().optional(), maxConcurrentJobs: z.number().int().optional(),
    maxRetries: z.number().int().optional(), includePriors: z.boolean().optional(), includeOcr: z.boolean().optional(),
    skipFinalizedReports: z.boolean().optional(), skipUnchangedStudies: z.boolean().optional(),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  await saveSchedulerConfig(parsed.data, staff(req)?.role);
  res.json({ ok: true, config: await getSchedulerConfig() });
});

/** One-shot save from Settings → Radiology → AI → Draft automation. */
aiClinicalRouter.put("/draft-automation", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const parsed = z.object({
    draftTiming: z.enum(["on_arrival", "scheduled"]),
    modalities: z.array(z.string().min(1)),
    nightStart: z.string().optional(),
    nightEnd: z.string().optional(),
    quietStart: z.string().optional(),
    quietEnd: z.string().optional(),
    enableAi: z.boolean().optional(),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  const result = await saveDraftAutomation({ ...parsed.data, updatedBy: staff(req)?.role });
  res.json({ ok: true, ...result });
});

aiClinicalRouter.get("/modality-policies", async (req, res) => { if (!requireAdmin(req, res)) return; res.json(await getModalityPolicies()); });
aiClinicalRouter.put("/modality-policies", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  // Batch overnight selection: { overnightModalities: ["MR","CT"], mode?: "night_batch" }
  const batch = z.object({
    overnightModalities: z.array(z.string().min(1)).min(0),
    mode: z.enum(["immediate", "night_batch", "manual", "disabled"]).optional(),
  }).safeParse(req.body);
  if (batch.success) {
    const policies = await setOvernightModalities(batch.data.overnightModalities, {
      mode: batch.data.mode ?? "night_batch",
      updatedBy: staff(req)?.role,
    });
    res.json({ ok: true, policies });
    return;
  }
  const parsed = z.object({ modality: z.string().min(1), mode: z.enum(["immediate", "night_batch", "manual", "disabled"]) }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  await setModalityPolicy(parsed.data.modality, parsed.data.mode, staff(req)?.role);
  res.json({ ok: true });
});

aiClinicalRouter.get("/policies", async (req, res) => { if (!requireAdmin(req, res)) return; res.json(await listFeaturePolicies()); });
aiClinicalRouter.put("/policies", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const parsed = z.object({
    scope: z.enum(["global", "hospital", "modality", "study_type", "radiologist"]),
    scopeKey: z.string().min(1), enabled: z.boolean(), mode: z.enum(["shadow", "pilot", "production"]),
  }).safeParse(req.body);
  if (!parsed.success) { res.status(400).json({ error: parsed.error.issues }); return; }
  await setFeaturePolicy(parsed.data.scope, parsed.data.scopeKey, parsed.data.enabled, parsed.data.mode, staff(req)?.role);
  res.json({ ok: true });
});

aiClinicalRouter.get("/queue", async (req, res) => { if (!requireAdmin(req, res)) return; res.json(await getAiQueueDashboard()); });
aiClinicalRouter.post("/jobs/:id/cancel", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  const ok = await cancelAiJob(Number(req.params.id));
  res.status(ok ? 200 : 404).json({ ok });
});

aiClinicalRouter.post("/scheduler/run/:mode", async (req, res) => {
  if (!requireAdmin(req, res)) return;
  switch (req.params.mode) {
    case "night-batch": {
      const force = req.query.force === "1" || req.body?.force === true;
      res.json(await runNightBatch(50, { forceOutsideWindow: force }));
      return;
    }
    case "reprocess": res.json(await runScheduledReprocessing()); return;
    case "learning": res.json(await runLearningAggregation()); return;
    default: res.status(400).json({ error: "unknown mode" });
  }
});
