/**
 * AI Settings Panel — Phase P3 / Gates G10/G11.
 *
 * Self-contained settings surface: radiologist preferences (any user), and —
 * for admins — the scheduler config, per-modality policies, and enablement
 * (enable a single pilot radiologist / a modality). All writes go to the gated
 * /api/ai admin endpoints. Safe to embed in an existing settings page.
 */
import { useEffect, useState } from "react";
import { aiClient, type AiPreferences } from "../../lib/aiClient";

const MODALITIES = ["MR", "CT", "CR", "US", "MG", "Doppler"];
const MODALITY_MODES = ["immediate", "night_batch", "manual", "disabled"];

export function AiSettingsPanel({ isAdmin = false }: { isAdmin?: boolean }) {
  const [prefs, setPrefs] = useState<AiPreferences | null>(null);
  const [modalityPolicies, setModalityPolicies] = useState<Array<{ modality: string; mode: string }>>([]);
  const [scheduler, setScheduler] = useState<Record<string, unknown>>({});
  const [pilotStaffId, setPilotStaffId] = useState("");
  const [msg, setMsg] = useState("");

  useEffect(() => {
    aiClient.getPreferences().then((p) => setPrefs(p ?? defaultPrefs())).catch(() => setPrefs(defaultPrefs()));
    if (isAdmin) {
      aiClient.getModalityPolicies().then(setModalityPolicies).catch(() => setModalityPolicies([]));
      aiClient.getSchedulerConfig().then(setScheduler).catch(() => setScheduler({}));
    }
  }, [isAdmin]);

  const flash = (m: string) => { setMsg(m); setTimeout(() => setMsg(""), 2000); };
  const savePrefs = async (patch: Partial<AiPreferences>) => {
    const next = { ...(prefs ?? defaultPrefs()), ...patch };
    setPrefs(next);
    await aiClient.savePreferences(patch).catch(() => {});
    flash("Preferences saved");
  };

  return (
    <div className="space-y-6 text-sm">
      {msg && <div className="rounded bg-emerald-50 px-3 py-1 text-emerald-700">{msg}</div>}

      <section>
        <h3 className="mb-2 font-semibold">My AI preferences</h3>
        {prefs && (
          <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
            {([
              ["autoGenerateDraft", "Auto-generate AI draft"],
              ["autoOpenDraft", "Auto-open AI draft"],
              ["showConfidenceBadges", "Show confidence badges"],
              ["showEvidenceThumbnails", "Show evidence thumbnails"],
              ["autoCompareWithPrior", "Auto-compare with prior"],
              ["autoLoadMeasurements", "Auto-load measurements"],
              ["structuredReportingPreference", "Prefer structured reporting"],
            ] as Array<[keyof AiPreferences, string]>).map(([key, label]) => (
              <label key={key} className="flex items-center gap-2">
                <input type="checkbox" checked={Boolean(prefs[key])} onChange={(e) => savePrefs({ [key]: e.target.checked } as Partial<AiPreferences>)} />
                {label}
              </label>
            ))}
            <label className="flex items-center gap-2">
              Report style
              <select value={prefs.preferredReportStyle} onChange={(e) => savePrefs({ preferredReportStyle: e.target.value })} className="rounded border px-1">
                <option value="structured">Structured</option>
                <option value="prose">Prose</option>
              </select>
            </label>
            <label className="flex items-center gap-2">
              Language
              <input value={prefs.preferredLanguage} onChange={(e) => savePrefs({ preferredLanguage: e.target.value })} className="w-16 rounded border px-1" />
            </label>
          </div>
        )}
      </section>

      {isAdmin && (
        <>
          <section>
            <h3 className="mb-2 font-semibold">Modality policies</h3>
            <div className="space-y-1">
              {MODALITIES.map((m) => {
                const current = modalityPolicies.find((p) => p.modality === m)?.mode ?? "disabled";
                return (
                  <div key={m} className="flex items-center gap-2">
                    <span className="w-20">{m}</span>
                    <select
                      value={current}
                      onChange={async (e) => { await aiClient.setModalityPolicy(m, e.target.value); setModalityPolicies((prev) => [...prev.filter((p) => p.modality !== m), { modality: m, mode: e.target.value }]); flash(`${m} → ${e.target.value}`); }}
                      className="rounded border px-1"
                    >
                      {MODALITY_MODES.map((mode) => <option key={mode} value={mode}>{mode}</option>)}
                    </select>
                  </div>
                );
              })}
            </div>
          </section>

          <section>
            <h3 className="mb-2 font-semibold">Enable a pilot radiologist</h3>
            <div className="flex items-center gap-2">
              <input placeholder="staff id" value={pilotStaffId} onChange={(e) => setPilotStaffId(e.target.value)} className="w-28 rounded border px-2 py-1" />
              <button
                className="rounded bg-indigo-600 px-3 py-1 text-white"
                onClick={async () => { if (!pilotStaffId) return; await aiClient.setPolicy({ scope: "radiologist", scopeKey: pilotStaffId, enabled: true, mode: "pilot" }); flash(`Pilot enabled for staff ${pilotStaffId}`); }}
              >Enable pilot</button>
            </div>
            <p className="mt-1 text-xs text-neutral-500">Requires the global master flag <code>ff_radiology_ai</code> to be ON. Default: AI is OFF for everyone.</p>
          </section>

          <section>
            <h3 className="mb-2 font-semibold">Scheduler</h3>
            <div className="grid grid-cols-2 gap-2">
              {[["nightStart", "Night start"], ["nightEnd", "Night end"], ["quietStart", "Quiet start"], ["quietEnd", "Quiet end"]].map(([k, label]) => (
                <label key={k} className="flex items-center justify-between gap-2">
                  {label}
                  <input
                    value={String(scheduler[k] ?? "")}
                    onChange={(e) => setScheduler((s) => ({ ...s, [k]: e.target.value }))}
                    onBlur={async () => { await aiClient.saveSchedulerConfig({ [k]: scheduler[k] }); flash("Scheduler saved"); }}
                    className="w-20 rounded border px-1"
                  />
                </label>
              ))}
            </div>
          </section>
        </>
      )}
    </div>
  );
}

function defaultPrefs(): AiPreferences {
  return {
    autoGenerateDraft: false, autoOpenDraft: false, preferredReportStyle: "structured",
    showConfidenceBadges: true, showEvidenceThumbnails: true, autoCompareWithPrior: true,
    autoLoadMeasurements: true, preferredLanguage: "en", structuredReportingPreference: true,
  };
}
