/**
 * Display helpers for Report Composer — keep job status READY for review/apply,
 * but surface deterministic fallback distinctly from true Ollama proposals.
 */

export const DETERMINISTIC_FALLBACK_WARNING =
  "Local AI was not used. This draft was generated by deterministic fallback.";

export function isDeterministicComposeFallback(opts: {
  fallbackUsed?: boolean | null;
  model?: string | null;
  provider?: string | null;
  warnings?: string[] | null;
}): boolean {
  if (opts.fallbackUsed === true) return true;
  if ((opts.model ?? "").trim().toLowerCase() === "deterministic") return true;
  if ((opts.provider ?? "").trim().toLowerCase() === "deterministic") return true;
  if (Array.isArray(opts.warnings) && opts.warnings.includes("deterministic_fallback")) return true;
  return false;
}

export type ComposeDisplayStatus = "AI_READY" | "FALLBACK_DRAFT" | "OTHER";

export function resolveComposeDisplayStatus(opts: {
  status?: string | null;
  fallbackUsed?: boolean | null;
  model?: string | null;
  provider?: string | null;
  warnings?: string[] | null;
}): ComposeDisplayStatus {
  const fallback = isDeterministicComposeFallback(opts);
  if (fallback) return "FALLBACK_DRAFT";
  if (opts.status === "READY" || opts.model) return "AI_READY";
  return "OTHER";
}

export function composerRuntimeStatusMessage(runtime: {
  enabled: boolean;
  model: string;
  ollamaEnabled?: boolean;
}): string | null {
  const model = (runtime.model ?? "").trim();
  if (!model) return "Report Composer model not configured";
  if (!runtime.enabled) return "Report Composer disabled (Local AI off or composer model missing)";
  return null;
}
