/**
 * Display helpers for Report Composer — READY jobs from deterministic fallback
 * must not be labeled as AI READY.
 */

export const DETERMINISTIC_FALLBACK_USER_MESSAGE =
  "Local AI was not used. This draft was generated by deterministic fallback.";

export function isDeterministicComposeFallback(opts: {
  fallbackUsed?: boolean | null;
  model?: string | null;
  provider?: string | null;
  warnings?: string[] | null;
}): boolean {
  if (opts.fallbackUsed === true) return true;
  if ((opts.model ?? "").trim().toLowerCase() === "deterministic") return true;
  if ((opts.provider ?? "").trim().toLowerCase() === "deterministic") return true;
  if (Array.isArray(opts.warnings) && opts.warnings.includes("deterministic_fallback")) return true;
  return false;
}

export type ComposeDisplayStatus = "LOCAL_AI_SUCCESS" | "FALLBACK_DRAFT" | "FAILED" | "OTHER";

export function resolveComposeDisplayStatus(opts: {
  ok?: boolean;
  fallbackUsed?: boolean | null;
  model?: string | null;
  provider?: string | null;
  warnings?: string[] | null;
}): ComposeDisplayStatus {
  if (opts.ok === false) return "FAILED";
  if (isDeterministicComposeFallback(opts)) return "FALLBACK_DRAFT";
  if (opts.ok === true && (opts.model ?? "").trim() && (opts.model ?? "").toLowerCase() !== "deterministic") {
    return "LOCAL_AI_SUCCESS";
  }
  return "OTHER";
}

export function composerRuntimeStatusMessage(runtime: {
  enabled: boolean;
  model: string;
}): string | null {
  const model = (runtime.model ?? "").trim();
  if (!model) return "Report Composer model not configured";
  if (!runtime.enabled) return "Report Composer disabled (Local AI off or composer model missing)";
  return null;
}
