/**
 * Display helpers for Report Composer.
 * Job status may stay READY for review/apply, but deterministic fallback must
 * never be labeled as AI READY / LOCAL AI SUCCESS.
 */

/** Canonical user-facing copy (also mirrored on the ERP client). */
export const DETERMINISTIC_FALLBACK_WARNING =
  "Local AI was not used. This draft was generated by deterministic fallback.";

/** Alias used by Report Composer Test responses. */
export const DETERMINISTIC_FALLBACK_USER_MESSAGE = DETERMINISTIC_FALLBACK_WARNING;

export function isDeterministicComposeFallback(opts: {
  fallbackUsed?: boolean | null;
  model?: string | null;
  provider?: string | null;
  warnings?: string[] | null;
}): boolean {
  if (opts.fallbackUsed === true) return true;
  if ((opts.model ?? "").trim().toLowerCase() === "deterministic") return true;
  if ((opts.provider ?? "").trim().toLowerCase() === "deterministic") return true;
  if (Array.isArray(opts.warnings) && opts.warnings.includes("deterministic_fallback")) return true;
  return false;
}

/**
 * - LOCAL_AI_SUCCESS: real Ollama compose (Report Composer Test path, ok=true)
 * - AI_READY: job/review path when status is READY and not fallback (#707)
 * - FALLBACK_DRAFT: deterministic offline draft
 * - FAILED: explicit compose failure (ok=false)
 */
export type ComposeDisplayStatus =
  | "LOCAL_AI_SUCCESS"
  | "CLOUD_AI_SUCCESS"
  | "AI_READY"
  | "FALLBACK_DRAFT"
  | "FAILED"
  | "OTHER";

export function resolveComposeDisplayStatus(opts: {
  ok?: boolean;
  status?: string | null;
  fallbackUsed?: boolean | null;
  model?: string | null;
  provider?: string | null;
  warnings?: string[] | null;
}): ComposeDisplayStatus {
  if (opts.ok === false) return "FAILED";
  if (isDeterministicComposeFallback(opts)) return "FALLBACK_DRAFT";

  const model = (opts.model ?? "").trim();
  const nonDeterministicModel = !!model && model.toLowerCase() !== "deterministic";
  const provider = (opts.provider ?? "").trim().toLowerCase();

  // Test / live compose path (explicit ok) — never label cloud as LOCAL AI SUCCESS
  if (opts.ok === true && nonDeterministicModel) {
    if (provider === "deepseek" || provider === "openai") return "CLOUD_AI_SUCCESS";
    return "LOCAL_AI_SUCCESS";
  }

  // Background job review path (#707). opts.ok===false already returned above.
  if (opts.status === "READY" || (nonDeterministicModel && opts.status !== "FAILED")) {
    return "AI_READY";
  }

  return "OTHER";
}

export function composerRuntimeStatusMessage(runtime: {
  enabled: boolean;
  model: string;
  ollamaEnabled?: boolean;
}): string | null {
  const model = (runtime.model ?? "").trim();
  if (!model) return "Report Composer model not configured";
  if (!runtime.enabled) return "Report Composer disabled (Local AI off or composer model missing)";
  return null;
}
