import { useWorkspace, useWorkspaceSelector } from "@/lib/zai-workspace/store";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { AlertTriangle, FileText } from "lucide-react";
import { useMemo } from "react";
export function ConfirmOverwriteDialog() {
  const open = useWorkspaceSelector(s => s.confirmOverwriteOpen); const confirm = useWorkspaceSelector(s => s.confirmOverwriteAndApply); const cancel = useWorkspaceSelector(s => s.cancelOverwrite);
  const pendingIds = useWorkspaceSelector(s => s.pendingFormatIds); const allF = useWorkspaceSelector(s => s.reportFormats);
  const formats = useMemo(() => allF.filter(f => pendingIds.includes(f.id)), [allF, pendingIds]);
  return <Dialog open={open} onOpenChange={o => !o && cancel()}><DialogContent className="max-w-md"><DialogHeader><DialogTitle className="flex items-center gap-2"><AlertTriangle className="h-4 w-4 text-amber-600" /> Overwrite existing content?</DialogTitle><DialogDescription>The editor has content. Applying will replace it.</DialogDescription></DialogHeader><div className="space-y-2"><div className="rounded-md border border-amber-300 bg-amber-50 p-2.5 text-xs text-amber-800">Applying <b>{formats.length} format{formats.length === 1 ? "" : "s"}</b> will overwrite all 4 editor fields.<div className="mt-1 text-[10px] text-amber-700/80 italic">Tip: Cancel and "Save as Format" first to preserve current work.</div></div>{formats.length > 0 && <div className="rounded-md border border-border bg-muted/30 p-2"><div className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground mb-1">About to apply:</div>{formats.map((f, i) => <div key={f.id} className="flex items-center gap-1.5 text-[11px]"><FileText className="h-3 w-3 text-muted-foreground" /><span className="rounded bg-muted px-1 text-[9px] font-bold">{i === 0 ? "A" : "B"}</span><span className="font-semibold">{f.name}</span></div>)}</div>}</div><DialogFooter><Button variant="ghost" onClick={cancel}>Cancel</Button><Button onClick={confirm} className="bg-amber-600 hover:bg-amber-700">Overwrite & apply</Button></DialogFooter></DialogContent></Dialog>;
}
