import { useWorkspace } from "@/lib/zai-workspace/store";
import { useState, useEffect, useRef } from "react";
import { Zap, X, ChevronRight } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
export function MacroPromptPopover() {
  const prompt = useWorkspace(s => s.activeMacroPrompt); const apply = useWorkspace(s => s.applyMacroWithValues); const cancel = useWorkspace(s => s.setActiveMacroPrompt);
  const [values, setValues] = useState<Record<string, string>>({}); const ref = useRef<HTMLInputElement>(null);
  useEffect(() => { if (prompt) { const init: Record<string, string> = {}; for (const v of prompt.macro.variables) init[v.name] = v.default ?? ""; setValues(init); setTimeout(() => ref.current?.focus(), 50); } }, [prompt]);
  if (!prompt) return null;
  const handleApply = () => apply(values);
  const hk = (e: React.KeyboardEvent) => { if (e.key === "Enter" || (e.key === "Tab" && !e.shiftKey)) { e.preventDefault(); handleApply(); } else if (e.key === "Escape") { e.preventDefault(); cancel(null); } };
  return <div className="fixed bottom-20 left-1/2 z-40 w-[420px] max-w-[95vw] -translate-x-1/2 animate-in slide-in-from-bottom-2"><div className="rounded-xl border-2 border-emerald-400 bg-white shadow-2xl"><div className="flex items-center gap-2 border-b border-emerald-200 bg-emerald-50 px-3 py-2"><Zap className="h-4 w-4 text-emerald-600" /><div className="flex-1"><div className="text-sm font-bold text-emerald-700">{prompt.macro.label}</div><div className="text-[10px] text-emerald-600/80">{" :"}{prompt.macro.trigger} — fill and press Enter</div></div><button onClick={() => cancel(null)} className="rounded-full p-1 text-emerald-500 hover:bg-emerald-100"><X className="h-3.5 w-3.5" /></button></div><div className="space-y-2 p-3" onKeyDown={hk}>{prompt.macro.variables.length === 0 ? <div className="text-[11px] text-muted-foreground">No variables. Press Enter.</div> : prompt.macro.variables.map((v, i) => <div key={v.name}><Label className="text-[10px] uppercase tracking-wider text-muted-foreground">{v.label || v.name}</Label>{v.options && v.options.length > 0 ? <select value={values[v.name] ?? ""} onChange={e => setValues({ ...values, [v.name]: e.target.value })} className="mt-0.5 w-full rounded-md border border-border bg-background px-2 py-1.5 text-sm h-8">{v.options.map(o => <option key={o} value={o}>{o}</option>)}</select> : <Input ref={i === 0 ? ref : undefined} value={values[v.name] ?? ""} onChange={e => setValues({ ...values, [v.name]: e.target.value })} placeholder={v.default || v.name} className="h-8 text-sm" />}</div>)}<div className="flex gap-1.5 pt-1"><Button size="sm" className="flex-1 h-7 bg-emerald-600 text-[11px] hover:bg-emerald-700" onClick={handleApply}><ChevronRight className="h-3 w-3 mr-1" /> Expand</Button><Button size="sm" variant="outline" className="h-7 text-[11px]" onClick={() => cancel(null)}>Cancel</Button></div><div className="text-center pt-1 text-[9px] text-muted-foreground"><kbd className="rounded bg-muted px-1 py-0.5 font-mono">Enter</kbd> expand · <kbd className="rounded bg-muted px-1 py-0.5 font-mono">Esc</kbd> cancel</div></div></div></div>;
}
