import { useWorkspace, useWorkspaceSelector } from "@/lib/zai-workspace/store";
import type { MergeSentence } from "@/lib/zai-workspace/types";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Check, X, GitMerge, Minus } from "lucide-react";
import { cn } from "@/lib/utils";
const T: Record<string, { bg: string; text: string; border: string }> = { common: { bg: "bg-slate-100", text: "text-slate-800", border: "border-l-slate-500" }, "from-a": { bg: "bg-emerald-100", text: "text-emerald-900", border: "border-l-emerald-600" }, "from-b": { bg: "bg-sky-100", text: "text-sky-900", border: "border-l-sky-600" } };
export function MergePreviewDialog() {
  const open = useWorkspaceSelector(s => s.mergePreviewOpen); const r = useWorkspaceSelector(s => s.lastMergeResult); const f = useWorkspaceSelector(s => s.lastMergeFormats); const apply = useWorkspaceSelector(s => s.applyMergedResult); const cancel = useWorkspaceSelector(s => s.cancelMerge);
  return <Dialog open={open} onOpenChange={o => !o && cancel()}><DialogContent className="max-w-3xl max-h-[90vh] flex flex-col"><DialogHeader><DialogTitle className="flex items-center gap-2"><GitMerge className="h-4 w-4 text-emerald-600" /> Merge Preview</DialogTitle><DialogDescription>Common kept once, unique from both added.</DialogDescription></DialogHeader>
    <div className="flex flex-wrap gap-2 mb-2"><Legend tone="common" count={r?.stats.commonSentencesDiscarded ?? 0} /><Legend tone="from-a" count={r?.stats.addedFromA ?? 0} name={f?.a.name} /><Legend tone="from-b" count={r?.stats.addedFromB ?? 0} name={f?.b?.name} /></div>
    {r && <div className="rounded-md border border-emerald-200 bg-emerald-50/40 p-2 text-[11px] text-emerald-800 mb-2">Kept <b>{r.stats.commonSentencesDiscarded}</b> common once, added <b>{r.stats.addedFromA}</b> from {f?.a.name} + <b>{r.stats.addedFromB}</b> from {f?.b?.name}.</div>}
    <div className="flex-1 overflow-y-auto space-y-3 pr-1">{r && <><Field label="Technique" sentences={r.techniqueSentences} discarded={[]} /><Field label="Findings" sentences={r.findingsMerged.sentences} discarded={r.findingsMerged.discarded} /><Field label="Impression" sentences={r.impressionMerged.sentences} discarded={r.impressionMerged.discarded} /><Field label="Recommendation" sentences={r.recommendationMerged.sentences} discarded={r.recommendationMerged.discarded} /></>}</div>
    <DialogFooter><Button variant="ghost" onClick={cancel}><X className="h-3.5 w-3.5 mr-1" /> Cancel</Button><Button onClick={apply} className="bg-emerald-600 hover:bg-emerald-700"><Check className="h-3.5 w-3.5 mr-1" /> Apply</Button></DialogFooter></DialogContent></Dialog>;
}
function Legend({ tone, count, name }: { tone: string; count: number; name?: string }) { const t = T[tone]; return <div className={cn("inline-flex items-center gap-1 rounded-md border-l-2 px-2 py-0.5 text-[10px] font-semibold", t.bg, t.text, t.border)}><span className={cn("h-2 w-2 rounded-full", tone === "common" ? "bg-slate-500" : tone === "from-a" ? "bg-emerald-600" : "bg-sky-600")} />{name && <span className="font-normal opacity-70 truncate max-w-[100px]">({name})</span>}<span className="font-mono">×{count}</span></div>; }
function Field({ label, sentences, discarded }: { label: string; sentences: MergeSentence[]; discarded: string[] }) { return <div className="rounded-md border border-border bg-card overflow-hidden"><div className="flex items-center justify-between bg-muted/30 px-2 py-1 border-b border-border"><div className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">{label}</div><div className="text-[9px] text-muted-foreground">{sentences.length} sentences{discarded.length > 0 && <span className="text-rose-600"> · {discarded.length} deduped</span>}</div></div><div className="p-2 space-y-1">{sentences.map((s, i) => { const t = T[s.source]; return <div key={i} className={cn("border-l-2 px-2 py-1 text-xs leading-snug", t.bg, t.text, t.border)}>{s.text}<span className="ml-1 text-[8px] font-mono opacity-50">[{s.source === "common" ? "C" : s.source === "from-a" ? "A" : "B"}]</span></div>; })}</div>{discarded.length > 0 && <div className="border-t border-rose-200 bg-rose-50/40 p-2"><div className="flex items-center gap-1 text-[10px] font-semibold uppercase tracking-wider text-rose-700 mb-1"><Minus className="h-3 w-3" /> Discarded duplicates</div>{discarded.map((d, i) => <div key={i} className="line-through text-[11px] px-2 text-rose-700/70">{d}</div>)}</div>}</div>; }
