import type { Modality, ReportFormat, MergeResult } from "./types";
import { mergeTwoFormats } from "./types";
const now = () => new Date().toISOString();
const uid = () => `rf_${Date.now().toString(36)}_${Math.random().toString(36).slice(2,7)}`;
function fmt(n: string, m: Modality, b: string, t: string[], body: { technique: string; findings: string; impression: string; recommendation: string }, c = false): ReportFormat { return { id: uid(), name: n, modality: m, bodyPart: b, diagnosisTags: t, isCommon: c, createdAt: now(), updatedAt: now(), ...body }; }

export const DEFAULT_REPORT_FORMATS: ReportFormat[] = [
  fmt("MRI Brain — Normal","MR","Brain",["normal"],{technique:"MRI brain on 3T. T1W, T2W, FLAIR, DWI, ADC, post-contrast T1W GRE. 5 mm.",findings:"Brain parenchyma shows normal signal intensity. No acute infarct, hemorrhage, or mass lesion. Ventricular system and cisternal spaces are normal. No midline shift. Cortical sulci normal for age. Basal cisterns unremarkable. No restricted diffusion on DWI/ADC. Flow voids in major intracranial vessels are normal.",impression:"Normal MRI brain. No acute intracranial abnormality.",recommendation:"Clinical correlation. Follow-up as clinically indicated."},true),
  fmt("MRI Brain — Fazekas 1","MR","Brain",["white matter disease","fazekas 1"],{technique:"MRI brain on 3T. T1W, T2W, FLAIR, DWI, ADC, post-contrast T1W GRE. 5 mm.",findings:"Few punctate T2/FLAIR hyperintense white matter lesions in bilateral periventricular and deep white matter, Fazekas grade 1. No confluent lesions. Brain parenchyma otherwise normal. No acute infarct, hemorrhage, or mass lesion. Ventricular system and cisternal spaces are normal. No midline shift. Cortical sulci normal for age. No restricted diffusion on DWI/ADC. Flow voids in major intracranial vessels are normal.",impression:"Mild chronic small vessel ischemic disease (Fazekas grade 1). No acute infarct or hemorrhage.",recommendation:"Clinical correlation. Control of vascular risk factors. Follow-up as clinically indicated."},true),
  fmt("MRI Brain — Glioma recurrence","MR","Brain",["tumor","glioma","recurrence","critical"],{technique:"MRI brain with contrast on 3T. T1W, T2W, FLAIR, DWI, ADC, post-contrast T1W GRE. 5 mm. IV: Gadobutrol 0.1 mmol/kg.",findings:"Heterogeneously enhancing area in the right frontal operculum at the post-resection cavity, measuring approximately ___ × ___ × ___ cm, with surrounding T2/FLAIR hyperintensity suggestive of edema. Findings are concerning for tumor recurrence. No new satellite lesions. No midline shift. Ventricular system is normal. Basal cisterns are unremarkable. No restricted diffusion on DWI/ADC. Flow voids in major intracranial vessels are normal.",impression:"Heterogeneously enhancing lesion in the right frontal operculum with surrounding edema. Findings are concerning for tumor recurrence. Recommend correlation with clinical status and oncology referral.",recommendation:"Urgent oncology referral. Recommend MRI brain with contrast and perfusion imaging in 6-8 weeks. Consider MR spectroscopy if clinically indicated."},true),
  fmt("MRI Brain — Acute infarct (MCA)","MR","Brain",["stroke","infarct","critical"],{technique:"MRI brain on 3T. T1W, T2W, FLAIR, DWI, ADC, GRE/SWI. 5 mm.",findings:"Restricted diffusion in the left middle cerebral artery territory on DWI/ADC, consistent with acute infarct. No hemorrhagic transformation. Mass effect minimal. Brain parenchyma otherwise normal. Ventricular system and cisternal spaces are normal. No midline shift. Flow voids: left MCA flow void absent, consistent with occlusion.",impression:"Acute left MCA territory infarct. No hemorrhagic transformation. ASPECTS: ___/10.",recommendation:"Immediate stroke team notification. If within thrombolysis window, consider IV tPA. MRA head and neck recommended."},true),
  fmt("MRI LS Spine — Normal","MR","LS Spine",["normal"],{technique:"MRI lumbo-sacral spine on 3T. Sagittal T1W, T2W; axial T1W, T2W. 4 mm.",findings:"Lumbar vertebrae show normal alignment and marrow signal. No spondylolisthesis. Disc spaces are maintained. No acute fracture. Conus medullaris at L1 with normal appearance. Cauda equina nerve roots are normally distributed. Paraspinal soft tissues are unremarkable. Sacroiliac joints are normal.",impression:"Normal MRI lumbo-sacral spine. No acute bony or disc abnormality.",recommendation:"Clinical correlation. Follow-up as clinically indicated."},true),
  fmt("MRI LS Spine — Disc herniation L4-L5","MR","LS Spine",["disc","herniation"],{technique:"MRI lumbo-sacral spine on 3T. Sagittal T1W, T2W; axial T1W, T2W. 4 mm.",findings:"Broad-based disc bulge at L4-L5 with posterocentral-right paracentral protrusion causing indentation on the thecal sac and mild narrowing of bilateral neural foramina. No significant central canal stenosis. Lumbar vertebrae show normal alignment and marrow signal. No spondylolisthesis. L4-L5 disc shows mild desiccation with reduced T2 signal. Other disc spaces are maintained. Conus medullaris at L1 with normal appearance. Cauda equina nerve roots are normally distributed. Paraspinal soft tissues are unremarkable. Sacroiliac joints are normal.",impression:"Disc herniation at L4-L5 causing indentation on the thecal sac and mild narrowing of bilateral neural foramina. No significant central canal stenosis.",recommendation:"Conservative management with NSAIDs and physiotherapy. MRI if radicular symptoms persist. Surgical referral if neurological deficits develop."},true),
  fmt("CT Brain — Normal","CT","Brain",["normal"],{technique:"Non-contrast CT brain on 128-slice scanner. 5 mm. Axial sections from skull base to vertex.",findings:"Brain parenchyma shows normal attenuation. No acute hemorrhage or mass lesion. Ventricular system and cisternal spaces are normal. No midline shift. Cortical sulci normal for age. Basal cisterns are patent. Pineal and choroid plexus calcifications, normal for age. Bony calvarium is unremarkable.",impression:"Normal non-contrast CT brain. No acute intracranial abnormality.",recommendation:"Clinical correlation. Follow-up as clinically indicated."},true),
  fmt("CT Brain — Acute infarct (MCA)","CT","Brain",["stroke","infarct","critical"],{technique:"Non-contrast CT brain on 128-slice scanner. 5 mm. Axial sections from skull base to vertex.",findings:"Loss of grey-white differentiation in the left middle cerebral artery territory, consistent with acute infarct. Hyperdense left MCA sign. No hemorrhagic transformation. Mass effect with effacement of cortical sulci in the left hemisphere. No midline shift at this time. Ventricular system is normal. Basal cisterns are patent. Bony calvarium is unremarkable.",impression:"Acute left MCA territory infarct. No hemorrhagic transformation. ASPECTS: ___/10.",recommendation:"Immediate stroke team notification. If within thrombolysis window, consider IV tPA. CTA head and neck recommended."},true),
  fmt("CT Brain — Acute ICH","CT","Brain",["hemorrhage","critical"],{technique:"Non-contrast CT brain on 128-slice scanner. 5 mm. Axial sections from skull base to vertex.",findings:"Acute intraparenchymal hemorrhage in the right basal ganglia measuring ___ × ___ cm. Intraventricular extension into the lateral ventricles. Mass effect with midline shift of ___ mm to the left. Surrounding low attenuation suggestive of edema. Ventricular system is dilated. Bony calvarium is unremarkable.",impression:"Acute intraparenchymal hemorrhage in the right basal ganglia with intraventricular extension and mass effect.",recommendation:"Urgent neurosurgery referral for hematoma evacuation. ICU admission. Blood pressure control. Repeat CT in 24-48 hours."},true),
  fmt("CT Chest — Normal","CT","Chest",["normal"],{technique:"CT thorax on 128-slice scanner. Contrast-enhanced. 5 mm. IV: 350 mgI/mL, 80 mL. MPR in coronal and sagittal planes.",findings:"Lung fields are clear. No focal consolidation, mass lesion, or nodule. Trachea and main bronchi are patent. Bilateral pleural spaces are clear. No pleural effusion or pneumothorax. Mediastinum is normal. No lymphadenopathy. Heart and great vessels are unremarkable. Pulmonary vasculature is normal. Bony thorax shows no lytic or sclerotic lesion.",impression:"Normal CT thorax. No acute intrathoracic abnormality.",recommendation:"Clinical correlation. Follow-up as clinically indicated."},true),
  fmt("CT Chest — Bronchogenic carcinoma (RUL)","CT","Chest",["malignancy","lung cancer","critical"],{technique:"CT thorax on 128-slice scanner. Contrast-enhanced. 5 mm. IV: 350 mgI/mL, 80 mL. MPR in coronal and sagittal planes.",findings:"Spiculated soft tissue mass in the right upper lobe measuring ___ × ___ × ___ cm with surrounding ground-glass opacities. Findings are highly suspicious for malignancy. New satellite nodules in the right upper lobe. Mediastinal lymphadenopathy: subcarinal node measuring ___ × ___ cm, paratracheal nodes enlarged. No pleural effusion. No pericardial effusion. Trachea and main bronchi are patent. Pulmonary vasculature is normal. Bony thorax shows no lytic or sclerotic lesion.",impression:"Spiculated mass in the right upper lobe with mediastinal lymphadenopathy, highly suspicious for bronchogenic carcinoma with nodal involvement.",recommendation:"Urgent oncology referral. Tissue diagnosis via CT-guided biopsy or bronchoscopy. PET-CT for complete staging. Brain MRI for metastasis assessment."},true),
  fmt("XR LS Spine — Normal","XR","LS Spine",["normal"],{technique:"Radiograph of lumbo-sacral spine on digital radiography unit. Standard AP and lateral views.",findings:"Lumbar vertebrae show normal alignment. No spondylolisthesis. Disc spaces are maintained. No acute fracture. Vertebral body heights are maintained. Bony cortex is intact. Sacroiliac joints are normal. Soft tissues are unremarkable.",impression:"Normal lumbo-sacral spine radiograph. No acute bony abnormality.",recommendation:"Clinical correlation. MRI lumbo-sacral spine if radicular symptoms persist."},true),
  fmt("XR LS Spine — Degenerative changes","XR","LS Spine",["degenerative"],{technique:"Radiograph of lumbo-sacral spine on digital radiography unit. Standard AP and lateral views.",findings:"Mild degenerative changes with marginal osteophytes at L3-L4 and L4-L5. Reduced L4-L5 disc space with endplate sclerosis. No significant spondylolisthesis. No acute fracture. Vertebral body heights are maintained. Bony cortex is intact. Sacroiliac joints are normal. Soft tissues are unremarkable.",impression:"Mild degenerative changes of the lumbar spine. No acute bony abnormality.",recommendation:"Clinical correlation. Conservative management with NSAIDs and physiotherapy. MRI if symptoms persist."},true),
  fmt("US Abdomen — Normal","US","Abdomen",["normal"],{technique:"Ultrasound of whole abdomen on convex transducer (3-6 MHz) with patient in supine position.",findings:"Liver is normal in size and echo texture. No focal lesion. Intrahepatic biliary radicals are not dilated. Portal vein is normal. Gallbladder is normal in size and wall thickness. No calculi or sludge. Common bile duct is unremarkable. Pancreas is normal in size and echo texture. Spleen is normal in size and echo texture. No focal lesion. Both kidneys are normal in size and cortical thickness. No calculus or hydronephrosis. Cortical echogenicity is normal. Urinary bladder is normal. No free fluid in abdomen.",impression:"Normal ultrasound abdomen. No focal lesion or free fluid detected.",recommendation:"Clinical correlation. Follow-up as clinically indicated."},true),
  fmt("US Abdomen — Cholelithiasis","US","Abdomen",["gallstones"],{technique:"Ultrasound of whole abdomen on convex transducer (3-6 MHz) with patient in supine position.",findings:"Multiple echogenic foci with acoustic shadowing in the gallbladder lumen, largest measuring ___ mm, suggestive of cholelithiasis. Gallbladder wall thickness is normal. No pericholecystic fluid. No sonographic Murphy sign. Common bile duct is unremarkable, measuring ___ mm. Liver is normal in size and echo texture. No focal lesion. Intrahepatic biliary radicals are not dilated. Portal vein is normal. Pancreas is normal. Spleen is normal. Both kidneys are normal. No free fluid in abdomen.",impression:"Cholelithiasis. No sonographic evidence of acute cholecystitis. No biliary dilatation.",recommendation:"Clinical correlation. Surgical consultation if symptomatic. Follow-up ultrasound as clinically indicated."},true),
  fmt("US OB — Normal 2nd trimester","US","OB",["normal","anomaly scan"],{technique:"Ultrasound obstetric scan on convex transducer (3-6 MHz). Transabdominal. Biometry: BPD, HC, AC, FL.",findings:"Single live intrauterine gestation. Cardiac activity positive (FHR ___ bpm). Biometry corresponds to ___ weeks. BPD: ___ mm. HC: ___ mm. AC: ___ mm. FL: ___ mm. EFW: ___ g. Placenta is posterior, fundal, grade II. Normal amniotic fluid volume (AFI: ___ cm). No fetal anomaly detected. Four-chamber heart normal. Spine intact. Limbs normal. Stomach bubble seen. Bladder seen.",impression:"Single live intrauterine gestation corresponding to gestational age. No fetal anomaly detected. Normal amniotic fluid volume.",recommendation:"Routine follow-up scan at 28 weeks. Clinical correlation advised."},true),
  fmt("MG Breast — BI-RADS 2 (Benign)","MG","Breast",["birads 2","benign","screening"],{technique:"Bilateral mammography. Standard CC and MLO views. Tomosynthesis acquired. Comparison with prior mammogram dated ____.",findings:"Bilateral breast parenchyma is symmetric. No suspicious masses or architectural distortion. No pleomorphic microcalcifications. Two well-circumscribed oval masses with coarse calcifications in the left breast, upper outer quadrant — benign features consistent with fibroadenomas. Stable compared to prior. Axillary lymph nodes are normal in morphology. Skin and nipples are unremarkable.",impression:"BI-RADS 2: Benign findings. Stable fibroadenomas in the left breast. No suspicious masses or calcifications.",recommendation:"Routine screening mammography in 12 months. Clinical correlation advised."},true),
  fmt("MG Breast — BI-RADS 5 (Highly suspicious)","MG","Breast",["birads 5","malignancy","critical"],{technique:"Bilateral mammography. Standard CC and MLO views. Tomosynthesis acquired. Comparison with prior mammogram dated ____.",findings:"Spiculated mass in the right breast, upper outer quadrant, measuring ___ × ___ cm, with associated skin retraction and nipple retraction. Clustered pleomorphic microcalcifications in the same region. Enlarged right axillary lymph node with cortical thickening and loss of fatty hilum. Left breast is unremarkable.",impression:"BI-RADS 5: Highly suggestive of malignancy. Spiculated mass with microcalcifications and suspicious axillary lymph node in the right breast.",recommendation:"Image-guided biopsy of the right breast lesion is mandatory. Surgical referral advised. Bilateral breast MRI for staging. Oncology referral."},true),
];

export function lookupFormats(formats: ReportFormat[], m: Modality | undefined, b: string | undefined): ReportFormat[] {
  return formats.filter(f => f.modality === m && (!b || f.bodyPart === b)).sort((a, b) => { if (a.isCommon !== b.isCommon) return a.isCommon ? -1 : 1; return (b.usageCount ?? 0) - (a.usageCount ?? 0) || a.name.localeCompare(b.name); });
}
const SK = "zai-rad-reportformats-v1";
export function loadFormats(): ReportFormat[] { try { const r = localStorage.getItem(SK); return r ? JSON.parse(r) : DEFAULT_REPORT_FORMATS; } catch { return DEFAULT_REPORT_FORMATS; } }
export function saveFormats(f: ReportFormat[]) { try { localStorage.setItem(SK, JSON.stringify(f)); } catch {} }
export function createFormat(i: Omit<ReportFormat, "id" | "createdAt" | "updatedAt">): ReportFormat { return { ...i, id: uid(), createdAt: now(), updatedAt: now(), custom: true }; }
export function resetFormatsToDefaults(): ReportFormat[] { localStorage.removeItem(SK); return DEFAULT_REPORT_FORMATS; }
export { mergeTwoFormats };
export type { MergeResult };
