/**
 * Catalog of Phase-2 owned Starting Canvas formats (excludes LS Standard Normal,
 * which remains defined in fullReportBaseline.ts as the architectural reference).
 */
import type { BaselineManifest, ReportFormat } from "../types";
import {
  MRI_BRAIN_STANDARD_NORMAL_FINDINGS,
  MRI_BRAIN_STANDARD_NORMAL_IMPRESSION,
  MRI_BRAIN_STANDARD_NORMAL_MANIFEST,
  MRI_BRAIN_STANDARD_NORMAL_META,
  MRI_BRAIN_STANDARD_NORMAL_NAME,
} from "./mriBrainStandardNormal";
import {
  MRI_BRAIN_SCREENING_NORMAL_FINDINGS,
  MRI_BRAIN_SCREENING_NORMAL_IMPRESSION,
  MRI_BRAIN_SCREENING_NORMAL_MANIFEST,
  MRI_BRAIN_SCREENING_NORMAL_META,
  MRI_BRAIN_SCREENING_NORMAL_NAME,
} from "./mriBrainScreeningNormal";
import {
  MRI_CERVICAL_STANDARD_NORMAL_FINDINGS,
  MRI_CERVICAL_STANDARD_NORMAL_IMPRESSION,
  MRI_CERVICAL_STANDARD_NORMAL_MANIFEST,
  MRI_CERVICAL_STANDARD_NORMAL_META,
  MRI_CERVICAL_STANDARD_NORMAL_NAME,
} from "./mriCervicalStandardNormal";
import {
  MRI_CERVICAL_SCREENING_NORMAL_FINDINGS,
  MRI_CERVICAL_SCREENING_NORMAL_IMPRESSION,
  MRI_CERVICAL_SCREENING_NORMAL_MANIFEST,
  MRI_CERVICAL_SCREENING_NORMAL_META,
  MRI_CERVICAL_SCREENING_NORMAL_NAME,
} from "./mriCervicalScreeningNormal";
import {
  MRI_DORSAL_SCREENING_NORMAL_FINDINGS,
  MRI_DORSAL_SCREENING_NORMAL_IMPRESSION,
  MRI_DORSAL_SCREENING_NORMAL_MANIFEST,
  MRI_DORSAL_SCREENING_NORMAL_META,
  MRI_DORSAL_SCREENING_NORMAL_NAME,
} from "./mriDorsalScreeningNormal";
import {
  MRI_LS_SCREENING_NORMAL_FINDINGS,
  MRI_LS_SCREENING_NORMAL_IMPRESSION,
  MRI_LS_SCREENING_NORMAL_MANIFEST,
  MRI_LS_SCREENING_NORMAL_META,
  MRI_LS_SCREENING_NORMAL_NAME,
} from "./mriLsScreeningNormal";
import {
  MRI_KNEE_STANDARD_NORMAL_FINDINGS,
  MRI_KNEE_STANDARD_NORMAL_IMPRESSION,
  MRI_KNEE_STANDARD_NORMAL_MANIFEST,
  MRI_KNEE_STANDARD_NORMAL_META,
  MRI_KNEE_STANDARD_NORMAL_NAME,
} from "./mriKneeStandardNormal";
import {
  MRI_WHOLE_SPINE_SCREENING_NORMAL_FINDINGS,
  MRI_WHOLE_SPINE_SCREENING_NORMAL_IMPRESSION,
  MRI_WHOLE_SPINE_SCREENING_NORMAL_MANIFEST,
  MRI_WHOLE_SPINE_SCREENING_NORMAL_META,
  MRI_WHOLE_SPINE_SCREENING_NORMAL_NAME,
} from "./mriWholeSpineScreeningNormal";
import {
  SCREENING_LIMITATION_TEXT,
  SCREENING_LIMITATION_CONCEPT,
  screeningLimitationObservation,
} from "./screeningLimitation";

export {
  SCREENING_LIMITATION_TEXT,
  SCREENING_LIMITATION_CONCEPT,
  screeningLimitationObservation,
  MRI_BRAIN_STANDARD_NORMAL_NAME,
  MRI_BRAIN_STANDARD_NORMAL_FINDINGS,
  MRI_BRAIN_STANDARD_NORMAL_IMPRESSION,
  MRI_BRAIN_STANDARD_NORMAL_MANIFEST,
  MRI_BRAIN_SCREENING_NORMAL_NAME,
  MRI_BRAIN_SCREENING_NORMAL_FINDINGS,
  MRI_BRAIN_SCREENING_NORMAL_IMPRESSION,
  MRI_BRAIN_SCREENING_NORMAL_MANIFEST,
  MRI_CERVICAL_STANDARD_NORMAL_NAME,
  MRI_CERVICAL_STANDARD_NORMAL_FINDINGS,
  MRI_CERVICAL_STANDARD_NORMAL_IMPRESSION,
  MRI_CERVICAL_STANDARD_NORMAL_MANIFEST,
  MRI_CERVICAL_SCREENING_NORMAL_NAME,
  MRI_CERVICAL_SCREENING_NORMAL_FINDINGS,
  MRI_CERVICAL_SCREENING_NORMAL_IMPRESSION,
  MRI_CERVICAL_SCREENING_NORMAL_MANIFEST,
  MRI_KNEE_STANDARD_NORMAL_NAME,
  MRI_KNEE_STANDARD_NORMAL_FINDINGS,
  MRI_KNEE_STANDARD_NORMAL_IMPRESSION,
  MRI_KNEE_STANDARD_NORMAL_MANIFEST,
  MRI_DORSAL_SCREENING_NORMAL_NAME,
  MRI_DORSAL_SCREENING_NORMAL_FINDINGS,
  MRI_DORSAL_SCREENING_NORMAL_IMPRESSION,
  MRI_DORSAL_SCREENING_NORMAL_MANIFEST,
  MRI_LS_SCREENING_NORMAL_NAME,
  MRI_LS_SCREENING_NORMAL_FINDINGS,
  MRI_LS_SCREENING_NORMAL_IMPRESSION,
  MRI_LS_SCREENING_NORMAL_MANIFEST,
  MRI_WHOLE_SPINE_SCREENING_NORMAL_NAME,
  MRI_WHOLE_SPINE_SCREENING_NORMAL_FINDINGS,
  MRI_WHOLE_SPINE_SCREENING_NORMAL_IMPRESSION,
  MRI_WHOLE_SPINE_SCREENING_NORMAL_MANIFEST,
};

export type OwnedBaselineCatalogEntry = {
  name: string;
  modality: "MR";
  bodyPart: string;
  protocolScope?: string;
  clinicalHistory: string;
  technique: string;
  findings: string;
  impression: string;
  recommendation: string;
  reportTitle: string;
  diagnosisTags: string[];
  manifest: BaselineManifest;
};

function asEntry(meta: OwnedBaselineCatalogEntry): OwnedBaselineCatalogEntry {
  return meta;
}

/** Phase 2 owned baseline catalog (8 formats). Does not include LS Standard Normal. */
export function ownedBaselineCatalog(): OwnedBaselineCatalogEntry[] {
  return [
    asEntry(MRI_BRAIN_STANDARD_NORMAL_META),
    asEntry(MRI_CERVICAL_STANDARD_NORMAL_META),
    asEntry(MRI_KNEE_STANDARD_NORMAL_META),
    asEntry(MRI_BRAIN_SCREENING_NORMAL_META),
    asEntry(MRI_CERVICAL_SCREENING_NORMAL_META),
    asEntry(MRI_DORSAL_SCREENING_NORMAL_META),
    asEntry(MRI_LS_SCREENING_NORMAL_META),
    asEntry(MRI_WHOLE_SPINE_SCREENING_NORMAL_META),
  ];
}

/** Built-in name → manifest map for hydration. */
export function ownedBaselineManifestByName(): Map<string, BaselineManifest> {
  const map = new Map<string, BaselineManifest>();
  for (const e of ownedBaselineCatalog()) map.set(e.name, e.manifest);
  return map;
}

export function ownershipCount(manifest: BaselineManifest): number {
  return manifest.observations.length;
}

export function formatLooksLikeOwnedBaseline(
  format: Pick<ReportFormat, "name" | "modality" | "bodyPart">,
): boolean {
  return ownedBaselineManifestByName().has(format.name);
}
