<#
  Care Diagnostics — Scan Bridge one-file web installer (Windows)
  ---------------------------------------------------------------
  This file is downloaded from Form F ("Set up scanner" → Download installer)
  and is fully self-contained — it writes the bridge into your user profile,
  installs it, registers it to auto-start at logon, and verifies it responds.
  No folder to copy, no admin rights.

  Run:  right-click this file  →  "Run with PowerShell"

  (Generated by scan-bridge/build-web-installer.mjs from the real bridge source
  — do not edit by hand; edit the source and re-run the generator.)
#>
#Requires -Version 5.1
$ErrorActionPreference = "Stop"

function Pause-Exit($code) { Read-Host "Press Enter to close"; exit $code }
function Write-FileNoBom($path, $text) {
  $dir = Split-Path -Parent $path
  if (-not (Test-Path $dir)) { New-Item -ItemType Directory -Force -Path $dir | Out-Null }
  [System.IO.File]::WriteAllText($path, $text, (New-Object System.Text.UTF8Encoding $false))
}

Write-Host ""
Write-Host "==  Care Diagnostics  -  Scan Bridge setup  ==" -ForegroundColor Cyan
Write-Host ""

# 1. Node.js present?
$nodeV = $null
try { $nodeV = (& node --version) 2>$null } catch { $nodeV = $null }
if (-not $nodeV) {
  Write-Host "Node.js is not installed." -ForegroundColor Red
  Write-Host "Install the LTS version from https://nodejs.org, then run this installer again."
  Start-Process "https://nodejs.org/en/download"
  Pause-Exit 1
}
Write-Host "Node.js $nodeV found." -ForegroundColor Green

# 2. Where the bridge lives (per-user profile — no admin needed)
$dest = Join-Path $env:LOCALAPPDATA "CareScanBridge"
Write-Host "Installing to: $dest"

# 3. Embedded bridge source (filled in by the generator)
$B = @{}
#__EMBEDDED_FILES__

foreach ($rel in $B.Keys) {
  Write-FileNoBom (Join-Path $dest $rel) $B[$rel]
}
Write-Host "Wrote bridge files."

# 4. Configuration
$defaultErp = "https://caredeoghar.com"
$erp = Read-Host "ERP web address (must match the browser URL) [$defaultErp]"
if ([string]::IsNullOrWhiteSpace($erp)) { $erp = $defaultErp }
$erp = $erp.TrimEnd('/')

Write-Host ""
Write-Host "Scanner type:"
Write-Host "  1) WIA          - any scanner listed in Windows 'Fax and Scan' (recommended)"
Write-Host "  2) folder-watch - your scanner's own software saves images to a folder"
$choice = Read-Host "Choose 1 or 2 [1]"
if ($choice -eq "2") {
  $vendor = "folder-watch"
  $watch = Read-Host "Folder your scanner software saves scans to (e.g. C:\Scans)"
} else {
  $vendor = "wia"
  $watch = ""
}

# 5. Dependencies
Write-Host ""
Write-Host "Installing dependencies (npm install)..." -ForegroundColor Cyan
Push-Location $dest
& npm install --omit=dev
$npmCode = $LASTEXITCODE
Pop-Location
if ($npmCode -ne 0) {
  Write-Host "npm install failed. Check your internet connection and try again." -ForegroundColor Red
  Pause-Exit 1
}

# 6. Start script with the chosen config baked in
$startCmd = Join-Path $dest "start-scan-bridge.cmd"
$cmdLines = @(
  "@echo off",
  "cd /d ""%~dp0""",
  "set ERP_BASE_URL=$erp",
  "set BRIDGE_SCAN_VENDOR=$vendor"
)
if ($vendor -eq "folder-watch") { $cmdLines += "set SCAN_WATCH_FOLDER=$watch" }
$cmdLines += "node src\index.js"
Write-FileNoBom $startCmd (($cmdLines -join "`r`n") + "`r`n")

# 7. Auto-start at logon (per-user task; no admin)
$taskName = "CareScanBridge"
$arg = '/c "' + $startCmd + '"'
try {
  Unregister-ScheduledTask -TaskName $taskName -Confirm:$false -ErrorAction SilentlyContinue
  $action   = New-ScheduledTaskAction -Execute "cmd.exe" -Argument $arg
  $trigger  = New-ScheduledTaskTrigger -AtLogOn
  $settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries -Hidden
  Register-ScheduledTask -TaskName $taskName -Action $action -Trigger $trigger -Settings $settings -Description "Care Diagnostics document scan bridge" | Out-Null
  Write-Host "Registered auto-start task '$taskName' (starts at each logon)." -ForegroundColor Green
  Start-ScheduledTask -TaskName $taskName
} catch {
  Write-Host "Could not register the auto-start task: $($_.Exception.Message)" -ForegroundColor Yellow
  Write-Host "Starting the bridge directly instead (it won't auto-start after reboot)."
  Start-Process -FilePath "cmd.exe" -ArgumentList $arg -WindowStyle Hidden
}

# 8. Verify
Write-Host ""
Write-Host "Verifying the bridge is responding..." -ForegroundColor Cyan
$ok = $false; $vendorReported = ""
for ($i = 0; $i -lt 6 -and -not $ok; $i++) {
  Start-Sleep -Seconds 2
  try {
    $health = Invoke-RestMethod -Uri "http://127.0.0.1:8766/health" -TimeoutSec 4
    if ($health.ok) { $ok = $true; $vendorReported = $health.vendor }
  } catch { }
}
Write-Host ""
if ($ok) {
  Write-Host "SUCCESS - scan bridge is running (vendor: $vendorReported)." -ForegroundColor Green
  Write-Host "Go back to Form F and the 'Existing Scanner' tab will show Online." -ForegroundColor Green
} else {
  Write-Host "The bridge did not answer on http://127.0.0.1:8766 yet." -ForegroundColor Yellow
  Write-Host "Give it a few seconds and refresh Form F. If it stays offline, confirm Node.js is on PATH."
}
Pause-Exit 0
