/**
 * AI Clinical Workflow config — Phase P3 / Gates G10/G11.
 *
 * The safety spine for the FIRST radiologist-visible phase. Everything is
 * OFF by default: the global `feature_flags` master switch (ff_radiology_ai)
 * gates all AI, and these tables layer per-hospital / per-radiologist /
 * per-modality / per-study-type enablement + mode (shadow/pilot/production) on
 * top. Composes with — does not replace — the existing feature_flags backbone.
 */
import { pgTable, serial, integer, text, boolean, timestamp, uniqueIndex, index } from "drizzle-orm/pg-core";
import { staffTable } from "./staff";

// ── AI enablement policies (most-specific-wins; default OFF) ─────────────────
// scope: global | hospital | radiologist | modality | study_type
// mode:  shadow (compute, never show) | pilot (show to pilot users) | production
export const aiFeaturePoliciesTable = pgTable(
  "ai_feature_policies",
  {
    id: serial("id").primaryKey(),
    scope: text("scope").notNull(),
    scopeKey: text("scope_key").notNull().default("*"), // e.g. staffId, "CT", studyType, hospital id
    enabled: boolean("enabled").notNull().default(false),
    mode: text("mode").notNull().default("shadow"),
    updatedBy: text("updated_by"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  },
  (t) => ({ scopeKey: uniqueIndex("ai_feature_policy_scope_key").on(t.scope, t.scopeKey) }),
);
export type AiFeaturePolicy = typeof aiFeaturePoliciesTable.$inferSelect;

// ── Scheduler config (singleton row id=1) ───────────────────────────────────
export const aiSchedulerConfigTable = pgTable("ai_scheduler_config", {
  id: serial("id").primaryKey(),
  /** on_arrival = draft when DICOM lands; scheduled = only inside nightStart–nightEnd. */
  draftTiming: text("draft_timing").notNull().default("on_arrival"),
  nightStart: text("night_start").notNull().default("23:00"), // HH:MM (local)
  nightEnd: text("night_end").notNull().default("06:00"),
  quietStart: text("quiet_start").notNull().default("08:00"),
  quietEnd: text("quiet_end").notNull().default("20:00"),
  gpuLimitPercent: integer("gpu_limit_percent").notNull().default(90),
  cpuLimitPercent: integer("cpu_limit_percent").notNull().default(80),
  maxConcurrentJobs: integer("max_concurrent_jobs").notNull().default(2),
  maxRetries: integer("max_retries").notNull().default(3),
  includePriors: boolean("include_priors").notNull().default(true),
  includeOcr: boolean("include_ocr").notNull().default(true),
  skipFinalizedReports: boolean("skip_finalized_reports").notNull().default(true),
  skipUnchangedStudies: boolean("skip_unchanged_studies").notNull().default(true),
  updatedBy: text("updated_by"),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
});
export type AiSchedulerConfig = typeof aiSchedulerConfigTable.$inferSelect;

// ── Per-modality processing policy ──────────────────────────────────────────
// mode: immediate | night_batch | manual | disabled
export const aiModalityPoliciesTable = pgTable(
  "ai_modality_policies",
  {
    id: serial("id").primaryKey(),
    modality: text("modality").notNull(), // MR | CT | XR/CR | US | MG | Doppler
    mode: text("mode").notNull().default("disabled"),
    updatedBy: text("updated_by"),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  },
  (t) => ({ modalityKey: uniqueIndex("ai_modality_policy_key").on(t.modality) }),
);
export type AiModalityPolicy = typeof aiModalityPoliciesTable.$inferSelect;

// ── Per-radiologist preferences ─────────────────────────────────────────────
export const aiRadiologistPreferencesTable = pgTable(
  "ai_radiologist_preferences",
  {
    id: serial("id").primaryKey(),
    staffId: integer("staff_id").notNull().references(() => staffTable.id),
    autoGenerateDraft: boolean("auto_generate_draft").notNull().default(false),
    autoOpenDraft: boolean("auto_open_draft").notNull().default(false),
    preferredReportStyle: text("preferred_report_style").notNull().default("structured"),
    showConfidenceBadges: boolean("show_confidence_badges").notNull().default(true),
    showEvidenceThumbnails: boolean("show_evidence_thumbnails").notNull().default(true),
    autoCompareWithPrior: boolean("auto_compare_with_prior").notNull().default(true),
    autoLoadMeasurements: boolean("auto_load_measurements").notNull().default(true),
    preferredLanguage: text("preferred_language").notNull().default("en"),
    structuredReportingPreference: boolean("structured_reporting_preference").notNull().default(true),
    updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow().$onUpdate(() => new Date()),
  },
  (t) => ({ staffKey: uniqueIndex("ai_radiologist_pref_staff_key").on(t.staffId) }),
);
export type AiRadiologistPreference = typeof aiRadiologistPreferencesTable.$inferSelect;

// ── Draft feedback (Accept / Edit / Ignore) for learning aggregation ────────
export const aiDraftFeedbackTable = pgTable(
  "ai_draft_feedback",
  {
    id: serial("id").primaryKey(),
    draftId: integer("draft_id").notNull(),
    studyInstanceUid: text("study_instance_uid").notNull(),
    findingKey: text("finding_key"),
    action: text("action").notNull(), // accept | edit | ignore | reject
    editedText: text("edited_text"),
    staffId: integer("staff_id"),
    // P4 / G21 — structured feedback dataset fields (analytics only; no retraining).
    reason: text("reason"),
    laterality: text("laterality"),
    measurementRef: text("measurement_ref"),
    confidence: integer("confidence"),
    promptVersion: text("prompt_version"),
    modelVersion: text("model_version"),
    createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  },
  (t) => ({
    draftIdx: index("ai_draft_feedback_draft_idx").on(t.draftId),
    actionIdx: index("ai_draft_feedback_action_idx").on(t.action),
  }),
);
export type AiDraftFeedback = typeof aiDraftFeedbackTable.$inferSelect;
