/**
 * AI clinical workflow client — Phase P3 (Gates G10/G11).
 * Thin typed wrappers over the existing `api` client for the /api/ai routes.
 * Every call is backend-gated (default OFF); the UI additionally hides itself
 * unless `visibleToRadiologist` is true.
 */
import { api } from "./fetchApi";

export interface AiEnablement {
  enabled: boolean;
  mode: "shadow" | "pilot" | "production";
  visibleToRadiologist: boolean;
  reason: string;
}

export interface AiDraftEvidence {
  evidenceType: string;
  seriesInstanceUid?: string | null;
  sopInstanceUid?: string | null;
  frameNumber?: number | null;
  measurementRef?: string | null;
  confidence?: number | null;
}
export interface AiDraftFinding {
  key: string;
  text: string;
  laterality?: string;
  evidence: AiDraftEvidence[];
}
export interface AiWorkspaceDraft {
  draftId: number;
  studyInstanceUid: string;
  status: "shadow" | "shadow_degraded";
  degraded: boolean;
  qualityScore: number | null;
  findings: AiDraftFinding[];
  quarantinedCount: number;
  measurements: Array<{ id: string; value: number; unit: string }>;
  impression: string[];
  provenance: { modelVersion: string; promptVersion: string; rulesVersion: string; degraded: boolean; createdAt: string };
}

export interface AiPreferences {
  autoGenerateDraft: boolean;
  autoOpenDraft: boolean;
  preferredReportStyle: string;
  showConfidenceBadges: boolean;
  showEvidenceThumbnails: boolean;
  autoCompareWithPrior: boolean;
  autoLoadMeasurements: boolean;
  preferredLanguage: string;
  structuredReportingPreference: boolean;
}

export const aiClient = {
  getPolicy: (modality?: string | null) =>
    api.get<AiEnablement>(`/api/ai/policy${modality ? `?modality=${encodeURIComponent(modality)}` : ""}`),
  getDraft: (studyInstanceUid: string, modality?: string | null) =>
    api.get<AiWorkspaceDraft | null>(`/api/ai/draft?studyInstanceUid=${encodeURIComponent(studyInstanceUid)}${modality ? `&modality=${encodeURIComponent(modality)}` : ""}`),
  generate: (studyInstanceUid: string, modality?: string | null) =>
    api.post<{ enqueued: boolean; reason: string }>(`/api/ai/generate`, { studyInstanceUid, modality }),
  feedback: (draftId: number, body: { studyInstanceUid: string; findingKey?: string; action: "accept" | "edit" | "ignore" | "reject"; editedText?: string }) =>
    api.post<{ ok: boolean }>(`/api/ai/draft/${draftId}/feedback`, body),
  getPreferences: () => api.get<AiPreferences | null>(`/api/ai/preferences`),
  savePreferences: (patch: Partial<AiPreferences>) => api.put<{ ok: boolean }>(`/api/ai/preferences`, patch),
  // Admin
  getSchedulerConfig: () => api.get<Record<string, unknown>>(`/api/ai/scheduler/config`),
  saveSchedulerConfig: (patch: Record<string, unknown>) => api.put<{ ok: boolean }>(`/api/ai/scheduler/config`, patch),
  getModalityPolicies: () => api.get<Array<{ modality: string; mode: string }>>(`/api/ai/modality-policies`),
  setModalityPolicy: (modality: string, mode: string) => api.put<{ ok: boolean }>(`/api/ai/modality-policies`, { modality, mode }),
  getQueue: () => api.get<Record<string, unknown>>(`/api/ai/queue`),
  setPolicy: (body: { scope: string; scopeKey: string; enabled: boolean; mode: string }) => api.put<{ ok: boolean }>(`/api/ai/policies`, body),
};
