/**
 * AI clinical workflow client — Phase P3 (Gates G10/G11).
 * Thin typed wrappers over the existing `api` client for the /api/ai routes.
 * Every call is backend-gated (default OFF); the UI additionally hides itself
 * unless `visibleToRadiologist` is true.
 */
import { api } from "./fetchApi";

export interface AiEnablement {
  enabled: boolean;
  mode: "shadow" | "pilot" | "production";
  visibleToRadiologist: boolean;
  reason: string;
}

export interface AiDraftEvidence {
  evidenceType: string;
  seriesInstanceUid?: string | null;
  sopInstanceUid?: string | null;
  frameNumber?: number | null;
  measurementRef?: string | null;
  confidence?: number | null;
}
export interface AiDraftFinding {
  key: string;
  text: string;
  laterality?: string;
  evidence: AiDraftEvidence[];
}
export interface AiWorkspaceDraft {
  draftId: number;
  studyInstanceUid: string;
  status: "shadow" | "shadow_degraded";
  degraded: boolean;
  qualityScore: number | null;
  findings: AiDraftFinding[];
  quarantinedCount: number;
  measurements: Array<{ id: string; value: number; unit: string }>;
  impression: string[];
  provenance: { modelVersion: string; promptVersion: string; rulesVersion: string; degraded: boolean; createdAt: string };
}

export interface AiPreferences {
  autoGenerateDraft: boolean;
  autoOpenDraft: boolean;
  preferredReportStyle: string;
  showConfidenceBadges: boolean;
  showEvidenceThumbnails: boolean;
  autoCompareWithPrior: boolean;
  autoLoadMeasurements: boolean;
  preferredLanguage: string;
  structuredReportingPreference: boolean;
}

export const aiClient = {
  getPolicy: (modality?: string | null) =>
    api.get<AiEnablement>(`/api/ai/policy${modality ? `?modality=${encodeURIComponent(modality)}` : ""}`),
  getDraft: (studyInstanceUid: string, modality?: string | null) =>
    api.get<AiWorkspaceDraft | null>(`/api/ai/draft?studyInstanceUid=${encodeURIComponent(studyInstanceUid)}${modality ? `&modality=${encodeURIComponent(modality)}` : ""}`),
  generate: (studyInstanceUid: string, modality?: string | null) =>
    api.post<{ enqueued: boolean; reason: string }>(`/api/ai/generate`, { studyInstanceUid, modality }),
  feedback: (draftId: number, body: { studyInstanceUid: string; findingKey?: string; action: "accept" | "edit" | "ignore" | "reject"; editedText?: string }) =>
    api.post<{ ok: boolean }>(`/api/ai/draft/${draftId}/feedback`, body),
  getPreferences: () => api.get<AiPreferences | null>(`/api/ai/preferences`),
  savePreferences: (patch: Partial<AiPreferences>) => api.put<{ ok: boolean }>(`/api/ai/preferences`, patch),
  // Admin
  getSchedulerConfig: () => api.get<Record<string, unknown>>(`/api/ai/scheduler/config`),
  saveSchedulerConfig: (patch: Record<string, unknown>) => api.put<{ ok: boolean }>(`/api/ai/scheduler/config`, patch),
  getModalityPolicies: () => api.get<Array<{ modality: string; mode: string }>>(`/api/ai/modality-policies`),
  setModalityPolicy: (modality: string, mode: string) => api.put<{ ok: boolean }>(`/api/ai/modality-policies`, { modality, mode }),
  setOvernightModalities: (overnightModalities: string[], mode?: string) =>
    api.put<{ ok: boolean }>(
      `/api/ai/modality-policies`,
      { overnightModalities, mode: mode ?? "night_batch" },
    ),
  saveDraftAutomation: (body: {
    draftTiming: "on_arrival" | "scheduled";
    modalities: string[];
    nightStart?: string;
    nightEnd?: string;
    quietStart?: string;
    quietEnd?: string;
    studyAgeWindow?: string;
    studyAgeCustomFrom?: string | null;
    studyAgeCustomTo?: string | null;
    enableAi?: boolean;
  }) =>
    api.put<{
      ok: boolean;
      masterEnabled?: boolean;
      scheduler?: Record<string, unknown>;
      policies?: Array<{ modality: string; mode: string }>;
    }>(`/api/ai/draft-automation`, body),
  runNightBatch: (force?: boolean, onlyNew?: boolean) => {
    const q = new URLSearchParams();
    if (force) q.set("force", "1");
    if (onlyNew) q.set("onlyNew", "1");
    const qs = q.toString();
    return api.post<Record<string, unknown>>(
      `/api/ai/scheduler/run/night-batch${qs ? `?${qs}` : ""}`,
      { force: Boolean(force), onlyNew: Boolean(onlyNew) },
    );
  },
  previewNightBatch: () => api.get<Record<string, unknown>>(`/api/ai/scheduler/night-batch-preview`),
  getOvernightDiagnostics: () => api.get<Record<string, unknown>>(`/api/ai/overnight-diagnostics`),
  getOvernightOps: () => api.get<{
    ops: Record<string, unknown>;
    effectivePolicy: Record<string, unknown>;
    backlogNote?: string;
    legacyBacklog?: {
      held: boolean;
      holdBefore: string | null;
      heldPending: number;
      heldRetrying: number;
      newEligible: number;
      releasedAllowlistSize: number;
    };
  }>(`/api/ai/overnight-ops`),
  saveOvernightOps: (body: {
    paused?: boolean;
    pauseReason?: string | null;
    imageCap?: "auto" | "1" | "2" | "3" | "4" | "6";
    visionCtx?: "current" | "4096" | "8192" | "16384";
    safeMode?: boolean;
    clearResourceStreak?: boolean;
    legacyBacklogHold?: true;
  }) => api.put<{ ok: boolean; ops: Record<string, unknown> }>(`/api/ai/overnight-ops`, body),
  legacyBacklogAction: (body:
    | { action: "retry_selected"; jobIds: number[] }
    | { action: "release_selected"; jobIds: number[] }
    | { action: "release_recent"; limit?: number }
    | { action: "release_all"; confirm: true }
  ) =>
    api.post<{
      ok: boolean;
      action: string;
      ops: Record<string, unknown>;
      legacyBacklog?: Record<string, unknown>;
      releasedJobIds?: number[];
      deleted?: number;
      retry?: Record<string, unknown>;
    }>(`/api/ai/overnight-ops/legacy-backlog`, body),
  recycleOllamaRunner: () =>
    api.post<Record<string, unknown>>(`/api/radiology-ollama/recycle-runner`, {}),
  queueSelected: (studyInstanceUids: string[], modalities?: Record<string, string | null>, retry?: boolean) =>
    api.post<{ queued: number; skipped: Array<{ uid: string; reason: string }> }>(`/api/ai/overnight/queue-selected`, {
      studyInstanceUids, modalities, retry,
    }),
  retryOvernightJobs: (jobIds: number[]) =>
    api.post<{ retried: number; skippedInFlight: number; skippedOther: number }>(`/api/ai/overnight/retry-jobs`, { jobIds }),
  cancelQueuedOvernight: (jobIds: number[]) =>
    api.post<{ cancelled: number; skippedRunning: number; skippedOther: number }>(`/api/ai/overnight/cancel-queued`, { jobIds }),
  getQueue: () => api.get<Record<string, unknown>>(`/api/ai/queue`),
  setPolicy: (body: { scope: string; scopeKey: string; enabled: boolean; mode: string }) => api.put<{ ok: boolean }>(`/api/ai/policies`, body),
};
